### ISSUE TITLE
Allow for etcd options specified via environment variable

### ISSUE THREAD

**Issue by lkysow** [aquasecurity/kube-bench#105]
I get failures like
```
1.5.1 Follow the etcd service documentation and configure TLS encryption.
Then, edit the etcd pod specification file /etc/kubernetes/manifests/etcd.yaml on the
master node and set the below parameters.
--ca-file=</path/to/ca-file>
--key-file=</path/to/key-file>

1.5.2 Edit the etcd pod specification file /etc/kubernetes/manifests/etcd.yaml on the master
node and set the below parameter.
--client-cert-auth="true"
```

However (via kops) I'm setting these via environment variable:
```
    - name: ETCD_CERT_FILE
      value: /srv/kubernetes/etcd.pem
    - name: ETCD_KEY_FILE
      value: /srv/kubernetes/etcd-key.pem
```

Kops code: https://github.com/kubernetes/kops/blob/37d4b53d0d5507025ef0bf89dcf13e62a355d1c0/protokube/pkg/protokube/etcd_manifest.go#L186

**Comment by tuminoid** [comment]
Also allow specifying them via `/etc/etcd/etcd.conf`, ie. as environment variables when running etcd on host and not in pod.

**Comment by ttousai** [comment]
@lkysow @tuminoid  closing this issue, please reopen if you still need this.
