### ISSUE TITLE
[Docs] Asff images are not loading

### ISSUE THREAD

**Issue by 64J0** [aquasecurity/kube-bench#1060]
**Overview**
 
The images in `asff` docs page is not loading because the path is wrong. I have created a PR to solve it: #1059 .

**How did you run kube-bench?**

...

**What happened?**

...

**What did you expect to happen:**

Load the images correctly.

**Environment** 

...

**Running processes**

...

**Configuration files**

...

**Anything else you would like to add:**

Accept my PR to solve this.

**Comment by yoavrotems** [comment]
Thanks
