### ISSUE TITLE
Issues while running within Tekton

### ISSUE THREAD

**Issue by xycloops123** [aquasecurity/kube-bench#1067]
**Overview**

I am seeing the below error while running kube-bench via tekton taskrun

```The Job "kube-bench" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app":"kube-bench", "controller-uid":"f8da6bd5-2076-46dd-8815-971475944d20", "job-name":"kube-bench"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)},```

**Environment** 

[What is your version of kube-bench? (run `kube-bench version`)]
0.6.5

**Configuration files**
Basic job.yaml file

**Comment by yoavrotems** [comment]
Hey @xycloops123  could you please try to run with 0.6.6 and check that there isn't running kube-bench jobs before?
