### ISSUE TITLE
error validating targets: No targets configured for gke-1.2.0

### ISSUE THREAD

**Issue by kbroughton** [aquasecurity/kube-bench#1070]
**Overview**

kubectl apply -f job-gke.yaml fails with the error in the logs
error validating targets: No targets configured for gke-1.2.0

**What did you expect to happen:**

expected a successful run

**Environment** 

GKE version 1.9

**Running processes**

it's not that complicated.

**Configuration files**

The config target changed from 
          command: ["kube-bench", "run", "--targets", "node,policies,managedservices", "--benchmark", "gke-1.0"]
to
          command: ["kube-bench", "run", "--targets", "node,policies,managedservices", "--benchmark", "gke-1.2.0"]

**Anything else you would like to add:**

This problem is fixed by removing the 0
          command: ["kube-bench", "run", "--targets", "node,policies,managedservices", "--benchmark", "gke-1.2"]

Creating an issue and PR to follow if I can figure this out.
I thought I'd see the error in the code, but it looks like 1.2.0 is consistent throughout.

```
grep -RHi gke-1.2 .
./job-gke.yaml:          command: ["kube-bench", "run", "--targets", "node,policies,managedservices", "--benchmark", "gke-1.2"] ------------------------- the file I changed
./cmd/util_test.go:			want: "gke-1.2.0",
./cmd/common_test.go:		{kubeVersion: "gke-1.2.0", succeed: true, exp: "gke-1.2.0"},
./cmd/common_test.go:		{n: "gke12", kubeVersion: "gke-1.2.0", benchmarkVersion: "", platformName: "", v: viperWithData, exp: "gke-1.2.0", callFn: withNoPath, succeed: true},
./cmd/common_test.go:			name:      "gke-1.2.0 valid",
./cmd/common_test.go:			benchmark: "gke-1.2.0",
./cmd/util.go:		return "gke-1.2.0"
./docs/architecture.md:| gke-1.2.0| controlplane, node, policies, managedservices |
./docs/running.md:| gke-1.2.0| master, controlplane, node, policies, managedservices |
./docs/running.md:kube-bench includes benchmarks for GKE. To run this you will need to specify `--benchmark gke-1.0` or `--benchmark gke-1.2.0` when you run the `kube-bench` command.
./docs/platforms.md:| CIS | [GKE 1.2.0](https://workbench.cisecurity.org/benchmarks/7534) | gke-1.2.0 | GKE |
./cfg/config.yaml:  "gke-1.2.0": "gke-1.2.0"
./cfg/config.yaml:  "gke-1.2.0":
./cfg/gke-1.2.0/policies.yaml:version: "gke-1.2.0"
./cfg/gke-1.2.0/controlplane.yaml:version: "gke-1.2.0"
./cfg/gke-1.2.0/managedservices.yaml:version: "gke-1.2.0"
./cfg/gke-1.2.0/node.yaml:version: "gke-1.2.0"
./cfg/gke-1.2.0/master.yaml:version: "gke-1.2.0"
```

I'm guessing somewhere in the code there is
major, minor = benchmark_version.split('.')
which fails because of the patch and the first error is swallowed raising the "no targets configured"

Searching for "No targets configured"

```
// validTargets helps determine if the targets
// are legitimate for the benchmarkVersion.
func validTargets(benchmarkVersion string, targets []string, v *viper.Viper) (bool, error) {
	benchmarkVersionToTargetsMap, err := loadTargetMapping(v)
	if err != nil {
		return false, err
	}
	providedTargets, found := benchmarkVersionToTargetsMap[benchmarkVersion]
	if !found {
		return false, fmt.Errorf("No targets configured for %s", benchmarkVersion)
	}
```

Oh, I see that the job-gke.yaml pulls aquasec/kube-bench:latest which hasn't been updated in 2 months.
This is likely the problem.

**Comment by mozillazg** [comment]
@kbroughton 

> Oh, I see that the job-gke.yaml pulls aquasec/kube-bench:latest which hasn't been updated in 2 months.
This is likely the problem.

Yes, you are right, the latest image does not support this benchmark, the reason can be found here: https://github.com/aquasecurity/kube-bench/pull/915#issuecomment-981050070

> It's not missing but just not there yet, it will be released in the next release, docker image used to be created from each push to main, but we changed it to be triggered by new tags.
Because it used to create unstable images for each new push. If you have any more questions in the subject please open a issue about it.

**Comment by yoavrotems** [comment]
Fixed by https://github.com/aquasecurity/kube-bench/discussions/1080
