### ISSUE TITLE
Documentation should be more clear about outputfile flag

### ISSUE THREAD

**Issue by BasBremerTC** [aquasecurity/kube-bench#1090]
**Overview**

At the page https://github.com/aquasecurity/kube-bench/blob/main/docs/flags-and-commands.md a flag is shown to output to json file (--outputfile).
In order to do this the --json flag also is needed.
This cant be found in the documentation.

Suggestion would be to add an example or write some more details behind the flag.

**Comment by mozillazg** [comment]
Thanks for your suggestion! We'll improve the document and PR is welcome.

**Comment by mozillazg** [comment]
@BasBremerTC I just have created a PR for this: https://github.com/aquasecurity/kube-bench/pull/1094. What do you think about it? Does it be more clear?
