### ISSUE TITLE
ASFF: timestamp in finding ID leads to duplicate Security Hub findings

### ISSUE THREAD

**Issue by ben-harvey** [aquasecurity/kube-bench#1116]
**Overview**
I'm using the `--asff` flag to generate ASFF findings and import them to Security Hub.  When encoding the results, `kube-bench` uses a timestamp as a component of the finding ID:
https://github.com/aquasecurity/kube-bench/blob/aedc2942bdb22455117382dd02e1d18212ed0a66/check/controls.go#L252
The result is that multiple runs of `kube-bench` will generate unique IDs, even if the underlying resource and vulnerability are unchanged.  When importing findings, Security Hub uses the finding ID to decide whether to update an existing finding or create a new one. Since each `kube-bench` ID is unique due to the timestamp, on subsequent runs I'm ending up with duplicate findings in Security Hub for the same resource and vulnerability, which I need to deduplicate by resolving all but the most recently generated finding.

Note that ASFF findings already have `CreatedAt` and `UpdatedAt` fields that track the timestamp of findings.  

**How did you run kube-bench?**

I am running `kube-bench` with the EKS benchmark as a container on EKS with the `--asff` flag

**What happened?**

See above

**What did you expect to happen:**

See above

**Environment** 

I build the `kube-bench` image from `main`

**Running processes**

N/A

**Configuration files**

N/A

**Anything else you would like to add:**

**Comment by mozillazg** [comment]
@ben-harvey Thanks for reporting. I'll take a look at it.
