### ISSUE TITLE
Remediation example for --reques-timeout is invalid

### ISSUE THREAD

**Issue by tuminoid** [aquasecurity/kube-bench#113]
Remediation example for `--request-timeout` is invalid, as parameter needs to have unit defined, ie. `300s` or `5m`, and not just integer.

```
  - id: 1.1.37
    text: "Ensure that the --request-timeout argument is set as appropriate (Scored)"
    audit: "ps -ef | grep $apiserverbin | grep -v grep"
    type: "manual"
    remediation: |
      Edit the API server pod specification file $apiserverconf
      and set the below parameter as appropriate and if needed. For example,
      --request-timeout=300
    scored: true
```

**Comment by ttousai** [comment]
Thank you @tuminoid  for catching that. The remediation is straight from the CIS kubernetes benchmark. We can fix it in kube-bench and we will have to notify CIS.
cc @lizrice

**Comment by lizrice** [comment]
I have proposed the change to the CIS, and since it's obviously wrong corrected it in our config files too.
