### ISSUE TITLE
ASFF: findings with the same control ID overwrite each other

### ISSUE THREAD

**Issue by ben-harvey** [aquasecurity/kube-bench#1179]
### Overview
We are running kube-bench against multiple EKS clusters that share a common configuration. That means that we often get findings for the same control ID across multiple clusters.

The PR for my previous [kube-bench issue](https://github.com/aquasecurity/kube-bench/issues/1116) which removed the timestamp from the finding ID, introduced a new problem.  By removing the timestamp (which guaranteed a unique ID), findings from different clusters for the same control now generate identical IDs.  These findings effectively overwrite each other (by updating an existing finding rather than creating a new one, despite the fact that the underlying resource is different) since they now share identical finding IDs.  

 I'm surprised that this is the behavior on the AWS side, since the findings have distinct `Resources.Id` fields, but apparently AWS doesn't disambiguate findings based on this field. I have tested this by running kube-bench in two different clusters, generating findings with identical finding IDs but different resource IDs.  The first finding is effectively overwritten by the second.

I think the solution is to add the cluster ARN to the finding ID, which would mean each combination of cluster and control ID would be unique. 

### How did you run kube-bench?

I am running kube-bench with the EKS benchmark as a container on EKS with the --asff flag

### What happened?

See above

### What did you expect to happen:

See above

### Environment

I build the kube-bench image from main

### Running processes

N/A

### Configuration files

N/A

### Anything else you would like to add:

**Comment by mozillazg** [comment]
@ben-harvey Thanks for reporting. I'll take a look at it and PR is welcome.

**Comment by mozillazg** [comment]
It may be necessary to add the node name(add a new environment variable to get the node name) to the finding ID too?
