### ISSUE TITLE
latest docker hub tag fails installation

### ISSUE THREAD

**Issue by kaspernissen** [aquasecurity/kube-bench#118]
Been using kube-bench on/off during the day, and suddently the
```
docker run --rm -v `pwd`:/host aquasec/kube-bench:latest install
```
fails with the following:
```
cp: can't stat '/cfg/*': No such file or directory
cp: can't stat '/kube-bench': No such file or directory
===============================================
kube-bench is now installed on your host
Run ./kube-bench to perform a security check
===============================================
```

I see latest has been updated 30 min ago. Maybe it's just a mismatch between the docs and what you are working on. 

Was able to use the `:logo` tag to get going again. BTW, what's up the versioning on docker hub? 

And of course, thank you for an awesome tool! :)

**Comment by wmedlar** [comment]
Sorry, this was my bad, I should've caught it! `:latest` is installing properly now.

**Comment by kaspernissen** [comment]
No worries. I can confirm that `:latest` is now working again. Will close the issue. Thank you for a great tool.
