### ISSUE TITLE
Kube-bench imports the same finding with the same finding arn from different clusters to Security Hub

### ISSUE THREAD

**Issue by artemisok** [aquasecurity/kube-bench#1190]
**Overview**

[A clear and concise description of what the bug is] 

**How did you run kube-bench?**

We have deployed kube-bech as a job based on the template to submit the findings to securiy hub.
https://github.com/aquasecurity/kube-bench/blob/main/job-eks-asff.yaml

**What happened?**

We have observed that the imports of findings from same account are not having unique ids therefore the findings from each clusters are overwriting each other. 
Finding ID: arn:aws:securityhub:eu-central-1::product/aqua-security/kube-bench434848391857EKSnodeID+3.2.9

**What did you expect to happen:**

I would expect each finding has their unique id, for example:
Finding ID: arn:aws:securityhub:eu-central-1:accountid:subscription/aws-foundational-security-best-practices/v/1.0.0/EC2.8/finding/5f3aa932-3494-4812-895a-89ba8456fb49

**Environment** 

aquasec/kube-bench:latest

This happens regardless of the kubernetes version.

**Running processes**

This happens at all nodes as it is an implementation bug.

**Comment by mozillazg** [comment]
@artemisok Is this issue a duplicate of the https://github.com/aquasecurity/kube-bench/issues/1179?
