### ISSUE TITLE
Kube-bench skips master node configuration checks while running it on default namespace

### ISSUE THREAD

**Issue by muddassir-r** [aquasecurity/kube-bench#1239]
**Overview**

While running the kube-bench on k3s cluster it only performs"4. Worker Node Security Configuration" and "5. Kubernetes Policies"  checks. 

**How did you run kube-bench?**

1. Created the job.yaml from https://github.com/aquasecurity/kube-bench/blob/main/job.yaml
 2. kubectl apply -f job.yaml (Which i think created a pod in default namespace)
 3. kubectl logs kube-bench-xxxx

**What did you expect to happen:**

Was expecting to perform all the cis-benchmark check from 1 to 5 .

**Environment** 

What is your version of kube-bench? => kube-bench:v0.6.8 

What is your version of Kubernetes?
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s1", GitCommit:"acad8ef8402021d6a78405c0b4fe420982e5ad1e", GitTreeState:"clean", BuildDate:"2021-09-20T17:40:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s1", GitCommit:"acad8ef8402021d6a78405c0b4fe420982e5ad1e", GitTreeState:"clean", BuildDate:"2021-09-20T17:40:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

**Anything else you would like to add:**
[kube-bench-result.txt](https://github.com/aquasecurity/kube-bench/files/9297077/kube-bench-result.txt)

[Miscellaneous information that will assist in solving the issue.]

**Comment by mozillazg** [comment]
@muddassir-r Hi, If you want to check master node configuration checks, you should run with job-master.yaml instead of job.yaml. And for your case to perform all the cis-benchmark checks from 1 to 5,  before applying job-master.yaml you should change the `command` value to `["kube-bench"]`

https://github.com/aquasecurity/kube-bench/blob/113ee337ee900f2e5b65f4471420a5fa08a94e97/job-master.yaml#L30

**Comment by muddassir-r** [comment]
@mozillazg I tried the above suggestion and I am getting the same result. It covers only 4 and 5 checks.

**Comment by mozillazg** [comment]
> @mozillazg I tried the above suggestion and I am getting the same result. It covers only 4 and 5 checks.

@muddassir-r How about change the `command` value to `["kube-bench", "run", "--targets", "master,node,controlplane,etcd,policies"]`?

**Comment by muddassir-r** [comment]
[output.txt](https://github.com/aquasecurity/kube-bench/files/9395076/output.txt)
@mozillazg attaching the error message obtained. 
"field is immutable"

**Comment by mozillazg** [comment]
@muddassir-r You should delete the old job first then apply new job yaml:
```
$ kubectl delete -f job-master.yaml
$ # change the command value in job-master.yaml to ["kube-bench", "run", "--targets", "master,node,controlplane,etcd,policies"]
$ vim job-master.yaml
$ kubectl apply -f job-master.yaml
```

**Comment by muddassir-r** [comment]
@mozillazg This actually worked, Thanks for resolving.
