### ISSUE TITLE
Benchmark Job on Control Plane does not work with K8s 1.24.x

### ISSUE THREAD

**Issue by ddubson** [aquasecurity/kube-bench#1250]
**Overview**

Benchmarking Job's Pod is stuck in `Pending` state when running against the Control Plane node on K8s 1.24.x. This is due to the fact that K8s 1.24.x replaced label `node-role.kubernetes.io/master` to `node-role.kubernetes.io/control-plane` and added a new taint of the same label.

Sources:
* https://kubernetes.io/blog/2022/04/07/upcoming-changes-in-kubernetes-1-24/#api-removals-deprecations-and-other-changes-for-kubernetes-1-24
* https://github.com/kubernetes/kubernetes/pull/107533

**How did you run kube-bench?**

`wget` the `job-master.yaml` file from the `main` branch and apply it on the K8s 1.24.x cluster. `k apply -f kube-master.yaml`

**What happened?**

`Pod` associated with the benchmarking `Job` is stuck in `Pending` state.

**What did you expect to happen:**

`Pod` should run and complete successfully.

**Environment** 

Kube bench v0.6.2

K8s v1.24.0

**Comment by mozillazg** [comment]
Fixed via https://github.com/aquasecurity/kube-bench/pull/1251
