### ISSUE TITLE
Docker build fail due to glibc

### ISSUE THREAD

**Issue by crenzoaws** [aquasecurity/kube-bench#1277]
The Docker build is failing due to an upstream package issue caused by glibc-2.33 and alpine 

`Step 18/28 : RUN apk add glibc-2.33-r0.apk
 ---> Running in fd3280d2775e
(1/1) Installing glibc (2.33-r0)
ERROR: glibc-2.33-r0: trying to overwrite etc/nsswitch.conf owned by alpine-baselayout-data-3.2.0-r23.
1 error; 17 MiB in 21 packages
The command '/bin/sh -c apk add glibc-2.33-r0.apk' returned a non-zero code: 1
makefile:43: recipe for target 'build-docker' failed
make: *** [build-docker] Error 1
Error: Process completed with exit code 2.`

**Comment by mozillazg** [comment]
Fixed via https://github.com/aquasecurity/kube-bench/pull/1280
