### ISSUE TITLE
Document example kubectl commands for running tool against a cluster

### ISSUE THREAD

**Issue by davidarcher** [aquasecurity/kube-bench#128]
While we have the commands documented for running kube-bench from a host directly using docker, I imagine most users will want to be able to point it at a remote cluster and get the audit result.

Here are the commands I used to run kube-bench using kubectl:

```
kubectl run --rm -i -t kube-bench-master --image=aquasec/kube-bench:latest --restart=Never --overrides="{ \"apiVersion\": \"v1\", \"spec\": { \"hostPID\": true, \"nodeSelector\": { \"kubernetes.io/role\": \"master\" }, \"tolerations\": [ { \"key\": \"node-role.kubernetes.io/master\", \"operator\": \"Exists\", \"effect\": \"NoSchedule\" } ] } }" -- master --version 1.8
```

```
kubectl run --rm -i -t kube-bench-node --image=aquasec/kube-bench:latest --restart=Never --overrides="{ \"apiVersion\": \"v1\", \"spec\": { \"hostPID\": true } }" -- node --version 1.8
```

It would be nice to have this documented in the README.

**Comment by ttousai** [comment]
@davidarcher thanks for the great suggestion I will add this.

**Comment by lizrice** [comment]
Added in #130. Thanks @davidarcher!

**Comment by udaygundala** [comment]
When I run below from remote system, my pd is always showing in pending status and no result for the command. 
kubectl run --rm -i -t kube-bench-master --image=aquasec/kube-bench:latest --restart=Never --overrides="{ \"apiVersion\": \"v1\", \"spec\": { \"hostPID\": true, \"nodeSelector\": { \"kubernetes.io/role\": \"master\" }, \"tolerations\": [ { \"key\": \"node-role.kubernetes.io/master\", \"operator\": \"Exists\", \"effect\": \"NoSchedule\" } ] } }" -- master --version 2.0 --namespace kube-system
---------------------

kubectl get pods
NAME                READY     STATUS    RESTARTS   AGE
kube-bench-master   0/1       Pending   0          5s

In events I see this 
LAST SEEN   FIRST SEEN   COUNT     NAME                                 KIND      SUBOBJECT                          TYPE      REASON                  SOURCE                              MESSAGE
19m         25m          26        kube-bench-master.154f5a33d29e677f   Pod                                          Warning   FailedScheduling        default-scheduler                   0/6 nodes are available: 6 node(s) didn't match node selector.

Im I missing anything here.
