### ISSUE TITLE
--unscored flag is undocumented

### ISSUE THREAD

**Issue by joebowbeer** [aquasecurity/kube-bench#1281]
**Overview**

The `--unscored` flag is not documented with the other flags:

https://github.com/aquasecurity/kube-bench/blob/main/docs/flags-and-commands.md#flags 

**How did you run kube-bench?**

N/A

**What happened?**

`--unscored` flag is implemented

**What did you expect to happen:**

`--unscored` flag is documented

**Environment** 

**Running processes**

**Configuration files**

**Anything else you would like to add:**

https://github.com/aquasecurity/kube-bench/commit/9f92e81361a1d4b883e81c42e00e588e85db9a11

**Comment by mozillazg** [comment]
Thanks for reporting and PR is welcome.
