### ISSUE TITLE
`if` with identical `then` and `else` branches

### ISSUE THREAD

**Issue by chavacava** [aquasecurity/kube-bench#1288]
In the following code, both control branches do the same.

https://github.com/aquasecurity/kube-bench/blob/4d76c77c6a9fcde493e99282575e9aebd70c6a9d/cmd/kubernetes_version_test.go#L267-L275

It could be simplified into:
```go
if k8sURL != c.expected { 
 	t.Errorf("Expected %q but Got %q", k8sURL, c.expected) 
}
```

Found by [revive](https://github.com/mgechev/revive) (rule [`identical-branches`](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#identical-branches))

**Comment by joebowbeer** [comment]
Dup of #1295
