### ISSUE TITLE
`if` statement with identical `then` and `else` branches

### ISSUE THREAD

**Issue by chavacava** [aquasecurity/kube-bench#1295]
https://github.com/aquasecurity/kube-bench/blob/dd39b19ffcd26d27b790916e844e3abf87b4a970/cmd/kubernetes_version_test.go#L267-L275

Could be simplified to just

```go
if k8sURL != c.expected {
	t.Errorf("Expected %q but Got %q", k8sURL, c.expected)
}
```
?

Found with [revive](https://github.com/mgechev/revive)

**Comment by mozillazg** [comment]
fixed via #1304
