### ISSUE TITLE
Are some of these really security issues?

### ISSUE THREAD

**Issue by jeroenjacobs1205** [aquasecurity/kube-bench#133]
Hi,

What is the security issue with the following checks:

```
[FAIL] 2.1.6 Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Scored)
[FAIL] 2.1.11 Ensure that the --event-qps argument is set to 0 (Scored)
[FAIL] 2.1.8 Ensure that the --make-iptables-util-chains argument is set to true (Scored)
```

In fact, changing some of those values might have a serious performance impact on your cluster. I would really like to know why you consider these as security risks.

The following kubelet parameter is deprecated btw:

`[FAIL] 2.1.9 Ensure that the --keep-terminated-pod-volumes argument is set to false (Scored)`

**Comment by lizrice** [comment]
In kube-bench we're implementing the tests as described in the [CIS Kubernetes Benchmark](https://www.cisecurity.org/benchmark/kubernetes/) which includes information about why these recommendations are made. The CIS is a good place to join in the discussion to improve the benchmarks themselves. 

Thank you for pointing out the --keep-terminated-pod-volumes argument. I have proposed a change on the CIS benchmark about removing that test.

**Comment by Sharma-Rajat** [comment]
https://github.com/kubernetes/kubernetes/pull/47539 deprecated since 1.8

**Comment by joebowbeer** [comment]
I notice that the `--event-qps` advice is causing a lot of confusion and potential [mis-configuration](https://github.com/awslabs/amazon-eks-ami/pull/391).

In the command line option, 0 is documented to use the default value of 5, whereas in the config file, a value of 0 is documented to disable rate limiting, which is precisely what this rule is supposed to prevent.

[https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go](https://github.com/kubernetes/kubernetes/blob/06e107081e4e0182efb9daa0daf7f2ae12272704/cmd/kubelet/app/options/options.go#L422)
[https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults.go](https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/pkg/kubelet/apis/config/v1beta1/defaults.go#L98)
