### ISSUE TITLE
flag value test may test wrong flag

### ISSUE THREAD

**Issue by xelalexv** [aquasecurity/kube-bench#137]
I've integrated kube-bench tests in our CI, but have seen it flaking out occasionally. Digging into it, I have found the following problem. I'm not sure yet whether that causes the test flakes, but it's a good candidate, so I thought I'd report it right away.

The flag value test in [`check/test.go`](https://github.com/aquasecurity/kube-bench/blob/3408e0f865e5c02fc38c9ee5f2b2ff5e08ca3b5b/check/test.go#L52) may potentially check using the value of the wrong flag. This can happen with flags where one flag is a prefix of the other, depending on the order in which the flags were provided to the command binary being checked.

For example, `--admission-control` is a prefix of `--admission-control-config-file`. When checking the value of `--admission-control`, the regular expression `(--admission-control)(=)*([^\s]*) *` would yield the flag value `-config-file=...`, if `--admission-control-config-file` is given before `--admission-control` ([check out in Go playground](https://play.golang.org/p/ey7MA4rHe2A)).

When adapting the regexp to `(--admission-control)([=\s])+([^\s]*) *`, it works.

**Comment by ttousai** [comment]
@xelalexv thank you for catching this. Your suggested regexp looks like what we want:
```
cat > test <<EOF
--admission-control RBAC,Node             
--admission-control=RBAC,Node        
--admission-control-config-file=foobar.ext                                          
EOF

grep -E '(--admission-control)[=\s]+([^\s]*) *' test
```
Produces:
```
--admission-control=RBAC,Node
```
as expected.
