### ISSUE TITLE
No logs shown after installing it on kubernetes cluster

### ISSUE THREAD

**Issue by bernardoortega** [aquasecurity/kube-bench#1392]
Just cloned the repo on master node, and perform following commands:

kubectl apply -f job.yaml
kubectl get pods:

ubuntu@k8s-control:~/kube-bench$ kubectl get pods
NAME               READY   STATUS    RESTARTS   AGE
kube-bench-m2pcq   1/1     Running   0          11m
my-pod             1/1     Running   0          8d

kubectl logs kube-bench-m2pcq   ----> nothing shown

If i do it as root:
sudo kubectl get pods:
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by bernardoortega** [comment]
i was too fast too furious. it was matter of some minutes until it runs scan. Anyway, results are way less that if I run it from command line from master control plane node. Is this maybe because with command line you have access to host and from Pod you do not?

**Comment by mozillazg** [comment]
@bernardoortega you should use the [job-master.yaml](https://github.com/aquasecurity/kube-bench/blob/main/job-master.yaml) to run the 1.x (control plane checks) on the master node.
