### ISSUE TITLE
Releases missing for Macbooks (Intel and M1 arch)

### ISSUE THREAD

**Issue by leodotcloud** [aquasecurity/kube-bench#1419]
**Overview**

Currently, there is no way to run kube-bench on Macbooks

**Comment by mozillazg** [comment]
IMHO, that is expected. Are there any cases that need to run kube-bench on Macbooks?

**Comment by leodotcloud** [comment]
`kube-bench` can be used to run checks on "offline" data. This is especially true for developers during the authoring of checks. And MacBooks are quite popular among developers.

If you could point me to the file responsible for the builds/releases, I can make a PR. Happy to contribute again to the project.

**Comment by mozillazg** [comment]
Got it. Here is the file: https://github.com/aquasecurity/kube-bench/blob/main/.goreleaser.yml#L10 and you can test it with https://github.com/goreleaser/goreleaser. Feel free to send a pull request.

**Comment by leodotcloud** [comment]
Thanks, for the pointer!

**Comment by leodotcloud** [comment]
@mozillazg Please review the [PR](https://github.com/aquasecurity/kube-bench/pull/1428), when you get a chance.
