### ISSUE TITLE
getting error while installing kube bench from source.

### ISSUE THREAD

**Issue by bond007007** [aquasecurity/kube-bench#143]
At first I followed the procedure for setting up $GOPATH. 
After that I went for installing kube bench from source 
the first command (go get github.com/aquasecurity/kube-bench)  
I am getting the error something like ERROR:/usr/***************************** : too many errors.

so how to resolve this error. 
env- linux
go - tried in both 1.10.1 and  1.9.4
kubernetes: 1.9.6

**Comment by bond007007** [comment]
the issue resolved.... actually there was problem in cluster, then I tried in diffrent cluster it worked.

**Comment by lizrice** [comment]
Thanks for letting us know
