### ISSUE TITLE
Kube-bench Fail to run on Tencent Kubernetes Engine Orchestrator

### ISSUE THREAD

**Issue by deven0t** [aquasecurity/kube-bench#1439]
**Overview**

Whenever we are running kube-bench on Tencent Kubernetes Engine Orchestrator(Tencent Cloud ) cluster, it exists with an error 
`error looking for file /etc/kubernetes/kubelet/kubelet-config.json: stat /etc/kubernetes/kubelet/kubelet-config.json: not a directory`

**How did you run kube-bench?**

We run with pod yaml file. It is same as this one https://github.com/aquasecurity/kube-bench/blob/main/job-node.yaml

**What happened?**
Pod gives error in the log
`error looking for file /etc/kubernetes/kubelet/kubelet-config.json: stat /etc/kubernetes/kubelet/kubelet-config.json: not a directory`

```
➜ ✗ kubectl logs kube-bench-4td6d 

error looking for file /etc/kubernetes/kubelet/kubelet-config.json: stat /etc/kubernetes/kubelet/kubelet-config.json: not a directory
```

**Comment by mozillazg** [comment]
Fixed via https://github.com/aquasecurity/kube-bench/pull/1440
