### ISSUE TITLE
Run kube-bench on EKS or GKE master

### ISSUE THREAD

**Issue by weisinc** [aquasecurity/kube-bench#145]
Is it possible to run the master check on EKS or GKE ?
I am getting this error:

need apiserver executable but none of the candidates are running
pod default/kube-bench-node terminated (Error)

I can run the node check without any problems.

**Comment by ttousai** [comment]
@weisinc please run kube-bench with with `-v 3` and share the output.

**Comment by weisinc** [comment]
$ ./kubectl run --rm -i -t kube-bench-node --image=aquasec/kube-bench:fix-typo --restart=Never --overrides="{ \"apiVersion\": \"v1\", \"spec\": { \"hostPID\": true } }" -- master --version 1.8 -v 3
I0725 19:36:10.831403   11052 util.go:55] [ps -C kube-apiserver -o cmd --no-headers]: exit status 1
I0725 19:36:10.831500   11052 util.go:200] executable 'kube-apiserver' not running
I0725 19:36:10.836283   11052 util.go:55] [ps -C hyperkube -o cmd --no-headers]: exit status 1
I0725 19:36:10.836388   11052 util.go:200] executable 'hyperkube apiserver' not running
I0725 19:36:10.840191   11052 util.go:55] [ps -C apiserver -o cmd --no-headers]: exit status 1
I0725 19:36:10.840245   11052 util.go:200] executable 'apiserver' not running

need apiserver executable but none of the candidates are running
pod default/kube-bench-node terminated (Error)

**Comment by weisinc** [comment]
Looks like there is an error when util.go:55 is trying to get the running apiserver command:  "ps -C hyperkube -o cmd --no-headers".
When I execute it on a master node, I get the following output:

ubuntu@master1:~$ ps -C "hyperkube" -o cmd  --no-headers
/hyperkube proxy --v=2 --kubeconfig=/etc/kubernetes/kube-proxy-kubeconfig.yaml ...etc.
/hyperkube apiserver --advertise-address=10.1.1.179 --etcd-servers=https://10.1.1.179:2379 ....etc.
/hyperkube scheduler --leader-elect=true --kubeconfig=/etc/kubernetes/kube-scheduler ....etc.
/hyperkube controller-manager --kubeconfig=/etc/kubernetes/kube-controller-manager ...etc.

Shouldn't it be "hyperkube apiserver" instead of "hyperkube" ?

**Comment by ttousai** [comment]
@weisinc closing this ticket please reopen if you still need this.
