### ISSUE TITLE
Can't run on kops-provisioned cluster v1.10.2

### ISSUE THREAD

**Issue by weisinc** [aquasecurity/kube-bench#146]
I am running a kops-deployed cluster, running kubernetes v1.10.2
I am getting below error. Is this expected as the k8s version is not supported?

$ kubectl run --rm -i -t kube-bench-node --image=aquasec/kube-bench:fix-typo --restart=Never --overrides="{ \"apiVersion\": \"v1\", \"spec\": { \"hostPID\": true } }" -- node --version 1.8 -v 3
If you don't see a command prompt, try pressing enter.
                                                      Error attaching, falling back to logs: unable to upgrade connection: container kube-bench-node not found in pod kube-bench-node_default
I0725 22:02:01.380608   18505 util.go:55] [ps -C hyperkube -o cmd --no-headers]: exit status 1
I0725 22:02:01.380759   18505 util.go:200] executable 'hyperkube kubelet' not running
I0725 22:02:01.392091   18505 util.go:110] Component kubelet uses running binary kubelet
I0725 22:02:01.403533   18505 util.go:55] [ps -C kube-proxy -o cmd --no-headers]: exit status 1
I0725 22:02:01.403627   18505 util.go:200] executable 'kube-proxy' not running
I0725 22:02:01.413758   18505 util.go:55] [ps -C hyperkube -o cmd --no-headers]: exit status 1
I0725 22:02:01.413868   18505 util.go:200] executable 'hyperkube proxy' not running
I0725 22:02:01.425186   18505 util.go:55] [ps -C proxy -o cmd --no-headers]: exit status 1
I0725 22:02:01.425381   18505 util.go:200] executable 'proxy' not running

need proxy executable but none of the candidates are running
pod default/kube-bench-node terminated (Error)

I see that the errors say kubelet and kube-proxy are not running, etc.  I did verify that they are in fact  installed and running.

**Comment by ttousai** [comment]
@weisinc I am closing this ticket, please reopen if you still want this.
