### ISSUE TITLE
docs: trivy not mentioned in the README

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/kube-bench#1470]
Currently, we are not mentioning trivy in the kube-bench README. Thus, we are still getting questions around kube-bench functionality that is integrated in the trivy operator. I would like to have a section on trivy in the README @itaysk what do you think?

**Comment by AHB102** [comment]
Is this issue still open ? I would like to contribute.

**Comment by itaysk** [comment]
the issue is still incomplete, but we prefer to leave it for a core team member (@AnaisUrlichs) due to the nature of the issue

**Comment by AnaisUrlichs** [comment]
Sorry, the changes are here #1485

**Comment by itaysk** [comment]
closed by #1485
