### ISSUE TITLE
kube-bench doesn't recognize a kubernetes node

### ISSUE THREAD

**Issue by lirkog86** [aquasecurity/kube-bench#150]
kueb-bench relies on the existence of "kubectl" to identify a k8s node.
in some k8s deployments (acs), k8s nodes are not installed with this utility which cause a failure in kube-bench.
need to find a better way to identify if a node is k8s or not.

**Comment by lizrice** [comment]
It's also looking for kubelet too - isn't that present?

**Comment by lirkog86** [comment]
In some deployments kubelet runs as a container so you won't find it with the LookPath function

**Comment by ttousai** [comment]
@lirkog86 this is true. We will take a look at how to handle such deployments. We also welcome any PR which will fix this.

**Comment by ttousai** [comment]
@lirkog86 kube-bench now has `--version` to allow specifying which version of k8s is running so kubectl is no longer required.

Closing this issue.
