### ISSUE TITLE
Allow passing the Kubernetes version by environment variable

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#152]
The --version flag we pass in selects the test config files to use so that you don't have to have kubelet or kubectl on the path to find the correct Kubernetes version (noting that this way we need to specify 1.8 to pick up the 1.8 files even if the running version is 1.9). 

It would be nice to allow the version to be passed in by environment variable, so that if another executable calls kube-bench (rather than the user invoking it directly) it can pick up the right version. This would also help in the circumstance where kubelet is in a container (e.g. hyperkube on ACS) and can't be found on the executable path on the host, 

We could also default to 1.8 (or the latest published CIS version) if no version can be found at all.

**Comment by VineethReddy02** [comment]
From my understanding is this enhancement specific to having a field in the yaml manifest file i.e job yaml. To pick the version as per the requirement? 
Can someone point me to some good first issues and minor enhancements in getting started :)
Looking forward to contributing to aqua's OSS stack.
