### ISSUE TITLE
file permissions test false positives

### ISSUE THREAD

**Issue by joewilliams** [aquasecurity/kube-bench#160]
I'm not sure I am understanding why [this test is failing](https://github.com/aquasecurity/kube-bench/blob/master/cfg/1.8/master.yaml#L876-L902). What am I missing? Is this a false positive since the file is missing?

```
{
  "test_number": "1.4.7",
  "test_desc": "Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Scored)",
  "type": "",
  "test_info": [
    "Run the below command (based on the file location on your system) on the master node.\nFor example,\nchmod 644 /etc/kubernetes/manifests/etcd.yaml\n"
  ],
  "status": "FAIL"
}
```

```
1.4.7 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 /etc/kubernetes/manifests/etcd.yaml
```

```
# /bin/sh -c 'if test -e /etc/kubernetes/manifests/etcd.yaml; then stat -c %a /etc/kubernetes/manifests/etcd.yaml; fi'
# echo $?
0
```

**Comment by joewilliams** [comment]
Also, some context, we don't have a `etcd.yaml` at all since we run it on bare metal instead of in kube.

**Comment by ttousai** [comment]
@joewilliams your first thought is correct. The CIS spec requires that this file exists and be checked to PASS . Anything else is a FAIL condition.

You can ignore this FAIL, but I recommend you take a look at the CIS Kubernetes Benchmark and implement the recommendations manually.

**Comment by joewilliams** [comment]
@ttousai thanks for the confirmation! 🙇
