### ISSUE TITLE
Support CIS kubernetes CIS-1.9 for k8s v1.27 - v1.29

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/kube-bench#1616]
## Description
Support CIS kubernetes CIS-1.9 for k8s v1.27 - v1.29

- Related #1613

**Comment by andypitcher** [comment]
### CIS Kubernetes Benchmark CIS-1.9

**CIS Workbench:** https://workbench.cisecurity.org/benchmarks/16828
**K8s version:** v1.27 to v1.29
**Changelog details:**
All the checks remain the same as CIS-1.8, only `5.1.1 `to `5.1.6` in policies were changed from `No Scored (Manual)` to `Scored (Automated)`

**Comment by andypitcher** [comment]
@chen-keinan IMO we can close this issue.
