### ISSUE TITLE
Missing module 5.6

### ISSUE THREAD

**Issue by nguyenthanhvu240** [aquasecurity/kube-bench#1627]
Check kubect logs and the document of https://downloads.cisecurity.org/#/ CIS Kubernetes Benchmarks v1.9,you will not see module 5.6. I dont know what function is missing

**Comment by andypitcher** [comment]
@nguyenthanhvu240 that's a good point - Actually it looks like 5.6 has been absent for as long as the `5 - Policies` recommendations have been around CIS Kubernetes benchmarks.

**Comment by andypitcher** [comment]
I suggest we close this issue @afdesk , as it's something that originates from CIS Workbench. Here is the discussion related: https://workbench.cisecurity.org/community/43/discussions/11042
