### ISSUE TITLE
CIS 1.9 Control Node Checks 1.1.13, 1.1.14 show fail with correct permissions/ownership. no actual output reported

### ISSUE THREAD

**Issue by btray900** [aquasecurity/kube-bench#1644]
**Overview**

CIS 1.9 implements a permission and ownership check for /etc/kubernetes/admin.conf and /etc/kubernetes/super-admin.conf.

The tested control node shows 600 for both files, as well as root:root ownership but the check is reporting FAIL for both `1.1.13` and `1.1.14` in `master.yaml` for `cis-1.9`

Also CIS 1.9 master.yaml 1.1.14 has an incorrect remediation path (chmod versus chown) for super-admin.conf.

![image](https://github.com/user-attachments/assets/a706b315-97a6-4fa5-a115-fabb41ed059d)

**How did you run kube-bench?**

kube-bench --benchmark cis-1.9 --json

**What happened?**

Permissions and ownership are correct, but benchmark reports FAIL.

![image](https://github.com/user-attachments/assets/93a17cec-8372-4217-86d4-95d55a1409a0)

![image](https://github.com/user-attachments/assets/af3a8b53-1d78-4920-9881-482904ec5b99)

Actual output is not captured for CIS-1.9

![image](https://github.com/user-attachments/assets/3d8bd671-8216-41f3-af80-7764484568c7)

[Comparison] Actual output was captured as expected for CIS-1.8

![image](https://github.com/user-attachments/assets/d92dc23e-3e24-4652-b370-ef4a18aa5b23)

**What did you expect to happen:**

The tests would pass due to the correct permissions and ownership for the admin.conf and super-admin.conf on Kubernetes 1.29.4

**Environment** 

kube-bench: v0.8.0
kubernetes: 1.29.4

**Comment by btray900** [comment]
I notice the CIS-1.9 master.yaml 1.1.14 test uses /tmp for the path to confs in the audit section, /etc/kubernetes is the actual path on the controller tested.

![image](https://github.com/user-attachments/assets/672da294-5bba-4b60-a56e-f648d8b4a376)

**Comment by mozillazg** [comment]
@btray900 Thanks for reporting.

* For 1.1.13, Could you please attach the debug logs? (via `kube-bench --benchmark cis-1.9 -c 1.1.13 -v 3`) 
* For 1.1.14, Yes, it looks like is a typo.

**Comment by btray900** [comment]
Debug for 1.1.13 attached
[kb_1_1_13_debug.txt](https://github.com/user-attachments/files/16335372/kb_1_1_13_debug.txt)

**Comment by andypitcher** [comment]
@btray900 nice catch thanks. 
@mozillazg I can make a PR to fix this up if needed.

**Comment by mozillazg** [comment]
@andypitcher Feel free to send a pull request. Thanks!

**Comment by andypitcher** [comment]
IMO This issue can be now closed, since #1649 has been merged.
