### ISSUE TITLE
GKE 1.6 CIS benchmark for GCP environment

### ISSUE THREAD

**Issue by guyjerby** [aquasecurity/kube-bench#1662]
CIS benchmark for GKE 1.6 is required:

https://workbench.cisecurity.org/benchmarks/16093

**Comment by guyjerby** [comment]
@ttousai is creating the benchmark

**Comment by deboshree-b** [comment]
I added a PR here
https://github.com/aquasecurity/kube-bench/pull/1677
@ttousai @guyjerby

**Comment by guyjerby** [comment]
Thanks @deboshree-b , can you describe in a summary the changes that you have made?
I see that you mapped the GKE 1.6 version and files and also added new checks - were they missed in the previous PR from @ttousai or you made fixes?

**Comment by ciphx** [comment]
Hello @guyjerby, I was upgrading CIS benchmarks for my org, so thought of adding an upstream PR. I didn't know that there were open PRs, so I'll compare and pingback. In the future, I would reply from https://github.com/ciphx, as this profile will be deactivated tomorrow.

**Comment by guyjerby** [comment]
Thanks @ciphx - so we are also handling some benchmarks for our customers (Aqua security) , for each benchmark that we should work on - I am creating a github issue, so we can use that for tracking, currently I am testing the PR from @ttousai and adding comments, thanks for your assistance, not sure what are the differences, but it seems that we have 2 PR's for the same use.

**Comment by afdesk** [comment]
closed #1672
