### ISSUE TITLE
CIS 1.9 Kubernetes Check 1.1.13 returns an error when ran from a job pod

### ISSUE THREAD

**Issue by Shashankft9** [aquasecurity/kube-bench#1666]
**Overview**

```
{
              "AuditConfig": "",
              "AuditEnv": "",
              "IsMultiple": true,
              "actual_value": "",
              "audit": "for adminconf in /etc/kubernetes/{admin.conf,super-admin.conf}; do if test -e $adminconf; then stat -c \\\"permissions=%a %n\\\" $adminconf; fi; done\n",
              "expected_result": "'permissions' is present",
              "remediation": "Run the below command (based on the file location on your system) on the control plane node.\nFor example, chmod 600 /etc/kubernetes/admin.conf\nOn Kubernetes 1.29+ the super-admin.conf file should also be modified, if present.\nFor example, chmod 600 /etc/kubernetes/super-admin.conf\n",
              "scored": true,
              "status": "FAIL",
              "test_desc": "Ensure that the default administrative credential file permissions are set to 600 (Automated)",
              "test_info": [
                "Run the below command (based on the file location on your system) on the control plane node.\nFor example, chmod 600 /etc/kubernetes/admin.conf\nOn Kubernetes 1.29+ the super-admin.conf file should also be modified, if present.\nFor example, chmod 600 /etc/kubernetes/super-admin.conf\n"
              ],
              "test_number": "1.1.13",
              "type": ""
            }
```
here the `audit` command fails to run both inside the kube-bench job pod or even outside in bash.

**How did you run kube-bench?**

I'm running kube-bench inside a pod using the `job.yaml`

**What happened?**
```
root@iksu27-3007-1-l7rfk:~# for adminconf in /etc/kubernetes/{admin.conf,super-admin.conf}; do if test -e $adminconf; then stat -c \"permissions=%a %n\" $adminconf; fi; done
stat: cannot statx '%n"': No such file or directory
"permissions=600
```
I suspect that because of the error, in the json pasted in overview, the `actual_value` is empty string. 
Possible fix - removing the trailing slash in cis 1.9 [here](https://github.com/aquasecurity/kube-bench/blob/main/cfg/cis-1.9/master.yaml#L192) in comparison to cis 1.8 [here](https://github.com/aquasecurity/kube-bench/blob/main/cfg/cis-1.8/master.yaml#L191). Is there some reason the slashes were added?

**What did you expect to happen:**

I expected the test to pass, because the permission is already set to `600`.

**Environment** 

kube-bench version: v1.8.0
kubectl version: v1.27.15

**Comment by andypitcher** [comment]
@Shashankft9 same as the other issue, linking to #1668. The linked PR is ready to merged.

**Comment by andypitcher** [comment]
@mozillazg IMO This issue can be close, since https://github.com/aquasecurity/kube-bench/pull/1649 has been merged.
