### ISSUE TITLE
ARGs aren't set when running DOCKERFILE

### ISSUE THREAD

**Issue by AndrewWSHenry** [aquasecurity/kube-bench#1684]
### Discussed in https://github.com/aquasecurity/kube-bench/discussions/1683

<div type='discussions-op-text'>

<sup>Originally posted by **AndrewWSHenry** September 18, 2024</sup>
hi,

I have not been able to build the kube-bench container using the instructions for "Running CIS benchmark in an EKS cluster" [https://github.com/aquasecurity/kube-bench/blob/main/docs/running.md#running-cis-benchmark-in-an-eks-cluster](url). I have run the docker build command on Ubuntu 24.04 and OpenSUSE LEAP 15.6 and run into the same problem of the KUBECTL_VERSION ARG not being set/available. causing the wget to error.

The instructions don't mention a need to set those values and a brief look seems to suggest that the makefile run by the dockerfile should be setting those values. Just wondering if anyone is aware of a reason why the KUBECTL_VERSION arg has no value? 

This is the relevant output.

> Dockerfile:14
> --------------------
>   12 |     # Add kubectl to run policies checks
>   13 |     ARG KUBECTL_VERSION TARGETARCH
>   14 | >>> RUN wget -O /usr/local/bin/kubectl "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl"
>   15 |     RUN wget -O kubectl.sha256 "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl.sha256"
>   16 |     # Verify kubectl sha256sum
> --------------------
> ERROR: failed to solve: process "/bin/sh -c wget -O /usr/local/bin/kubectl \"https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl\"" did not complete successfully: exit code: 8</div>

**Comment by mozillazg** [comment]
@AndrewWSHenry Thanks for reporting. We should add a default value for the KUBECTL_VERSION arg in the Dockerfile.
Feel free to send a pull request for this. Thanks!

**Comment by afdesk** [comment]
#1648 should fix this issue. 
@AndrewWSHenry could you confirm that It's OK for you? thanks!

**Comment by afdesk** [comment]
closed in favor of #1648 and was confirmed https://github.com/aquasecurity/kube-bench/discussions/1683#discussioncomment-10894251

please feel free to reopen this issue if it appears again. 

thanks!
