### ISSUE TITLE
1.1.37 should also check that --audit-policy-file is set

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#177]
See discussion in PR #173

**Comment by ttousai** [comment]
@lizrice

To resolve this issue, I think kube-bench needs to support sub-checks under checks and combining the results of each sub-check with operators like `and` or `or`.

For example, we could have check 1.1.37a and 1.1.37b then combine them with the comparison operators (for example and/or) to get the result for 1.1.37.
wdyt?
WDYT?

**Comment by simar7** [comment]
This has been fixed here: https://github.com/aquasecurity/kube-bench/pull/440
