### ISSUE TITLE
Add Rancher 2.x support

### ISSUE THREAD

**Issue by panho66** [aquasecurity/kube-bench#179]
Does this tools support Kubernete installed by Rancher Rke ? 
https://github.com/rancher/rke

**Run with command line:**
docker run --pid=host -v /usr/local/bin/kubectl:/usr/bin/kubectl -t aquasec/kube-bench:latest master --version 1.11

**Result:**
[WARN] Unable to get kubectl version, using default version: 1.6
[INFO] 1 Master Node Security Configuration
[INFO] 1.1 API Server
[FAIL] 1.1.1 Ensure that the **--anonymous-auth argument is set to false** (Scored)

**Actually:**
root      6112  6094  2 Nov01 ?        07:57:12 kubelet --address=0.0.0.0 --network-plugin=cni --cni-bin-dir=/opt/cni/bin --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --root-dir=/var/lib/kubelet --v=2 --enforce-node-allocatable= --volume-plugin-dir=/var/lib/kubelet/volumeplugins --cluster-domain=cluster.local --cluster-dns=10.43.0.10 --cloud-provider= --cgroups-per-qos=True --cni-conf-dir=/etc/cni/net.d **--anonymous-auth=false**

**Kubelet in container hyperkube:v1.11.3-rancher1**
f144e08bb3aa        **rancher/hyperkube:v1.11.3-rancher1**                                                                                        "/opt/rke-tools/en..."   2 weeks ago         Up 2 weeks                              kubelet

1.1.1 Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml
on the master node and set the below parameter.
--anonymous-auth=false

**There is no file in /etc/kubernetes/**
[dockeradm@rancher2-lab2-1 ~]$ ls -arlt /etc/kubernetes/
total 20K
drwxr-xr-x    4 root root   29 Oct 25 12:33 ./
drwxr-xr-x. 100 root root 8.0K Oct 25 12:37 ../
drwxr-xr-x    3 root root 4.0K Oct 25 14:29 ssl/
drwxr-xr-x    2 root root 4.0K Nov  7 11:32 .tmp/

**Comment by ttousai** [comment]
@panho66 kube-bench implements the CIS Kubernetes benchmarks which is mostly based on a kubeadm installed cluster.

For clusters deployed via other methods or platforms like Rancher, kube-bench will report a few false negatives because of different executable names or different file locations.

Some file locations can be fixed by overriding file paths and executable names in `cfg/config.yaml`.

**Comment by panho66** [comment]
@lizrice  The output of ps -eaf | grep apiserver

root      2971  2953  5 Nov19 ?        02:46:16 kube-apiserver --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem --enable-admission-plugins=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --insecure-port=0 --cloud-provider= --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem --requestheader-group-headers=X-Remote-Group --etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem --bind-address=0.0.0.0 --storage-backend=etcd3 --etcd-servers=https://rancher2-restores-test-1.auiag.corp:2379,https://rancher2-restores-test-2.auiag.corp:2379,https://rancher2-restores-test-3.auiag.corp:2379 --requestheader-client-ca-file=/etc/kubernetes/ssl/kube-apiserver-requestheader-ca.pem --service-node-port-range=30000-32767 --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --secure-port=6443 --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --proxy-client-key-file=/etc/kubernetes/ssl/kube-apiserver-proxy-client-key.pem --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --proxy-client-cert-file=/etc/kubernetes/ssl/kube-apiserver-proxy-client.pem --insecure-bind-address=127.0.0.1 --allow-privileged=true --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --etcd-prefix=/registry --requestheader-allowed-names=kube-apiserver-proxy-client --requestheader-extra-headers-prefix=X-Remote-Extra- --service-cluster-ip-range=10.43.0.0/16 --requestheader-username-headers=X-Remote-User --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --authorization-mode=Node,RBAC
root      3167  3150  0 Nov19 ?        00:01:07 kube-controller-manager --allow-untagged-cloud=true --leader-elect=true --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --service-cluster-ip-range=10.43.0.0/16 --enable-hostpath-provisioner=false --v=2 --allocate-node-cidrs=true --service-account-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --address=0.0.0.0 --cloud-provider= --cluster-cidr=10.42.0.0/16 --configure-cloud-routes=false --node-monitor-grace-period=40s --pod-eviction-timeout=5m0s --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --use-service-account-credentials=true
dockera+ 28090 26863  0 10:23 pts/0    00:00:00 grep --color=auto apiserver

which configuration file application looking for ?

Here is all I got
[dockeradm@rancher2-restores-test-1 ~]$ ls -asrlt /etc/kubernetes/*
total 116K
   0 drwxr-xr-x 4 root root   29 Nov 19 11:59 ../
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-apiserver-key.pem
4.0K -rw-r--r-- 1 root root 1.1K Nov 19 11:59 kube-apiserver-requestheader-ca.pem
4.0K -rw-r--r-- 1 root root 1.1K Nov 19 11:59 kube-node.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-scheduler-key.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-ca-key.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-etcd-rancher2-restores-test-3-auiag-corp-key.pem
4.0K -rw-r--r-- 1 root root 1017 Nov 19 11:59 kube-ca.pem
4.0K -rw-r--r-- 1 root root 1.5K Nov 19 11:59 kube-etcd-rancher2-restores-test-1-auiag-corp.pem
4.0K -rw-r--r-- 1 root root 1.1K Nov 19 11:59 kube-proxy.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-node-key.pem
4.0K -rw-r--r-- 1 root root 1.1K Nov 19 11:59 kube-apiserver-proxy-client.pem
4.0K -rw-r--r-- 1 root root 1.1K Nov 19 11:59 kube-scheduler.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-apiserver-proxy-client-key.pem
4.0K -rw-r--r-- 1 root root 1.5K Nov 19 11:59 kube-etcd-rancher2-restores-test-2-auiag-corp.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-apiserver-requestheader-ca-key.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-etcd-rancher2-restores-test-1-auiag-corp-key.pem
4.0K -rw-r--r-- 1 root root 1.5K Nov 19 11:59 kube-apiserver.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-proxy-key.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-controller-manager-key.pem
4.0K -rw-r--r-- 1 root root 1.1K Nov 19 11:59 kube-controller-manager.pem
4.0K -rw-r--r-- 1 root root 1.7K Nov 19 11:59 kube-etcd-rancher2-restores-test-2-auiag-corp-key.pem
4.0K -rw-r--r-- 1 root root 1.5K Nov 19 11:59 kube-etcd-rancher2-restores-test-3-auiag-corp.pem
4.0K -rw-r--r-- 1 root root  517 Nov 19 11:59 kubecfg-kube-apiserver-proxy-client.yaml
4.0K -rw-r--r-- 1 root root  465 Nov 19 11:59 kubecfg-kube-scheduler.yaml
4.0K -rw-r--r-- 1 root root  445 Nov 19 11:59 kubecfg-kube-node.yaml
4.0K -rw-r--r-- 1 root root  533 Nov 19 11:59 kubecfg-kube-apiserver-requestheader-ca.yaml
4.0K -rw-r--r-- 1 root root  449 Nov 19 11:59 kubecfg-kube-proxy.yaml
4.0K -rw-r--r-- 1 root root  501 Nov 19 11:59 kubecfg-kube-controller-manager.yaml
4.0K drwxr-xr-x 3 root root 4.0K Nov 19 13:43 ./
   0 drwxr-xr-x 2 root root   22 Nov 19 13:43 certs/

**Comment by lizrice** [comment]
The `ps` output shows us that the kube-apiserver is running with the default setting of --anonymous-auth. For test 1.1.1 to pass, you would need to explicitly set --anonyous-auth=false in the kube-apiserver settings. 

From https://github.com/rancher/rancher/issues/12184 and the issue comment it refers to, https://github.com/rancher/rancher/issues/12111#issuecomment-425061897, it looks as though you can do this by specifying the field in the Rancher UI. 

(That said, many people do choose to ignore this CIS recommendation, provided they are using RBAC, because anonymous access allows for anonymous health checks, and the default RBAC settings prevent the anonymous user doing anything untoward . This recommendation 1.1.1 has been modified accordingly in the latest version of the CIS Kubernetes benchmark.)
