### ISSUE TITLE
Kube-bench on every nodes in a cluster

### ISSUE THREAD

**Issue by nishitm** [aquasecurity/kube-bench#184]
Is there any way to deploy kube-bench on every possible node (master/worker) in a cluster. Right now, I have a setup of 1 master node and 4 worker node spread across 4 namespaces. If I am trying to deploy it both instance master and worker inside every `namespace`, I can see it got deployed only on the 2 nodes out of 5, 1 master and 1 worker node.

I wanted to know the reason for this, also will it be the same result for every node if i forcefully deploy it on every nodes?

Thanks in advance

**Comment by lizrice** [comment]
You probably want all your nodes to be configured the same way, but you can use kube-bench to check that is the case by running on all the nodes. 

The ideal way to do this would be some sort of hybrid between a DaemonSet (which runs a pod on every node) and a Job (which runs a pod to completion), though I don't believe that exists at the moment. 

One way to solve this would be to have a DaemonSet that runs a pod which runs continually, but is mostly sleeping, just waking up on a regular basis to run kube-bench.  

Another option would be to ensure it's deployed on every node by having some kind of unique label for each node and running a job for each with an appropriate nodeSelector.

**Comment by jnummelin** [comment]
Haven't tried, yet, but I _think_  a `DaemonSet` with a `restartPolicy: Never` would do the trick too. It's no way perfect, but AFAIK gets closest to whats needed.

**Comment by nishitm** [comment]
Thanks for the help :)
Closing the issue
