### ISSUE TITLE
Update tests to match the new release of the CIS Benchmark

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#19]
New version [v1.1.0](https://workbench.cisecurity.org/files/1738) has been released with the following changes. We need to modify the test config files to match. 

**New Recommendations**

1.1.32 Ensure that the --authorization-mode argument is set to Node

1.1.33 Ensure that the admission control policy is set to NodeRestriction

1.1.34 Ensure that the --experimental-encryption-provider-config argument is set as appropriate

1.1.35 Ensure that the encryption provider is set to aescbc

1.3.7 Ensure that the RotateKubeletServerCertificate argument is set to true

1.6.8 Configure Network policies as appropriate

2.1.14 Ensure that the RotateKubeletClientCertificate argument is set to true

2.1.15 Ensure that the RotateKubeletServerCertificate argument is set to true

2.2.7 Ensure that the certificate authorities file permissions are set to 644 or more restrictive

2.2.8 Ensure that the client certificate authorities file ownership is set to root:root

**Deleted Recommendations**

1.3.3 Ensure that the --insecure-experimental-approve-all-kubelet-csrs-for-group argument is not set

1.6.5 Avoid using Kubernetes Secrets

**Comment by ttousai** [comment]
I have sent a PR for this issue. Some observations. I think we should provide a way to notify users of "manual" checks.

These will be checks that are hard to run automatically, like 1.1.35 and the entirety of 1.6 (which we silently  ignore).

As it stands now we ignore all manual checks and do not inform our users of the skipped checks, losing the benefit of the benchmarks for those checks.

Any thoughts?

**Comment by lizrice** [comment]
I agree. We could have a test config type that is something like "manual", which always generates a [WARN], and outputs the remediation text (as part of the output of all the remediations) to explain what the user should do manually. Sound OK?

**Comment by ttousai** [comment]
Yeah, sounds good!

**Comment by ttousai** [comment]
I am creating an issue for manual test config type.

**Comment by ttousai** [comment]
I just updated the PR for this issue.
