### ISSUE TITLE
Take advantage of dynamic kubelet config

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#196]
I don't think this is in common usage yet, but eventually we will be able to query kubelet config dynamically as described [here](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/). We should look for this capability and use it where possible.

**Comment by lizrice** [comment]
This will require using the kubernetes API to query Node.Spec.Status.Config for the node being tested. I wonder if this would report the right information regardless of whether the node is configured by run-time parameters, JSON config file, or ConfigMap?

**Comment by tengqm** [comment]
Looks like this feature can be closed because dynamic kubelet config is deprecated in Kubernetes.
