### ISSUE TITLE
Unable to see anything in kube bench job

### ISSUE THREAD

**Issue by Allesgluck** [aquasecurity/kube-bench#207]
Kube-bench job pods :
-bash-4.2$ kubectl get pods|grep -i kube-bench
kube-bench-master-478f9                           0/1       Error       0          1h
kube-bench-master-6czr9                           0/1       Error       0          1h
kube-bench-master-6glhn                           0/1       Error       0          1h
kube-bench-master-92tjg                           0/1       Error       0          1h
kube-bench-master-fqxhg                           0/1       Error       0          1h
kube-bench-master-r4qxt                           0/1       Error       0          1h
kube-bench-master-xctkg                           0/1       Error       0          1h

-bash-4.2$ kubectl logs kube-bench-master-xctkg

Version check failed: need kubectl or kubelet binaries to get kubernetes version
Alternatively, you can specify the version with --version

**Comment by Allesgluck** [comment]
@lizrice Tx for responding. Still not clear, where to mention these. 
What i did so far is, as yaml mount /usr/bin,  i symlinked it to right path of kubectl and kubelete..and even though exported varaible for correct path but no luck...Please help

**Comment by RealArtemiy** [comment]
As fast fix, you can run with next parameters, as for 1.11 version
```
        image: aquasec/kube-bench:latest
        command: ["kube-bench","node", "--version", "1.11"]
```

**Comment by lizrice** [comment]
@Allesgluck did specifying the --version as @RealArtemiy suggested work for you?

**Comment by chandtailor** [comment]
Having the same issue, did specifying the version number solve the problem for you? Doesn't seem to make a difference for me

**Comment by Allesgluck** [comment]
Tx @lizrice. It worked. So nice of u for giving such a gr8 support.

**Comment by devops2201** [comment]
@lizrice Any plans to add config for 1.14.x?

**Comment by lizrice** [comment]
We follow the CIS benchmark and there is no benchmark for 1.14. The CIS community is currently working on a benchmark for 1.15. There was also an updated spec for 1.14 (CIS benchmark 1.4.1) and we are working on the changes for that.

**Comment by lordcf** [comment]
@RealArtemiy I am facing the same with with kube-bench 
Your solution of adding version in command works for node but nor for master .
can you suggest anything specif for master node.

kube-bench-master-l4gvj   0/1     Pending   0          11m
