### ISSUE TITLE
need apiserver executable but none of the candidates are running

### ISSUE THREAD

**Issue by Allesgluck** [aquasecurity/kube-bench#210]
Hi,

In our k8s cluster, we are running apiserver as pod, can u help how to help master.yaml to detect $apiserverbin

[root@master2 1.8]# ps -elf|grep -i api
4 S root      1501  1482  3  80   0 - 182420 futex_ Jan02 ?       20:12:59 kube-apiserver --allow-privileged=true --apiserver-count=3 --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --endpoint-reconciler-type=lease --insecure-port=0 --kubelet-preferred-address-types=InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP --runtime-config=admissionregistration.k8s.io/v1alpha1 --service-node-port-range=30000-32767 --storage-backend=etcd3 --advertise-address=172.25.19.21 --client-ca-file=/etc/kubernetes/ssl/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/ssl/etcd/ssl/ca.pem --etcd-certfile=/etc/ssl/etcd/ssl/node-master2.pem --etcd-keyfile=/etc/ssl/etcd/ssl/node-master2-key.pem --etcd-servers=https://172.25.19.18:2379,https://172.25.19.29:2379,https://172.25.19.35:2379,https://172.25.19.30:2379,https://172.25.19.25:2379 --kubelet-client-certificate=/etc/kubernetes/ssl/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/ssl/apiserver-kubelet-client.key --proxy-client-cert-file=/etc/kubernetes/ssl/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/ssl/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/ssl/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/ssl/sa.pub --service-cluster-ip-range=10.233.0.0/18 --tls-cert-file=/etc/kubernetes/ssl/apiserver.crt --tls-private-key-file=/etc/kubernetes/ssl/apiserver.key --oidc-issuer-url=https://jc-pd-keycloak.node.jiocloud.prod.internal:8443/auth/realms/k8s --oidc-groups-claim=groups --oidc-client-id=kubernetes-cluster --oidc-ca-file=/etc/kubernetes/ssl/keycloak-2.crt
0 S root      3763 29765  0  80   0 - 28177 pipe_w 12:58 pts/0    00:00:00 grep --color=auto -i api

**Comment by ttousai** [comment]
Hello @Allesgluck can you please share the output of running kube-bench with `-v2` in your cluster?

**Comment by Allesgluck** [comment]
@ttousai I m running K8s cluster with k8s components like apiserver, scheduler,controller as pod. And now running kube bench as job pod.. Now can u help me, what to do as kube-bench is installed as pod ? and where to run above -v2 command with kube-bench

**Comment by ttousai** [comment]
@Allesgluck there 2 approaches:
1. run a new master job with the command field set to `command: ["kube-bench", "master", "-v2"]` like in this gist https://gist.github.com/ttousai/4ec3c856770c474a3ec9fd10bafc49d1.

2. Edit your currently configured job spec command field and setting it to `["kube-bench", "master", "-v2"]`.

**Comment by jaredallard** [comment]
@ttousai In my case, this is caused by ps not being present on CoreOS

**Comment by lizrice** [comment]
> In my case, this is caused by ps not being present on CoreOS

@jaredallard were you running kube-bench in a pod or directly on the host? If it's a containerized version of kube-bench, I would expect it to pick up `ps` from `/bin/ps` in the container

**Comment by marccarre** [comment]
Same happening here, having:
```console
[root@node0 ~]# ps -elf | grep apiserver | grep -v grep
4 S root      1098  1076  6  80   0 - 112040 -     04:10 ?        00:19:56 kube-apiserver --authorization-mode=Node,RBAC --advertise-address=172.17.0.2 --allow-privileged=true --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key

[root@node0 ~]# which ps
/usr/bin/ps
```
Using `-v2`, the logs say:
```console
$ kubectl logs kube-bench-master-hb648
I0322 09:06:44.471230   47108 util.go:118] Looking for config for version 1.13
I0322 09:06:44.473729   47108 util.go:123] Looking for config file: cfg/1.13/master.yaml
I0322 09:06:44.474167   47108 common.go:65] Using benchmark file: cfg/1.13/master.yaml
I0322 09:06:44.475275   47108 common.go:77] Using config file: cfg/1.13/config.yaml
I0322 09:06:44.477659   47108 util.go:43] [ps -C kube-apiserver -o cmd --no-headers]: fork/exec /usr/bin/ps: no such file or directory
I0322 09:06:44.477788   47108 util.go:301] executable 'kube-apiserver' not running
I0322 09:06:44.481088   47108 util.go:43] [ps -C hyperkube -o cmd --no-headers]: fork/exec /usr/bin/ps: no such file or directory
I0322 09:06:44.481183   47108 util.go:301] executable 'hyperkube apiserver' not running
I0322 09:06:44.510365   47108 util.go:43] [ps -C hyperkube -o cmd --no-headers]: fork/exec /usr/bin/ps: no such file or directory
I0322 09:06:44.510557   47108 util.go:301] executable 'hyperkube kube-apiserver' not running
I0322 09:06:44.515422   47108 util.go:43] [ps -C apiserver -o cmd --no-headers]: fork/exec /usr/bin/ps: no such file or directory
I0322 09:06:44.515825   47108 util.go:301] executable 'apiserver' not running

need apiserver executable but none of the candidates are running
```
Is there any additional info I could provide to help on this?

**Comment by pms1969** [comment]
On CoreOS if you don't mount the /usr/bin directory, and set the version manually, you no longer get the missing `ps` problem.
