### ISSUE TITLE
Handle errors from tests where executable not running

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#22]
Some tests can generate errors:
```
failed to run: ps -ef | grep etcd | grep -v grep | grep -o data-dir=.* | cut -d= -f2 | xargs stat -c %a
failed command:[grep -o data-dir=.*], error: exit status 1
failed to run: ps -ef | grep etcd | grep -v grep | grep -o data-dir=.* | cut -d= -f2 | xargs stat -c %a
failed command:[xargs stat -c %a], error: exit status 123
```
We should be able to figure out what these errors mean for the test status, and give a better [WARN] or [FAIL] message as appropriate. For example, I guess these both happen if etcd isn't running? If that's the case, we should say so in a [WARN] and only show the detail seen above if the --verbose flag is on.

See more context for this in #7

**Comment by lizrice** [comment]
@ttousai do you think this is still an issue? I'm thinking of closing this one as stale

**Comment by ttousai** [comment]
@lizrice you can close it as stale.
