### ISSUE TITLE
Setup of Kube-bench for OpenShift

### ISSUE THREAD

**Issue by PEDaaS** [aquasecurity/kube-bench#223]
From document, i have tried to setup kube-bench on master node of openshift and can run on one of the master node. Now in order to run on other master and worker nodes, do i need to do same setup and it only executes locally?
I was wondering if from one node, i can trigger scan of another node.

**Comment by lizrice** [comment]
kube-bench needs to be scheduled on every node that you want to test, because it needs to be able to examine processes and files on the node directly (which requires sharing the host namespace and mounting some directories from the host - see job-master.yaml and job-node.yaml). See also #225

**Comment by lizrice** [comment]
[OpenShift is now supported](https://github.com/aquasecurity/kube-bench#running-on-openshift) through the ocp-3.10 config directory
