### ISSUE TITLE
helm-chart for kube-bench

### ISSUE THREAD

**Issue by davidkarlsen** [aquasecurity/kube-bench#225]
It would be nice to have a helm-chart for running kube-bench regularly through CronJobs in a cluster - similar to https://github.com/helm/charts/tree/master/stable/kube-hunter.

**Comment by lizrice** [comment]
It would. The main difference is that kube-hunter only needs to run in one location, whereas kube-bench needs to be scheduled onto every node where the tests are going to be run. We typically do that with a DaemonSet, but then that only runs once. What we need is some sort of CronJob / DaemonSet combo which would run on all nodes, on a regular basis...

**Comment by davidkarlsen** [comment]
Linking some issues https://github.com/kubernetes/kubernetes/issues/36601 https://etoews.github.io/blog/2017/05/13/run-once-daemonset-on-kubernetes/

**Comment by lizrice** [comment]
With https://github.com/kubernetes/kubernetes/issues/36601 being closed, I guess we are unlikely to see native support for running jobs on each node regularly. So I guess the way we can work around this is with a DaemonSet that runs a containerized regular job to run kube-bench. 

This will be easier with #72 as we wouldn't have to worry about what kind of node the job is running on.

**Comment by lizrice** [comment]
Thanks to #72 we can run kube-bench on any node and it will automatically detect whether to run the master or node tests. 

We could extend the [entrypoint script](https://github.com/aquasecurity/kube-bench/blob/master/entrypoint.sh) to add a new command (say, `repeat`) that calls kube-bench every day. 

And then a DaemonSet could easily install this on every node.

**Comment by lizrice** [comment]
After much debate we've reached the conclusion that this isn't something we want to support within the kube-bench project, without the underlying support of a native Kubernetes DaemonSet / CronJob combination. It's possible to do without that support, but it doesn't feel like a clean solution and we are concerned about maintaining it going forward.

**Comment by subodhp** [comment]
Hi @lizrice - How do you suggest one should run the kube-bench in periodic manner in current state in k8s cluster?

Thanks,
Subodh

**Comment by mirtov-alexey** [comment]
@lizrice 
Hello!
Do I understand correctly that this problem can be partially solved through the starboard?
will it launch kube-bench when a new node joins a node?
but it will not run repeated checks again on the already connected node in case someone just logs in and changes the config file? https://blog.aquasec.com/automate-kubernetes-compliance
does starboard not have this feature?

What are the other alternatives to running kube-bench on a periodic basis?

**Comment by max-rocket-internet** [comment]
FYI there is a Helm chart here: https://github.com/deliveryhero/helm-charts/tree/master/stable/kube-bench
