### ISSUE TITLE
EKS worker node - misleading --allow-privileged FAIL

### ISSUE THREAD

**Issue by Constantin07** [aquasecurity/kube-bench#229]
If the `--allow-privileged` is deprecated but required for kubelet (according to https://github.com/awslabs/amazon-eks-ami/commit/9ad6e2abca3d6f8f87b72534e8d0270e895b2e1b) why kube-bench still reports it as a fail  on EKS node ?

More info: https://github.com/awslabs/amazon-eks-ami/blob/9f2000223d4f081d24419c5af7dd058c4117c945/files/kubelet.service#L11

```
[INFO] 2.1 Kubelet
[FAIL] 2.1.1 Ensure that the --allow-privileged argument is set to false (Scored)
```

**Comment by lizrice** [comment]
The --allow-privileged check was retired in version 1.4.0 of the CIS Kubernetes Benchmark, so it will be retired when we add the updated version of the test files in #226

**Comment by Constantin07** [comment]
Thanks @lizrice for explanation.
