### ISSUE TITLE
Add config settings for OpenShift

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#23]
Openshift uses different binaries and config file locations, and I'm opening this issue to gauge interest in adding Openshift config to kube-bench. 

OpenShift has its own approach to security, and doesn't directly expose a lot of the config arguments of kube-bench making a lot of the CIS Benchmark tests seem mostly irrelevant. 

However, "all kubelet settings that have corresponding command-line flags can already be set using the [kubeletArguments](https://github.com/openshift/origin/blob/f59053a0a62249190a721ab6a67d45986d80f596/pkg/cmd/server/api/v1/types.go#L49-L52) map in the node config file, with the caveat that it can result in insecure, untested, and/or invalid configurations". 

It would also be possible to at least check for things like file permissions.  

- Config files live in `/etc/origin/master` and `/etc/origin/node` directories (for master & node respectively)
- Executables are `openshift start node` and `openshift start master`

**Comment by lizrice** [comment]
There is new [a plan to document how the CIS benchmarks would need to be adapted to apply to OpenShift](https://trello.com/c/rXm68iBd/202-review-and-document-openshift-specifics-for-cis-kubernetes-benchmarks) - once that's in place we can create kube-bench tests to match.

**Comment by kawai888** [comment]
cool, looking forward to using it for our openshift post deployment check

**Comment by lizrice** [comment]
Work is actively in progress on making the OpenShift checks now

**Comment by lizrice** [comment]
work in progress under #212

**Comment by agvikashsagar** [comment]
It will be helpful one

**Comment by lizrice** [comment]
The config files are there now so you should be able to give this a try by specifying `--version ocp-3.10`

**Comment by PEDaaS** [comment]
Can you please help me with full command to execute ocp checks?

**Comment by ttousai** [comment]
@PEDaaS on your k8s cluster master run:
```
docker run --rm -v `pwd`:/host aquasec/kube-bench:latest install
./kube-bench master --version ocp-3.10
```
