### ISSUE TITLE
kube-bench w/ kubespray

### ISSUE THREAD

**Issue by christoph-puppe** [aquasecurity/kube-bench#231]
Hi

I'm trying to run the benchmark on a cluster created with kubespray. 

First error is the version thing. Fixed that with --version 1.11 (it's 1.13 but there is no config for that in kube-bench).

Now I get the logfile:

need apiserver executable but none of the candidates are running

I've run it successfully on a cluster generated with kubeadm, a 1.13.

**Comment by lizrice** [comment]
The 1.13 config is in progress right now (see #226). However, kube-bench is supposed to pick up the version automatically if --version isn't specified, by looking at the version returned by kubectl or kubelet if possible (which requires at least one of those to be on the path). 

@christoph-puppe did you run kube-bench as an executable running directly on the host, or as a container or k8s pod? 

As it's not finding the API server executable, I wonder if you're running as a container but without the host PID mapped? See https://github.com/aquasecurity/kube-bench#running-inside-a-container.

**Comment by christoph-puppe** [comment]
@lizrice thanks for the reply! I only have k8s-api access  to the cluster. So it was done with the master.yaml.

**Comment by christoph-puppe** [comment]
got root on the master and used the docker based receipe, that worked and I got the results.
