### ISSUE TITLE
GKE?

### ISSUE THREAD

**Issue by christoph-puppe** [aquasecurity/kube-bench#232]
Hi

are there plans to enable the job.master.yaml on GKE? I didn't find a way to do it, maybe you have an idea :)

**Comment by leodotcloud** [comment]
One thing for sure, you do not have access to the Master Nodes of a GKE cluster. So, only support for "node" is needed.

**Comment by lizrice** [comment]
We’d be interested in feedback from anyone who has run the node tests on GKE - does the 1.11-json config file work OK there?

**Comment by lizrice** [comment]
I think #300 means we can close this
