### ISSUE TITLE
Cipher suites warning after I set the specific ciphers

### ISSUE THREAD

**Issue by horis233** [aquasecurity/kube-bench#243]
I got the warning message after I used the cipher suites provided by the remediation messages.
Command`ps -ef |  grep -v grep | grep tls-cipher-suites`

```root      3267  3248 17 15:16 ?        00:01:06 /hyperkube apiserver --secure-port=8001 --bind-address=0.0.0.0 --advertise-address=9.21.58.173 --endpoint-reconciler-type=lease --insecure-port=0 --anonymous-auth=false --etcd-servers=https://9.21.58.173:4001 --etcd-cafile=/etc/cfc/conf/etcd/ca.pem --etcd-certfile=/etc/cfc/conf/etcd/client.pem --etcd-keyfile=/etc/cfc/conf/etcd/client-key.pem --runtime-config=batch/v2alpha1,extensions/v1beta1=true,extensions/v1beta1/podsecuritypolicy=true,admissionregistration.k8s.io/v1alpha1 --enable-admission-plugins=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,PodSecurityPolicy,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,Priority,EventRateLimit,PodNodeSelector,PodTolerationRestriction,NodeRestriction,ResourceQuota --admission-control-config-file=/etc/cfc/conf/admission-control-config.yaml --repair-malformed-updates=false --oidc-issuer-url=https://mycluster.icp:9443/oidc/endpoint/OP --oidc-client-id=385ac67a478609e8614ecf377143975f --oidc-ca-file=/etc/cfc/conf/ca.crt --oidc-groups-claim=teamRoleMappings --tls-cert-file=/etc/cfc/conf/server.cert --tls-private-key-file=/etc/cfc/conf/server.key --kubelet-client-certificate=/etc/cfc/conf/kubelet-client.crt --kubelet-client-key=/etc/cfc/conf/kubelet-client.key --client-ca-file=/etc/cfc/conf/ca.crt --service-account-key-file=/etc/cfc/conf/k8s-service-account.key --authorization-mode=Node,RBAC --min-request-timeout=300 --allow-privileged --requestheader-client-ca-file=/etc/cfc/conf/front/front-proxy-ca.pem --requestheader-username-headers=X-Remote-User --requestheader-group-headers=X-Remote-Group --requestheader-allowed-names=mycluster.icp,aggregator --requestheader-extra-headers-prefix=X-Remote-Extra- --proxy-client-cert-file=/etc/cfc/conf/front/front-proxy-client.pem --proxy-client-key-file=/etc/cfc/conf/front/front-proxy-client-key.pem --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256 --enable-bootstrap-token-auth --v=2 --profiling=false --service-cluster-ip-range=10.0.0.0/16```

```root     32225     1  6 14:59 ?        00:01:31 /opt/kubernetes/hyperkube kubelet --bootstrap-kubeconfig=/etc/cfc/kubelet/kubelet-bootstrap-config --kubeconfig=/etc/cfc/kubelet/kubelet-config --cert-dir=/etc/cfc/kubelet --config=/etc/cfc/kubelet/kubelet-service-config --dynamic-config-dir=/etc/cfc/kubelet/kubelet-dynamic-config --network-plugin=cni --address=0.0.0.0 --hostname-override=9.21.58.173 --node-ip=9.21.58.173 --pod-infra-container-image=hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/pause:3.1 --housekeeping-interval=15s --node-labels=role=master,master=true,node-role.kubernetes.io/master=true,proxy=true,node-role.kubernetes.io/proxy=true,etcd=true,node-role.kubernetes.io/etcd=true, --register-with-taints=dedicated=infra:NoSchedule --keep-terminated-pod-volumes=false --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256```

But I still got the warning message:
`[WARN] 1.1.30 Ensure that the API Server only makes use of Strong Cryptographic Ciphers (Not Scored)`
`[WARN] 2.1.14 Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers (Not Scored)`

**Comment by cjschaef** [comment]
It looks like the bug is for tests that are not scored `scored: false`, as the check whether they pass or fail is not recognized, and you get a warning either way. Not sure if this is by design, but I would hope that following the remediation action to fix the warning would cause the test to pass next time, not continue to warn like this issue mentions.

I have changed `1.1.30` and `1.5.7` to be **scored**, with the proper changes, and they now pass without a `WARN` message or included the `WARN` count results.

**Comment by lizrice** [comment]
Should be fixed by #402 so I'm not sure why this issue didn't get closed
