### ISSUE TITLE
cadvisor-port in kubernetes 1.13

### ISSUE THREAD

**Issue by veeshall** [aquasecurity/kube-bench#252]
Is this still valid? https://github.com/aquasecurity/kube-bench/blob/54502c5f755bf054f9a65bc957a77321433a9f77/cfg/1.13/node.yaml#L222

cadvisor-port is no longer a flag in Kubernetes 1.13
https://v1-13.docs.kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by ttousai** [comment]
@veeshall thanks for pointing this out. 

However kube-bench tries to match the CIS Kubernetes benchmark as closely as possible. The CIS Kubernetes benchmark v1.4.0 checks this value so kube-bench also does.

**Comment by lizrice** [comment]
I have raised a [ticket](https://workbench.cisecurity.org/sections/45008/recommendations/120844) against the CIS spec.
