### ISSUE TITLE
kube-bench master job fails to run when targeting EKS nodes

### ISSUE THREAD

**Issue by teamhanded** [aquasecurity/kube-bench#253]
For some reason I can't reach the EKS API server. Upon searching this repo, I did try running this from both my workstation and an EC2 instance

```
 kubectl run --rm -i -t kube-bench-node-test --image=aquasec/kube-bench:latest --restart=Never --overrides="{ \"apiVersion\": \"v1\", \"spec\": { \"hostPID\": true, \"nodeSelector\": { \"kubernetes.io/role\": \"master\" }, \"tolerations\": [ { \"key\": \"node-role.kubernetes.io/master\", \"operator\": \"Exists\", \"effect\": \"NoSchedule\" } ] } }" -- master --version 1.11 -v 3
```

to no avail. Can someone help me figure out what do I need to do to check the EKS master node against the CIS benchmark?

@ttousai @lizrice I'll appreciate it. <3

**Comment by ttousai** [comment]
@teamhanded we are already tracking a similar EKS issue in #220 which you might find useful.

**Comment by lizrice** [comment]
I don’t believe the master node is accessible on EKS
