### ISSUE TITLE
Lint the YAML configuration files

### ISSUE THREAD

**Issue by cjschaef** [aquasecurity/kube-bench#254]
The provided YAML configuration files should be linted to remove whitespace and make sure the formatting is correct. As of today, some of them are a bit messy, not including the line length check.

It would be best to include this in the Travis checks on PR's, like most repositories.

**Comment by ttousai** [comment]
@cjschaef thanks for the suggestion.

**Comment by lizrice** [comment]
@cjschaef do you have a suggestion for the lint tool or maybe a link to an example? Thanks

**Comment by cjschaef** [comment]
@lizrice There are many different tools available, depending on your preferred installation method. In my experience [yamllint](https://yamllint.readthedocs.io/en/stable/) is a popular one given how common Python is on Linux distros and how easy it is to install with `pip`. Other linting tools such as the Rubygem [yaml-lint](https://github.com/Pryz/yaml-lint) or NodeJS [yaml-lint](https://www.npmjs.com/package/yaml-lint) are also available as well.

So it's dealer's choice at that point. I'm sure there are more tools available for the job.
