### ISSUE TITLE
RFC: retire federated checks

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#257]
I'd like to understand whether there is any demand to keep the benchmark checks for federated nodes. 

Federated checks were removed in version 1.3.0 of the CIS Kubernetes Benchmark, which applies to Kubernetes 1.11-1.12., so they are effectively deprecated from kube-bench since then anyway. 

Given the low usage of federation in Kubernetes I'm wondering if there is any demand to keep the checks for this that currently exist in config files for 1.6, 1.7 and 1.8? Comments welcome. 

cc @jerbia @liranaqua @ttousai

**Comment by ttousai** [comment]
@lizrice I think we should keep them:
- in the unlikely event someone is runs kube-bench against a 1.6-1.8 cluster
- we are considering discontinuing support for 1.6-1.8 anyways
- it hurts nothing to keep them
- it feels right to not drop them if we still want to support those version

**Comment by lizrice** [comment]
OK, we could retire this once the older versions are retired. See #289

**Comment by robertojrojas** [comment]
Fixed by #431
