### ISSUE TITLE
cannot execute binary 

### ISSUE THREAD

**Issue by kranthi0826** [aquasecurity/kube-bench#265]
Installing from a container: I am getting the following error.

**Comment by kranthi0826** [comment]
kranthimbp:kube-bench kranthikumarsara$ file kube-bench 
kube-bench: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
kranthimbp:kube-bench kranthikumarsara$ ./kube-bench
-bash: ./kube-bench: cannot execute binary file
kranthimbp:kube-bench kranthikumarsara$ ./kube-bench [master]
-bash: ./kube-bench: cannot execute binary file

**Comment by ttousai** [comment]
@kranthi0826 can you please share the exact command you used for installing from a container?

**Comment by heydonovan** [comment]
I'm receiving the same error:

```
$ docker run --rm -v (pwd):/host aquasec/kube-bench:latest install
===============================================
kube-bench is now installed on your host
Run ./kube-bench to perform a security check
===============================================
```

```
$ ./kube-bench
Failed to execute process './kube-bench'. Reason:
exec: Exec format error
The file './kube-bench' is marked as an executable but could not be run by the operating system.
```

```
$ file kube-bench
kube-bench: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by kranthi0826** [comment]
the command i used is $ docker run --rm -v `pwd`:/host aquasec/kube-bench:latest install
and  i tried  ./kube-bench [master|node]

**Comment by ttousai** [comment]
@kranthi0826 @heydonovan are you by any chance running on Mac OSX? The container install method builds for Linux x86_64 systems (see #178) . 

You can try building from source.

**Comment by kranthi0826** [comment]
@ttousai That means you are suggesting to use the another method

**Comment by kranthi0826** [comment]
I have one more problem while  Running in a kubernetes cluster:
$ kubectl apply -f  job-node.yam ----> when i do this command i getting only one pod got deployed  i.e one node, But actually i have 3 node cluster, how can i see the report of `3 nodes`
 
When the pod gets configured i use the below command to get the report
 $ kubectl logs <deployed pod>

**Comment by ttousai** [comment]
@kranthi0826 please share the output of `kubectl get po | grep node-ds`

**Comment by kranthi0826** [comment]
@ttousai  i am not getting any report while i run the above command , but if run the command kubectl get pods i can see the below snippet result ![image](https://user-images.githubusercontent.com/41030772/56594841-88cdf700-65bb-11e9-90a1-87b763624cec.png)

**Comment by kranthi0826** [comment]
To deploy this kube-bench-node-2cchz i made some changes in the job-node.yaml like adding the --version  command: ["kube-bench","node"]  ----->  command: ["kube-bench","node","--version","1.11"]

**Comment by ttousai** [comment]
@kranthi0826 please confirm that all your nodes are schedulable with the `kubectl get nodes` command.

**Comment by kranthi0826** [comment]
@ttousai  yes i can all my 3 nodes.
![image](https://user-images.githubusercontent.com/41030772/56595497-c2533200-65bc-11e9-8aab-1900a6400de5.png)

**Comment by ttousai** [comment]
@kranthi0826 it appears on one node is schedulable (the 2nd in the list) and I suspect 1 is the master. That will explain the fact that you get only 1 pod. Please check why the 3rd node has status NotReady.

**Comment by kranthi0826** [comment]
@ttousai  I am just updating my kubernetes version so its the not ready status, but i am asking how can i get the report on all the 3 nodes, do i need to change anything in the job-node.yaml or any other changes.

**Comment by ttousai** [comment]
@kranthi0826 no. Once your nodes are schedulable the daemon set will create pods running on all the nodes. So there should a total of 3 pods, 2 running on your nodes and 1 running on your master. But they must all be schedulable first.

**Comment by kranthi0826** [comment]
@ttousai ok, Once all nodes are in the Ready status, what you want me to do get the 3 pods, 2 running on your nodes and 1 running on your master.

**Comment by kranthi0826** [comment]
![image](https://user-images.githubusercontent.com/41030772/56600017-cdf72680-65c5-11e9-8681-fdb12eefcbd5.png)
all my nodes are ready, what should i need to run the `kube-bench` on all my `3 nodes`

**Comment by ttousai** [comment]
Closing this issue as solved.
