### ISSUE TITLE
RFC: change config numbering to reflect the spec rather than the Kubernetes version

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#269]
Currently the config files are numbered according to the earliest Kubernetes version for which the config is valid. As described in [this table in the README](https://github.com/aquasecurity/kube-bench#cis-kubernetes-benchmark-support), in most cases the CIS spec is valid for more than Kubernetes version, and this causes some confusion. 

We also now have config files for Openshift, and for JSON-specific versions of the files. I am wondering if it would be clearer to rename them something like this: 

| kube-bench config | Spec |
|:-----|:-----|
| cis-1.0.0 | CIS Kubernetes Benchmark 1.0.0 |
| cis-1.1.0 | CIS Kubernetes Benchmark 1.1.0 | 
| ...etc... | |
| rh-0.7 | Red Hat Openshift Hardening Guide 0.7 |
| cis-1.4.0-json | CIS Kubernetes Benchmark, for platforms configured using json / yaml |

Auto-detection should still work i.e. we'd include intelligence in `kube-bench` to know which CIS spec version is valid for which Kubernetes version. 

Comments welcome! 

cc @jerbia, @liranaqua

**Comment by lizrice** [comment]
@jerbia you are supportive of this, right?

**Comment by lizrice** [comment]
We would continue to support `--version` flag, which specifies the Kubernetes version. User can specify, say, `--version 1.12` and kube-bench should map this to the right CIS version. 

We would also add a flag `--benchmark`, which specifies the config directory, e.g. `--benchmark cis-1.1.0` which maps directly to the `cfg/cis-1.10` directory. 

It would be an error to specify both `--version` and `--benchmark` flags.

**Comment by robertojrojas** [comment]
fixed by #511
