### ISSUE TITLE
1.5.2 fails when --client-cert-auth flag is set

### ISSUE THREAD

**Issue by frsh2fourty** [aquasecurity/kube-bench#270]
In cfg/1.11/master.yaml check 1.5.2 checks that the --client-cert-auth flag is set to true for etcd. This test seems to fail even though that flag is set in my cluster and confirmed by manually running docker inspect etcd on the master node.

Changing the test_items to
op: has
value: "--client-cert-auth"
seems to make the test pass as it should.

Its worth noting that setting "--client-cert-auth" is the equivalent of setting "--client-cert-auth=true".

**Comment by ttousai** [comment]
@frsh2fourty thanks for filing this bug. PR #275 addresses this.

**Comment by lizrice** [comment]
Fixed by #275
