### ISSUE TITLE
Can step:1.4 Configuration Files be skipped if the configuration file doesn't exist?

### ISSUE THREAD

**Issue by Thinkwp** [aquasecurity/kube-bench#271]
If the configuration file does not exist, can this check step(1.4 Configuration Files) be skipped? Because k8s component is configured through command line parameters.

**Comment by ttousai** [comment]
@Thinkwp you can skip these checks manually by specifying the check groups kube-bench should run:
```
kube-bench master -g 1.1,1.2,1.3,1.5,.16
```

Majority of the checks in 1.4 are required by the CIS Kubernetes Benchmark (scored) and you will need to pass them if you are looking to get certified by CIS.

**Comment by Thinkwp** [comment]
@ttousai Thanks.
I have another question want to confirm. If I want to get certified by CIS,  do I have to configure k8s with a configuration file that is checked instead of using command line parameters?

**Comment by lizrice** [comment]
@Thinkwp in the most recent version of the CIS spec, it allows for config by either config file or command line parameters (although it doesn't really give the audit or remediation instructions in config file terms)

**Comment by lizrice** [comment]
Closing as I think this is now answered
