### ISSUE TITLE
Push latest release to Docker Hub

### ISSUE THREAD

**Issue by goffinf** [aquasecurity/kube-bench#274]
I note that kube-bench has been updated to support K8s 1.13, but on DockerHub it would appear that the latest tag image is 2 months old.

Could you possibly push the latest version to DockerHub please.

**Comment by lizrice** [comment]
cc @eranbibi

**Comment by goffinf** [comment]
Any movement on this one possible ?

**Comment by lizrice** [comment]
Latest version is now updated. Leaving open while we sort out the automated builds.

**Comment by goffinf** [comment]
Thanks @lizrice appreciate it. So that you are aware, we have an open feature request with Aquasec to run kube-bench with the Aqua CSP. There are some config issues with the current implementation which is why I am running kube-bench outside for now, hence why I really needed this version.

**Comment by ttousai** [comment]
Closing this issue as resolved.
