### ISSUE TITLE
Inconsistent tag/release naming convention

### ISSUE THREAD

**Issue by leodotcloud** [aquasecurity/kube-bench#277]
Problems:
- Currently, the tag/releases do not follow consistent convention/pattern.
Example: `0.0.27` vs `v0.0.28` (Notice the **v**?)
- The source code folder name inside the tar.gz file is also not consistent.
`v0.0.28.tar.gz` extracts to `kube-bench-0.0.28/*` [missing **v**]

These problems create quite a bit of pain when packing kube-bench. It would be great if a consistent approach is chosen.

Sample packaging that fails currently:
```
FROM ubuntu:18.04

ARG kube_bench_tag=v0.0.28

WORKDIR /
RUN apt-get update && apt-get install -y curl jq
RUN curl -sLf https://github.com/aquasecurity/kube-bench/releases/download/${kube_bench_tag}/kube-bench_${kube_bench_tag}_linux_amd64.tar.gz | tar xvzf - -C /usr/bin \
    && curl -sLf https://github.com/aquasecurity/kube-bench/archive/${kube_bench_tag}.tar.gz | tar --strip=1 xvzf - -C / kube-bench-${kube_bench_tag}/cfg
```

**Comment by lizrice** [comment]
Sorry about that, they should all have the “v” prefix in the tax and it’s my mistake that it has occasionally been missed. I have updated, please shout if you find any more I missed!
