### ISSUE TITLE
Skip etcd checks when etcd is not running on the host

### ISSUE THREAD

**Issue by kenperkins** [aquasecurity/kube-bench#287]
Currently, when I run kube-bench on one of my 1.11 masters where there is no etcd, I'm failing all of the etcd checks.

```
[FAIL] 1.4.7 Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.8 Ensure that the etcd pod specification file ownership is set to root:root (Scored)
...
[FAIL] 1.4.11 Ensure that the etcd data directory permissions are set to 700 or more restrictive (Scored)
[FAIL] 1.4.12 Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)
...
[INFO] 1.5 etcd
[FAIL] 1.5.1 Ensure that the --cert-file and --key-file arguments are set as appropriate (Scored)
[FAIL] 1.5.2 Ensure that the --client-cert-auth argument is set to true (Scored)
[PASS] 1.5.3 Ensure that the --auto-tls argument is not set to true (Scored)
[WARN] 1.5.4 Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate (Scored)
[WARN] 1.5.5 Ensure that the --peer-client-cert-auth argument is set to true (Scored)
[WARN] 1.5.6 Ensure that the --peer-auto-tls argument is not set to true (Scored)
```

```
core@ken-test-k8s-master-ne-1 /etc/kubernetes/manifests $ ls -la
total 44
drwxr-xr-x. 2 kube root 4096 Apr 26 19:53 .
drwxr-xr-x. 4 kube root 4096 Apr 26 19:58 ..
-rw-------. 1 root root 4491 Apr 26 19:53 kube-apiserver.yaml
-rw-------. 1 root root 2874 Apr 26 19:53 kube-controller-manager.yaml
-rw-------. 1 root root 1190 Apr 26 19:53 kube-scheduler.yaml
```

**Comment by lizrice** [comment]
You could work around this by [marking these checks as “skip”](https://github.com/aquasecurity/kube-bench#omitting-checks). This would be safer than trying to auto-detect, because we wouldn’t be able to tell the difference between etcd deliberately not running, and etcd having failed or being termporarily out of action (in which event you would want the tests to run). But I will leave this open for now for further comment.

**Comment by kenperkins** [comment]
I was wondering if maybe `etcd` should be considered an additional node type to go with `master` and `node` ? Many clusters do not run etcd on the same hosts as the master.

**Comment by lizrice** [comment]
That's a good idea - I'll raise it with the CIS folks

**Comment by lizrice** [comment]
I’m going to close this here; if/when it gets done in the CIS spec we will pick up that change in kube-bench
