### ISSUE TITLE
RFC: retire support for Kubernetes 1.10 and earlier

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#289]
Kubernetes is now at 1.14, and the three prior minor releases (1.11 on) are still supported. 

I propose we retire support for the tests related to older versions. 

cc @jerbia @ttousai

**Comment by ttousai** [comment]
+1 for me

**Comment by lizrice** [comment]
Let's retire the configs for everything prior to 1.11

**Comment by robertojrojas** [comment]
As of today **`10/2/2019`** here are the version supported:
 - Kubernetes core: 1.12 or later 
- AKS: 1.12.1 or later (https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions)
- EKS: 1.11.10 **(Amazon EKS will deprecate Kubernetes version 1.11 on November 4th, 2019)** or later
- GKE: 1.12.7 or later (https://cloud.google.com/run/docs/gke/cluster-versions)
- IKS: 1.12.10 (deprecated) or later https://cloud.ibm.com/docs/containers?topic=containers-cs_versions
- Ubuntu Charmed Kubernetes (CDK): 1.14 (Note:Only the latest three versions of Charmed Kubernetes are supported at any time) or later https://ubuntu.com/kubernetes/docs/install-manual

**Comment by robertojrojas** [comment]
Fixed by #429
