### ISSUE TITLE
executable 'apiserver' not running

### ISSUE THREAD

**Issue by J4m3sZ** [aquasecurity/kube-bench#294]
Hi, 

I have a GCP k8s cluster.
when i run the following command in kubectl - 
`kubectl run --rm -it kube-bench-node --image=aquasec/kube-bench:latest --restart=Never --overrides="{ \"apiVersion\": \"v1\", \"spec\": { \"hostPID\": true } }" -- master --version 1.8 -v2`

I get an error indicating there's no apiserver executable - 
```
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: unable to upgrade connection: container kube-bench-node not found in pod kube-bench-node_default
I0514 13:52:04.588773 2019682 util.go:122] Looking for config for version 1.8
I0514 13:52:04.588894 2019682 util.go:127] Looking for config file: cfg/1.8/master.yaml
I0514 13:52:04.589469 2019682 common.go:222] Using config file: cfg/1.8/config.yaml
I0514 13:52:04.589585 2019682 common.go:72] Using benchmark file: cfg/1.8/master.yaml
I0514 13:52:04.602085 2019682 util.go:43] [ps -C kube-apiserver -o cmd --no-headers]: exit status 1
I0514 13:52:04.602194 2019682 util.go:305] executable 'kube-apiserver' not running
I0514 13:52:04.611418 2019682 util.go:43] [ps -C hyperkube -o cmd --no-headers]: exit status 1
I0514 13:52:04.611574 2019682 util.go:305] executable 'hyperkube apiserver' not running
I0514 13:52:04.621534 2019682 util.go:43] [ps -C hyperkube -o cmd --no-headers]: exit status 1
I0514 13:52:04.621658 2019682 util.go:305] executable 'hyperkube kube-apiserver' not running
I0514 13:52:04.632244 2019682 util.go:43] [ps -C apiserver -o cmd --no-headers]: exit status 1
I0514 13:52:04.632372 2019682 util.go:305] executable 'apiserver' not running
```

I attached one of the pods and tried running ps command and indeed there are no apiserver executables running. Is it possible that in a GCP k8s cluster the pods won't any of the listed apiserver processes?

Thanks

**Comment by lizrice** [comment]
When you say "GCP" do you mean you installed k8s yourself, or is this GKE? If you don't have access to the master node (which I believe is true with GKE) then you won't be able to run the master tests, just the worker node tests.

**Comment by J4m3sZ** [comment]
Thanks, i did some resaearch about why it's not compatible and if someone will ever wonder why:
It's because in a default Google Cloud platform Kubernetes deployment the master is being managed by google.

[https://cloud.google.com/kubernetes-engine/docs/concepts/control-plane-security]()
[https://stackoverflow.com/questions/54434561/gke-master-node]()
