### ISSUE TITLE
container failed to start - "`pwd`" includes invalid characters

### ISSUE THREAD

**Issue by lirkog86** [aquasecurity/kube-bench#3]
[root@k8s32-vm0 kube-bench]# docker run --rm -v \`pwd\`:/host aquasec/kube-bench:latest
Unable to find image 'aquasec/kube-bench:latest' locally
Trying to pull repository docker.io/aquasec/kube-bench ...
latest: Pulling from docker.io/aquasec/kube-bench
ef0380f84d05: Extracting [==================================================>] 52.57 MB/52.57 MB
24c170465c65: Download complete
4f38f9d5c3c0: Download complete
d36744f83dc1: Download complete
107ef86d710c: Download complete
ef0380f84d05: Pull complete
24c170465c65: Pull complete
4f38f9d5c3c0: Pull complete
d36744f83dc1: Pull complete
107ef86d710c: Pull complete
b789525fd509: Pull complete
633896968756: Pull complete
f68634ee500b: Pull complete
e8bd062c9b27: Pull complete
d1516e5a487b: Pull complete
78a9aed077ca: Pull complete
65230781dafa: Pull complete
9606ea51ca81: Pull complete
Digest: sha256:20f2c34568ab9a889a923b9925d1c547532a6e71d583eb613353c1b98b1ff9f0
/usr/bin/docker-current: Error response from daemon: create `pwd`: "`pwd`" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
See '/usr/bin/docker-current run --help'.

**Comment by jerbia** [comment]
Fixed.
