### ISSUE TITLE
option "tls-cipher- suites" should be "tls-cipher-suites"

### ISSUE THREAD

**Issue by zhedahht** [aquasecurity/kube-bench#302]
In https://github.com/aquasecurity/kube-bench/blob/master/cfg/1.13/master.yaml#L505, the option "tls-cipher- suites" should be "tls-cipher-suites", removing the space between the second '-' and "suites".

In the same line, we should also remove extra spaces from the following word:
TLS_ECDHE_RSA_WITH_AES_128_GCM _SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM _SHA384
TLS_ECDHE_ECDSA_WITH_AES_256_GCM _SHA384

**Comment by yoavrotems** [comment]
Due to https://github.com/aquasecurity/kube-bench/pull/308 i think we can close it here and move the discussion to there
