### ISSUE TITLE
false positive on RotateKubeletServerCertificate test in openshift 3.11

### ISSUE THREAD

**Issue by vsevel** [aquasecurity/kube-bench#304]
Hello,

I am running kube-bench on the a compute node in openshift 3.11
my node-config.yaml contains:
```  
feature-gates:
  - RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true
```

I run:
```docker run --rm --pid=host -v /etc:/etc:ro -v /var:/var:ro -t aquasec/kube-bench:latest node --version ocp-3.10```

and I get:
```
[PASS] 7.14 Verify that the RotateKubeletClientCertificate argument is set to true
[FAIL] 7.15 Verify that the RotateKubeletServerCertificate argument is set to true
```

If I change the client certificate value to false:
```
  feature-gates:
  - RotateKubeletClientCertificate=false,RotateKubeletServerCertificate=true
```

then I get:
```
[FAIL] 7.14 Verify that the RotateKubeletClientCertificate argument is set to true
[FAIL] 7.15 Verify that the RotateKubeletServerCertificate argument is set to true
```

which is appropriate for the client but not for the server.

Expectation: 7.15 should not fail when we have:
```
  feature-gates:
  - RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true
```

**Comment by simar7** [comment]
I'd like to tackle this if it's still up for grabs.

cc/ @lizrice
