### ISSUE TITLE
Add feature to get kube-bench version

### ISSUE THREAD

**Issue by ttousai** [aquasecurity/kube-bench#311]
We need a way to show the version of kube-bench running, for example for reporting bugs.

Since the `--version` flag is already used to specify checks version to run, I propose we create a version sub-command to show the kube-bench version. For example:

```
$ kube-bench version
v1.13
```

**Comment by simar7** [comment]
Hey @ttousai I tried to take a crack at this here: https://github.com/aquasecurity/kube-bench/pull/313 Currently I'm using the `git-tag` for the released version. Do you think that makes sense or should it be combined together with the SHA as well?

**Comment by lizrice** [comment]
+1 for git-tag
