### ISSUE TITLE
need to change defaultsvc location  for worker node in 1.13 version

### ISSUE THREAD

**Issue by Richahasija** [aquasecurity/kube-bench#314]
Hi,

I am trying to change defaultsvc location for worker node to /etc/systemd/system/multi-user.target.wants/kubelet.service by mentioning 
defaultsvc: "/etc/systemd/system/multi-user.target.wants/kubelet.service" but it is automatically taking below location form util.go
defaultsvc: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
Any idea how can i change default defaultsvc location. Kindly help.

Thanks,
Richa Hasija

**Comment by Richahasija** [comment]
Hi, Can anyone help on above. @lizrice

**Comment by lizrice** [comment]
You should be able to modify the cfg/config.yaml file to work in your environment: either simply change the `defaultsvc` value, or you should be able to add it as a `svc:` entry that gets picked ahead of the `defaultsvc` value. 

Out of curiosity, what platform is this on? If you installed kubernetes yourself, which installer tool did you use?

**Comment by Richahasija** [comment]
i did it with both the options mentioned above i.e defaultsvc and svc: but its not updating the location and is taking the default location. while running kube bench in verbose mode. I am getting below output:

I0617 09:26:34.071047   27324 util.go:122] Looking for config for version 1.13
I0617 09:26:34.071078   27324 util.go:127] Looking for config file: cfg/1.13/node.yaml
I0617 09:26:34.071338   27324 common.go:222] Using config file: cfg/1.13/config.yaml
I0617 09:26:34.071369   27324 common.go:72] Using benchmark file: cfg/1.13/node.yaml
I0617 09:26:34.088831   27324 util.go:43] [ps -C hyperkube -o cmd --no-headers]: exit status 1
I0617 09:26:34.088897   27324 util.go:305] executable 'hyperkube kubelet' not running
I0617 09:26:34.106981   27324 util.go:102] Component kubelet uses running binary kubelet
I0617 09:26:34.124078   27324 util.go:102] Component proxy uses running binary kube-proxy
I0617 09:26:34.124141   27324 util.go:179] Using default config file name '/etc/kubernetes/kubelet.conf' for component kubelet
I0617 09:26:34.124169   27324 util.go:179] Using default config file name '/etc/kubernetes/addons/kube-proxy-daemonset.yaml' for component proxy
I0617 09:26:34.124190   27324 util.go:179] Using default config file name '/etc/kubernetes/config' for component kubernetes
I0617 09:26:34.124203   27324 util.go:210] Using default service file name '/etc/systemd/system/kubelet.service.d/10-kubeadm.conf' for component kubelet
I0617 09:26:34.124219   27324 util.go:213] Missing service file for proxy
I0617 09:26:34.124245   27324 util.go:213] Missing service file for kubernetes
I0617 09:26:34.124274   27324 util.go:241] Using default kubeconfig file name '/etc/kubernetes/kubelet.conf' for component kubelet
I0617 09:26:34.124282   27324 util.go:241] Using default kubeconfig file name '/etc/kubernetes/proxy.conf' for component proxy
I0617 09:26:34.124302   27324 util.go:244] Missing service file for kubernetes
I0617 09:26:34.124329   27324 util.go:389] Substituting $kubeletbin with 'kubelet'
I0617 09:26:34.124369   27324 util.go:389] Substituting $proxybin with 'kube-proxy'
I0617 09:26:34.124389   27324 util.go:389] Substituting $kubeletconf with '/etc/kubernetes/kubelet.conf'
I0617 09:26:34.124440   27324 util.go:389] Substituting $proxyconf with '/etc/kubernetes/addons/kube-proxy-daemonset.yaml'
I0617 09:26:34.124449   27324 util.go:389] Substituting $kubernetesconf with '/etc/kubernetes/config'
I0617 09:26:34.124453   27324 util.go:389] Substituting $kubeletsvc with '/etc/systemd/system/kubelet.service.d/10-kubeadm.conf'
I0617 09:26:34.124509   27324 util.go:389] Substituting $proxysvc with 'proxy'
I0617 09:26:34.124515   27324 util.go:389] Substituting $kubernetessvc with 'kubernetes'
I0617 09:26:34.124520   27324 util.go:389] Substituting $kubeletkubeconfig with '/etc/kubernetes/kubelet.conf'
I0617 09:26:34.124571   27324 util.go:389] Substituting $proxykubeconfig with '/etc/kubernetes/proxy.conf'
I0617 09:26:34.124592   27324 util.go:389] Substituting $kuberneteskubeconfig with 'kubernetes'
--------------------------------------------------------------------------------------------
Below is the config file that I changed.
  kubelet:
    bins:
      - "hyperkube kubelet"
      - "kubelet"
    confs:
      - "/var/lib/kubelet/config.yaml"
      - "/etc/kubernetes/kubelet/kubelet-config.json"
      - "/home/kubernetes/kubelet-config.yaml"
    svc:
      - "/etc/systemd/system/multi-user.target.wants/kubelet.service"
    defaultconf: "/var/lib/kubelet/config.yaml"
    defaultsvc: "/etc/systemd/system/multi-user.target.wants/kubelet.service"
    defaultkubeconfig: "/etc/kubernetes/kubelet.conf"

----------------------------------------------
We are using RHEL 7.5  and installed kubernetes with Kubeadm tool.

**Comment by lizrice** [comment]
That config file content looks right, but from the logs we can see it’s not being picked up. Where is the config file you’ve modified, is it `cfg/config.yaml`? There will also be a file at `cfg\1.13\config.yaml` and any values in that will override the `cfg/config.yaml` version, so it would be worth checking what’s there (the latest versions are essentially empty apart from a comment).

**Comment by Richahasija** [comment]
Yeah that is what i am unable to understand why svc location is not being picked up. There is nothing in cfg\1.13\config.yaml. It's empty.

## Version-specific settings that override the values in cfg/config.yaml

**Comment by Richahasija** [comment]
Hi @lizrice any idea, why I am unable to update svc path as mentioned above.

**Comment by lizrice** [comment]
How are you running kube-bench? Directly on the command line, in a container, or as a job? If the latter two have you checked that your versions of the config files are built into your version of the container?

**Comment by Richahasija** [comment]
I am running it as a job. kubectl apply -f job-node.yaml.
In the config file I am mentioning my version. 
containers:
      - name: kube-bench
        image: aquasec/kube-bench:latest
        command: ["kube-bench","node","--version","1.13","-v2"]

I didn't get this point?
have you checked that your versions of the config files are built into your version of the container?

**Comment by lizrice** [comment]
If you pull the container image from aquasec/kube-bench:latest, the config file is built into it, so it won't include your local changes. You'll need to rebuild the image with your changes, push the image to your registry of choice, and modify the job file to pull your version of the image from your registry. 

If `/etc/systemd/system/multi-user.target.wants/kubelet.service` is a standard location for the service file we can add it as one of the `svc` options in the version we build into the config file. That said, is it possible you have missed a `systemctl enable kubelet` step? Some googling of that file location suggests that running that command would result in `Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /etc/systemd/system/kubelet.service.`

**Comment by ttousai** [comment]
@lizrice we probably should add instructions for creating a custom config file with configmaps for kubernetes somewhere.

wdyt?

**Comment by lizrice** [comment]
@ttousai that's a great idea! Would you mind raising a separate issue for that enhancement please?

**Comment by simar7** [comment]
Hey @Richahasija do you still need further help with this issue? Let us know if you do so, otherwise I'll be closing this issue.

**Comment by lizrice** [comment]
Closing - please reopen if you still need help with this
