### ISSUE TITLE
Can kube-bench used to perform OCP security assessment by running kube-bench directly from the master node

### ISSUE THREAD

**Issue by skam-github** [aquasecurity/kube-bench#317]
1. Can kube-bench used to perform OCP security assessment by running kube-bench directly from the master node?
Meaning: I should install kube-bench only on master node and using cluster information it should automatically assess all the nodes (workers, masters and infrastructure) nodes.

**Comment by ttousai** [comment]
@skam-github yes. Once you install the kube-bench binary and have your kubeconfig file it will work.

**Comment by lizrice** [comment]
That answer isn't correct - you have to run kube-bench on each node that needs assessing
