### ISSUE TITLE
Add a json version of the config for Kubernetes 1.13

### ISSUE THREAD

**Issue by scottybrisbane** [aquasecurity/kube-bench#323]
We recently updated our EKS clusters to run Kubernetes 1.13 and have noticed there's no `1.13-json` config for `kube-bench`. Would be great if one could be added so that we can continue to accurately verify our security posture on EKS 😄

**Comment by Pratima** [comment]
Can someone help with an update on this?

**Comment by marcincuber** [comment]
@scottybrisbane Could you provide the command you are running to run kube-bench?

I was trying to use ```kubectl run --rm -i -t kube-bench-node --image=aquasec/kube-bench:latest --restart=Never --overrides="{ \"apiVersion\": \"v1\", \"spec\": { \"hostPID\": true } }" -- node --version 1.13``` however almost everything is failing. Whereas on EKS 1.12 only four things failed.

**Comment by lizrice** [comment]
@marcincuber the version 1.13 config won't be effective on EKS - you'll need the JSON version of the file, which we're working on. 

In the meantime you could use the 1.11-json config to give you some provisional results. There aren't a great number of changes between the CIS benchmarks at 1.3 (for Kubernetes 1.11) and 1.4 (for Kubernetes 1.13)

**Comment by lizrice** [comment]
This was done in #342

**Comment by scottybrisbane** [comment]
Hi @lizrice and @robertojrojas, thanks for the fix! Would it be possible to cut a release so we can start using it? :smile:
