### ISSUE TITLE
need to differentiate failing to find kubectl/kubelet from other executables

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#331]
Depending on the environment, failing to find the kubelet / kubectl might be resolved by specifying a version explicitly, or by specifying a different PATH. This is a different category of error from failing to find the control plane components. In these situations it may be that the config needs modifying to specify a different binary to look for. 

We should have different error messages in these two situations so that people are less likely to report them as the same issue (as in #328). We should also have kube-bench give better advice on how to modify the config to try to solve problems.

**Comment by robertojrojas** [comment]
Fixed by #497
