### ISSUE TITLE
kube-bench version cmd should not require config dir to be set

### ISSUE THREAD

**Issue by mrueg** [aquasecurity/kube-bench#334]
This happens if the config is not available on the right path, but kube-bench version should work independently of that:

```
/usr/bin/kube-bench version                                                                      :(
[FAIL] Failed to read config file: Config File "config" Not Found in "[/$PATH/cfg]"
```
with a path to config set:
```
/usr/bin/kube-bench version -D /etc/kube-bench/cfg                                                 :(
0.0.30
```

**Comment by ttousai** [comment]
Hello @mrueg I can't seem to reproduce this issue. This is what I did:
```
$ git checkout v0.0.30
$ make
GOOS=linux go build -ldflags "-X github.com/aquasecurity/kube-bench/cmd.KubeBenchVersion=v0.0.30" -o kube-bench .
$ sudo cp kube-bench /usr/bin
$ kube-bench version
0.0.30
```
- Did I miss something? 
- Did you build kube-bench from source?
- Can you upgrade to the latest kube-version, v0.0.33? 
- Do you have the same issue when you update to the latest kube-bench?

**Comment by mrueg** [comment]
Can you try executing `kube-bench version` from a different cwd? (e.g. `cd /` and then run `kube-bench version`) I think you don't see it because you have the cfg files in your CWD

**Comment by ttousai** [comment]
@mrueg thanks for pointing that out, I have reproduced this.
