### ISSUE TITLE
need proxy executable but none of the candidates are running, when use kube-router instead of kube-proxy

### ISSUE THREAD

**Issue by Slach** [aquasecurity/kube-bench#335]
when i use kube-router instead of kube-proxy
and run following command
```
KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/master/job.yaml
```
job finished with error status
and i see following error message
```
== Summary ==                                                                                                                                                                    
57 checks PASS
6 checks FAIL
28 checks WARN
0 checks INFO
need proxy executable but none of the candidates are running
```

**Comment by lizrice** [comment]
I think the best bet for this would be to set `optional: true` for the proxy binary in the config.yaml file. The tests may still fail or warn, but this is to be expected as the CIS Kubernetes Benchmark assumes that kube-proxy is being used. 

Individual users could chose to modify the test yaml to skip the kube-proxy tests if they aren't appropriate.

**Comment by simar7** [comment]
Closing as https://github.com/aquasecurity/kube-bench/pull/436 addresses this.
