### ISSUE TITLE
1.11-json test 2.1.1 is checking executable params instead of config file

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#337]
For some reason the first test in the node.yaml file in 1.11-json is testing against the executable parameter rather than looking at the equivalent setting in the config file.

* The audit parameter is [running ps](https://github.com/aquasecurity/kube-bench/blob/e6e6333e6dfeed41f7f709c7cba0ca66e39a29aa/cfg/1.11-json/node.yaml#L13) when it should be `cat`ing the config file.

* The test is checking for an executable [flag](https://github.com/aquasecurity/kube-bench/blob/e6e6333e6dfeed41f7f709c7cba0ca66e39a29aa/cfg/1.11-json/node.yaml#L16) when it should instead be using a `path` to specify the JSON/YAML field to check against. 

(I'm assuming that --allow-privileged can be set in a config file!)

**Comment by robertojrojas** [comment]
Looking at the [KubeletConfiguration](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go) shows that the **allow-privileged** is not set using the kubelet configuration file. In other words, it's only be set as a command argument.

**Comment by lizrice** [comment]
Let's add a comment into the YAML file so that we don't keep asking this same question :-)
