### ISSUE TITLE
anonymous-auth=true is secure by mention kubeadm team

### ISSUE THREAD

**Issue by Slach** [aquasecurity/kube-bench#341]
according to https://github.com/kubernetes/kubeadm/issues/1105#issuecomment-508099934
kubeadm team think --anonymous-auth=true is secure behavior

could anybody share kube-bench team opinion in source kubeadm issue or comment here?

**Comment by lizrice** [comment]
kube-bench is not opinionated - we implement the recommendations in the CIS Kubernetes Benchmark. You can raise the discussion by joining at https://workbench.cisecurity.org
