### ISSUE TITLE
Kubelet Config: Add Support for Test Comparison of Array Values

### ISSUE THREAD

**Issue by robertojrojas** [aquasecurity/kube-bench#344]
The value of the property **'tlsCipherSuites'** Kubelet Configuration file is an array of strings.
The tests does not appear to be working while parsing this property and reporting that 
the property is not being set correctly.
Here is a snippet sample of the Kubelet config file:

`{
  ...
   "tlsCipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  ],
  ...
}
`

This is the JSONPATH string in the **cfg/<version>-json/node.yaml** used to find the Kubelet config property value. Unfortunately, it doesn't appear to be working:

`
...
tests:
      test_items:
      - path: "{.tlsCipherSuites}"
        compare:
          op: eq
...
`

**Comment by robertojrojas** [comment]
This issue appears to be related to issue #243

**Comment by lizrice** [comment]
@robertojrojas is this done?

**Comment by robertojrojas** [comment]
yes, it was fixed by #367
