### ISSUE TITLE
Add 2.2.8 in 1.13-json

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#349]
While @robertojrojas was adding the 1.13-json config, we got an update that automates test 2.2.8 in #343. We need to update the 1.13-json/node.yaml file with those changes.

**Comment by PatrickSplice** [comment]
Can we add 2.2.7 to this issue?  That is currently marked as manual as well in the 1.13-json/node.yaml

    - id: 2.2.7
      text: "Ensure that the certificate authorities file permissions are set to
      644 or more restrictive (Scored)"
      type: manual
      remediation: |
        Run the following command to modify the file permissions of the --client-ca-file
        chmod 644 <filename>
      scored: true

Appears to be fixed, if I modify it to this:

    - id: 2.2.7
      text: "Ensure that the certificate authorities file permissions are set to
      644 or more restrictive (Scored)"
      audit: "/bin/sh -c 'if test -e $kubeletcafile; then stat -c %a $kubeletcafile; fi'"
      tests:
        bin_op: or
        test_items:
        - flag: "644"
          compare:
            op: eq
            value: "644"
          set: true
        - flag: "640"
          compare:
            op: eq
            value: "640"
          set: true
        - flag: "600"
          compare:
            op: eq
            value: "600"
          set: true
      remediation: |
        Run the following command to modify the file permissions of the --client-ca-file
        chmod 644 $kubeletcafile
      scored: true

**Comment by PatrickSplice** [comment]
It also appears test 2.1.13 is not working properly.  My test failed with this output:
2.1.13 Edit the kubelet service file /etc/systemd/system/kubelet.service
on each worker node and set the below parameter in KUBELET_CERTIFICATE_ARGS variable.
--feature-gates=RotateKubeletServerCertificate=true
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload
systemctl restart kubelet.service


Yet, if I check that seeing in my /etc/kubernetes/kubelet/kubelet-config.json:
  "featureGates": {
    "RotateKubeletServerCertificate": true
  },

**Comment by lizrice** [comment]
@PatrickSplice please let's have one issue per GitHub issue :-) 
* Regarding 2.2.7, that looks good, would you mind raising a PR for that? 
* Please could you raise a separate issue about 2.1.13?

**Comment by PatrickSplice** [comment]
Pull request submitted for 2.2.7 and new issue created for 2.1.13.

Thanks

**Comment by lizrice** [comment]
Original issue was fixed in #351 so this can now be closed
