### ISSUE TITLE
Incorrect feature gate configuration key in 1.13-json

### ISSUE THREAD

**Issue by scottybrisbane** [aquasecurity/kube-bench#369]
https://github.com/aquasecurity/kube-bench/blob/86e3456f33498c63e48857627d9d1c365d17dba9/cfg/1.13-json/node.yaml#L280
https://github.com/aquasecurity/kube-bench/blob/86e3456f33498c63e48857627d9d1c365d17dba9/cfg/1.11-json/node.yaml#L299
Comparing the configuration between `1.11-json` and `1.13-json` for the `RotateKubeletServerCertificate` check, I believe the path should remain as `{.featureGates.RotateKubeletServerCertificate}`, as it is in `1.11-json`. The format for feature gates doesn't seem to have changed in Kubernetes 1.13.

**Comment by scottybrisbane** [comment]
Any update on this? Would be great to see it resolved 😄

**Comment by berney** [comment]
This is being fixed in PR #371.

**Comment by scottybrisbane** [comment]
Hi @lizrice and @robertojrojas, thanks for the fix! Would it be possible to get a release made and docker image published so we can benefit from this fix?
