### ISSUE TITLE
Update 1.13 specs for new CIS release 1.4.1

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#370]
There is an update v1.4.1 of the CIS Benchmark for Kubernetes 1.13. We should update both 1.13 and 1.13-json configs to match.

**Comment by lizrice** [comment]
@yoavrotems working on this under PR #376

**Comment by lizrice** [comment]
@yoavrotems #376 covers the 1.13 config, could you also do one for 1.13-json please?

**Comment by cjschaef** [comment]
Does kube-bench now support the v1.4.1 CIS benchmark, given #376 has merged?

Can the README be updated now if this is the case?

**Comment by lizrice** [comment]
We still need to update 1.13-json, but I agree we could update the README already
