### ISSUE TITLE
Check 1.1.10 fails when flag is not set

### ISSUE THREAD

**Issue by mwwolters** [aquasecurity/kube-bench#374]
The AlwaysAdmit admission controller is not enabled by [default](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#which-plugins-are-enabled-by-default), but when this check runs and the flag is not set the test fails.

**Comment by yoavrotems** [comment]
I believe @robertojrojas is fixing this issue right?

**Comment by mwwolters** [comment]
I think #375 should fix this, @robertojrojas if you were working on this sorry to step on your toes.

**Comment by robertojrojas** [comment]
@mwwolters it's  all good. All contributions are really appreciated 💯
