### ISSUE TITLE
Testing locally with kind doesn't seem to work

### ISSUE THREAD

**Issue by VineethReddy02** [aquasecurity/kube-bench#382]
```
$ make kind-test-cluster
Could not find kube-bench cluster. Creating...
Creating cluster "kube-bench" ...
 ✓ Ensuring node image (kindest/node:v1.11.3) 🖼
 ✓ Preparing nodes 📦 
 ✓ Creating kubeadm config 📜 
 ✗ Starting control-plane 🕹️ 
Error: failed to create cluster: failed to init node with kubeadm: exit status 1
make: *** [makefile:43: kind-test-cluster] Error 1
````
But  ```make kind-test-cluster``` is using the oldest version **kindest/node:v1.11.3**
When I run ```kind create cluster``` for other purposes it uses **kindest/node:v1.15.0**

**Comment by lizrice** [comment]
@yoavrotems you're looking at this already, right?

**Comment by yoavrotems** [comment]
Hey its seems like you are correct and it was making problems we now going to use the most recent version 1.15.3 https://github.com/aquasecurity/kube-bench/pull/411.
Thanks for your issue

**Comment by yoavrotems** [comment]
That's was fixed and marged into master https://github.com/aquasecurity/kube-bench/pull/411
