### ISSUE TITLE
Remove out-of-date kubernetes/conf from config.yaml

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#384]
`cfg/config.yaml` currently has a kubernetes section which, as the comments suggest, is only there to cover references to `/etc/kubernetes/config`. I can only see `kubernetesconf` referred to in the 1.7 test files, so I think we should retire this section from the main `cfg/config.yaml` file. It could be moved into the 1.7-specific config file instead.

**Comment by robertojrojas** [comment]
I think this issue is somewhat related to #289 and should be fixed once #429 is merged.
