### ISSUE TITLE
Check 2.1.13 in 1.13-json node check reports incorrectly

### ISSUE THREAD

**Issue by PatrickSplice** [aquasecurity/kube-bench#387]
It appears test 2.1.13 is not working properly. My test failed with this output:
2.1.13 Edit the kubelet service file /etc/systemd/system/kubelet.service
on each worker node and set the below parameter in KUBELET_CERTIFICATE_ARGS variable.
--feature-gates=RotateKubeletServerCertificate=true
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload
systemctl restart kubelet.service

Yet, if I check that setting in my /etc/kubernetes/kubelet/kubelet-config.json:
"featureGates": {
"RotateKubeletServerCertificate": true
},

**Comment by lizrice** [comment]
If you are using a json config file, at the moment you'll need to specify `--version=1.13-json` to pick up the set of tests for that. 

At the moment kube-bench can either pick up the config from the command line parameters that you see if you run `ps` for the kubernetes components, *or* from the json config file. (We'll be working on combining the two soon.)

**Comment by robertojrojas** [comment]
Fixed by #353
