### ISSUE TITLE
kube-bench for kubernetes versions for 1.15.x

### ISSUE THREAD

**Issue by abhiTamrakar** [aquasecurity/kube-bench#393]
can we use this version to run bench-marking for kubernetes version 1.15.x? if not, when shall we expect it. I am also ready to contribute if needed, please let me know.

**Comment by andrewrynhard** [comment]
On that note, what is the policy that the aquasecurity team has around how often they will release configs for version of k8s?

**Comment by lizrice** [comment]
We implement the CIS Kubernetes benchmarks, and currently the most recent release of the benchmark is 1.4.1. That's aimed at Kubernetes 1.13 onwards (as documented in the README). 

There is a draft version of a 1.5.0 release of the benchmark in progress at https://workbench.cisecurity.org, which will apply to Kubernetes 1.15+, and we'll implement that as soon as we can after it has been published.
