### ISSUE TITLE
1.5.5 and 1.5.6 should not be manual tests

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#394]
Please correct for 1.13 and 1.13-json, 1.11 and 1.11-json

**Comment by yoavrotems** [comment]
Hey done [here ](https://github.com/aquasecurity/kube-bench/pull/398)and added 1.5.4, because it also shouldn't be manual

**Comment by yoavrotems** [comment]
And about the 1.11-json  1.13-json Those tests do not exist because master nodes are controlled by EKS and not user-accessible.
