### ISSUE TITLE
remediation text should be platform agnostic

### ISSUE THREAD

**Issue by kwmonroe** [aquasecurity/kube-bench#415]
This came up when adding support for snap-based components in #389.  Snaps are driven by config files with systemd services, which makes current remediation text confusing.  For example, there is no `pod specification` file for snaps so I'd like to change this remediation text to be more generic:
```diff
-      Edit the API server pod specification file $apiserverconf
+      Edit the API server configuration file $apiserverconf
```

**Comment by lizrice** [comment]
This makes sense to me, but we try not to diverge from the CIS benchmark. I've raised a ticket against the benchmark: https://workbench.cisecurity.org/benchmarks/1370/tickets/9719
