### ISSUE TITLE
--encryption-provider-config not properly detected

### ISSUE THREAD

**Issue by TheKangaroo** [aquasecurity/kube-bench#420]
We run kubernetes components in docker container started by systemd units.
The parameters for apiserver are properly detected, but when I added the `--encryption-provider-config` flag, it still warns me with 
```
[WARN] 1.1.34 Ensure that the --encryption-provider-config argument is set as appropriate (Scored)
```
as if I did not specify the parameter.
Same goes for the check in the encryptionconfig file
```
[WARN] 1.1.35 Ensure that the encryption provider is set to aescbc (Scored)
```
I'm not sure, what's wrong here.
We are on k8s 1.13 so I run kube-bench with 
```
docker run --pid=host -v /etc:/etc:ro -v /var:/var:ro -t aquasec/kube-bench:latest master --version 1.13
```
If I understand kube-bench correct, it checks something like
```
ps -ef |grep apiserver |grep -v grep
```
and watches the result for the parameter. As expected I can see the `--encryption-provider-config` in the output if run manually.
I guess I'm missing something here, but I'm not sure what.

**Comment by lizrice** [comment]
Please could you run with debug logging on (add the parameter `-v 3`) and share the results?

**Comment by TheKangaroo** [comment]
Sorry for the late response. I somehow missed your reply.
Here is the debug log for `docker run --pid=host -v /etc:/etc:ro -v /var:/var:ro -t aquasec/kube-bench:latest master --version 1.13 -v 3`:
```

```

**Comment by TheKangaroo** [comment]
I accidentally closed this issue, but the fix of @mrueg sounds legit. I didn't even recognize the manual type.
