### ISSUE TITLE
Output in junit

### ISSUE THREAD

**Issue by johnSchnake** [aquasecurity/kube-bench#460]
Would you be open to a PR which added the option to output in a junit format so that these could effectively be parsed as a test suite?

As of now the json output is just the json representation of the controls object which has to be parsed as a one-off if someone wants to automate this. If we could output into junit then other tools could more easily consume the results and check for pass/failure count etc.

**Comment by johnSchnake** [comment]
I'm happy to put up a PR for this, but effectively this is the plan of work:
 - currently the data that gets printed is in the `Controls` datatype; that type has a flag for `json` output and for `pgsql` output
 - We would add a new flag `junit` which would output to the junit format
 - this would require a new method, analgous to the `JSON()` method on the `Controls` object but would just create a value junit suite of test results. The datatypes needed should be valid junit; I would recommend using the types defined either:
 - using the ginkgo types like the Kubernetes tests would report them: https://github.com/onsi/ginkgo/blob/master/reporters/junit_reporter.go#L23-L61
 - or using the go-junit types which are a pretty common format (but I think it is a little more unclear how to map generic chardata into those types): https://github.com/jstemmer/go-junit-report/blob/master/formatter/formatter.go#L16-L59

The implementation would just be a matter of deciding the mapping between fields of those types but in most cases I think that is pretty straight forward:
 - In all cases, we could store the 'prettyPrint' version of the value as the stdout if we want to simplify things
 - the mapping between passing/failing tests in both cases is 1-1
 - I'm only really unsure about warning/info values; are those considered passing?
 - if we want we can have a slightly finer grain mapping. Clearly specific error/failure messages would go in the corresponding fields on the new type.

I wanted to make sure you'd be open to it though before proceeding.

**Comment by johnSchnake** [comment]
I just put up a PR for this; let me know what you think. I looked at your releases and saw that you may be due for another one shortly. I was hoping to get this in before the next release if possible as it is a feature we'd love to utilize in an integration.

**Comment by DhruvTrehan** [comment]
I got your idea. But my skills are not so advanced to turn your idea into
code. I am working on it. I am learning each day.
