### ISSUE TITLE
kube-bench for master node 

### ISSUE THREAD

**Issue by lordcf** [aquasecurity/kube-bench#488]
I am trying to deploy kube-bench , when using the jobs.yml for node with version specification in command line it works fine pod gets created successfully.
but when using jobs-master.yml file for master node I am facing following issue 
kc get pods 
NAME                      READY   STATUS    RESTARTS   AGE
kube-bench-master-l4gvj   0/1     Pending   0          66m

After ssh into master vm
 Error syncing job: failed pod(s) detected for job key "security/kube-bench"

**Comment by lordcf** [comment]
pod description says this 
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  81s (x5 over 4m20s)  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.
what should i specify in node selector?

**Comment by NandoTheessen** [comment]
It looks like none of your nodes are available for scheduling, this could have multiple causes but I don't think it's related to kube-bench.

**Comment by jgsqware** [comment]
Maybe you have should have a toleration to allow the scheduling on the master node.

**Comment by robertojrojas** [comment]
Hi @lordcf does this continue to an issue for you?

**Comment by lizrice** [comment]
I think what @jgsqware suggests is very likely the cause - it's often the case that master nodes are tainted to prevent pods from running on them. This [doc](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation) describes how to remove the taint.

I'm closing on the assumption that this is the reason it's not working - please re-open if it continues to be a problem, attaching the output from `kubectl describe` for the node and the pod.
