### ISSUE TITLE
Run kube-bench image as non-root user

### ISSUE THREAD

**Issue by s-nirali** [aquasecurity/kube-bench#498]
This update is in view of following security best practices.

**Comment by lizrice** [comment]
I don't think this is going to work on all platforms as there are some cases where it needs root privilege to look at certain files. @robertojrojas wdyt?

**Comment by robertojrojas** [comment]
I think this might not work in cases where the code needs to read certain file, **/var/lib/kubelet/config.yaml** is one example that comes to mind.

**Comment by s-nirali** [comment]
Hello @lizrice , @robertojrojas . I've tested the container created using a non-root user by mounting the /var and /etc directory . All contents of the directory are accessible inside to the non-root user. The results of running kube-bench with or without the root user are also the same. However, the "install" command in the entrypoint script does require root privileges to install the binary in the host. For that, I updated the makefile in the PR with the following usage command.

```
docker run --rm -v `pwd`:/host -u 0:0 aquasec/kube-bench:latest install
```

We've been using kube-bench in our organization and it's been a really great experience so far. Thank you for developing this 😃  . However, recently, I was asked to make this change which is why I raised an issue and a PR here. I'm not aware about any specific checks that require root to run. If there are, it would be great to have them documented so I can show it to my reviewers. It'll also be helpful if someone could thoroughly test the PR for any breaking checks or other issues that I might've missed.

**Comment by leodotcloud** [comment]
It doesn't matter who the user is inside the container, if the docker run command is invoked as root.

**Comment by lizrice** [comment]
It may be possible to run kube-bench as a non-root user on some platforms, but in general we believe that it will need to be root (on the host) to have correct access to certain config files, and to produce correct results. For that reason we are not proposing to pursue this issue. 

Note that the associated PR #499 sets up the image as a non-root user, but then overrides the user with -u 0:0 so that it does actually run the container as root.
