### ISSUE TITLE
Addition of exit code(s)?

### ISSUE THREAD

**Issue by jondkent** [aquasecurity/kube-bench#509]
Hi,

I'm wondering if it would be a good idea to have a non-zero exit code on any FAILS to allow kube-bench to be run more programmically?  Obviously any non-zero would mean digging into any log created.  Not expecting this for WARN messages, though maybe possible to have a code for individual FAIL, WARN states and a code for a mix of the 2?

Cheers,
Jon

**Comment by robertojrojas** [comment]
@jondkent thanks for the suggestion.
 
At the moment, the main idea of **kube-bench** was to provide a report based on CIS Benchmark checks. 
If you need programmatic way, you could use the **"--json"** flag and parse the JSON payload.

**Comment by jondkent** [comment]
Thanks, I'll go that route

**Comment by robertojrojas** [comment]
Closing...
