### ISSUE TITLE
Where to run the kube-bench ? 

### ISSUE THREAD

**Issue by muradmomani** [aquasecurity/kube-bench#512]
Hello,

I read that i can run kube-bench on my host, as container on the cluster and as docker image.

1.what is the difference between running kube-bench on my host or as a container in the cluster itself?

2.should I run it on each worker and master node on my cluster to get the security status of each one or I can  only run it on one node and it will scan all other worker and master nodes in the cluster ?

**Comment by robertojrojas** [comment]
@muradmomani **kube-bench** performs a check on the host that you run only. Currently, the tool doesn't have the ability to discover members of the cluster.

Running  **kube-bench** on a host or a container is a matter of choice. One way to think about this is running **kube-bench** directly provides more flexibility, but requires more configuration (i.e create the cfg directory, etc..)
Running **kube-bench** as a container or a Kubernetes Pod (look at the job-*.yaml files) comes with the '**cfg'** directory 

You can run **"kube-bench"** without any sub-commands and the tool will try to figure out if the host is a _master_ and/or a _node_. 

 Also, If the host you're running the tool is a **_master_** as part of the Kubernetes control plane, you would run it like **"kube-bench master".** 

 If the host is a _worker_ node, you would run it like **"kube-bench node"**.

**Comment by robertojrojas** [comment]
For more detail take a look at our [README](https://github.com/aquasecurity/kube-bench/blob/master/README.md) file 

Closing...
