### ISSUE TITLE
Artifacts/Binaries missing for v0.1.0 release

### ISSUE THREAD

**Issue by leodotcloud** [aquasecurity/kube-bench#515]
Hi team, could you please upload the binaries for the latest release?

[Not sure if I am checking too early, at the time of creating this issue, it's been 3 hours since the release]

**Comment by robertojrojas** [comment]
@leodotcloud Thanks for reporting this. we're looking into this.

**Comment by robertojrojas** [comment]
@leodotcloud binaries should be available now [v0.1.0](https://github.com/aquasecurity/kube-bench/releases/tag/v0.1.0.)
Closing
