### ISSUE TITLE
Support alternative file locations for kubeconfig

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#521]
In order to accommodate the file locations needed for AKS, as shown in [this commit](https://github.com/andyzhangx/kube-bench/commit/5f5ee060445b762ae93945a8288e7de0c20caf9d) we need the ability to specify alternative locations for the kubelet kubeconfig file

**Comment by robertojrojas** [comment]
Appears to be fixed by #383

**Comment by robertojrojas** [comment]
Fixed by #383
