### ISSUE TITLE
Summary should cover all tests

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#528]
When you run kube-bench without specifying the node type, on a master node it runs the master tests, outputs a summary of those, then runs the node tests and outputs a separate summary of those. It would be better if there was one summary covering all the tests that have been run

**Comment by johnSchnake** [comment]
Do you think it would also make sense to (either by default or optionally) describe all tests; regardless of whether they were run or not? That way the report would be consistent across any given run regardless if they were master or node tests. The tests not run would just be marked as skipped.

It seems like that may make it easier or people saving/running lots of these to view different reports with less of a context switch (e.g. since the first test in the report will be the same every time)

**Comment by lizrice** [comment]
It might be good to at least indicate when an entire section is skipped (because it's not relevant on that node). From CIS 1.5.0 it's no longer just master & node tests - there are now five different sections

**Comment by czunker** [comment]
Hi,

I've added some changes to a fork, which changes the summary sections as I understood the above comments.
This is an example output for a node:
```
$ ./kube-bench --noremediations --noresults
== Summary master==
0 checks PASS
0 checks FAIL
0 checks WARN
65 checks INFO

== Summary etcd==
0 checks PASS
0 checks FAIL
0 checks WARN
7 checks INFO

== Summary controlplane==
0 checks PASS
0 checks FAIL
0 checks WARN
3 checks INFO

== Summary node==
10 checks PASS
5 checks FAIL
8 checks WARN
0 checks INFO

== Summary policies==
0 checks PASS
0 checks FAIL
24 checks WARN
0 checks INFO

== Summary Total==
10 checks PASS
5 checks FAIL
32 checks WARN
75 checks INFO
```

All master, etcd and control plane checks are skipped and at the end, there are summed up checks across all sections.

I just wanted to check, whether I understood the comments correctly, before opening the PR.

**Comment by lizrice** [comment]
That looks pretty close to what I was imagining, although I don't think we should have totals for a section that has been skipped, as this could potentially mislead the user into thinking they should have run. So I'd say the overall totals should just be of the So on a worker node I'd imagine the output above might be like this: 

```
== Master section skipped ==
== Etcd section skipped ==
== Controlplane section skipped ==

== Summary node ==
10 checks PASS
5 checks FAIL
8 checks WARN
0 checks INFO

== Summary policies ==
0 checks PASS
0 checks FAIL
24 checks WARN
0 checks INFO

== Summary Total ==
10 checks PASS
5 checks FAIL
32 checks WARN
0 checks INFO
```

**Comment by czunker** [comment]
Thanks for your feedback @lizrice. I'll change it accordingly.

**Comment by czunker** [comment]
I changed the code and now it looks like this on a node:
```
$ ./kube-bench --noremediations --noresults
== Skipping master checks ==
== Skipping etcd checks ==
== Skipping managed services checks ==
== Summary node ==
10 checks PASS
5 checks FAIL
8 checks WARN
0 checks INFO

== Summary policies ==
0 checks PASS
0 checks FAIL
24 checks WARN
0 checks INFO

== Summary total ==
10 checks PASS
5 checks FAIL
32 checks WARN
0 checks INFO

```


And like this on a master:
```
$ ./kube-bench --noremediations --noresults
== Skipping managed services checks ==
== Summary master ==
38 checks PASS
19 checks FAIL
8 checks WARN
0 checks INFO

== Summary etcd ==
2 checks PASS
4 checks FAIL
1 checks WARN
0 checks INFO

== Summary controlplane ==
0 checks PASS
0 checks FAIL
3 checks WARN
0 checks INFO

== Summary node ==
10 checks PASS
5 checks FAIL
8 checks WARN
0 checks INFO

== Summary policies ==
0 checks PASS
0 checks FAIL
24 checks WARN
0 checks INFO

== Summary total ==
50 checks PASS
28 checks FAIL
44 checks WARN
0 checks INFO

```
