### ISSUE TITLE
RPM only contains the binary

### ISSUE THREAD

**Issue by rrey** [aquasecurity/kube-bench#536]
Hello,

The RPM only contains the `kube-bench` binary.
The configuration and yaml representation of the cis bench is not included and requires additional downloads to be able to run `kube-bench`.

Is there any reason for omitting this ?

**Comment by robertojrojas** [comment]
@rrey thanks for reporting this. 
I'll take a look at cause of this and fix it.

**Comment by robertojrojas** [comment]
Fixed by #540
