### ISSUE TITLE
release cycle

### ISSUE THREAD

**Issue by leodotcloud** [aquasecurity/kube-bench#557]
Hi Team,

Is it possible to have a biweekly release (bump the PATCH number of vMAJOR.MINOR.PATCH) for downstream projects to pick up the latest fixes quickly?

**Comment by lizrice** [comment]
Hi @leodotcloud right now we're planning the next drop for end of January, would that meet your needs for now or would it be helpful to have one sooner? 

I agree with you we need to get our house in order with better visibility on release timings

**Comment by leodotcloud** [comment]
Really appreciate your support, it would be great if we can have one release before end of this month, since the previous one is one month old already.

**Comment by lizrice** [comment]
Cutting a release right now!
