### ISSUE TITLE
Add v1.8 support

### ISSUE THREAD

**Issue by luxas** [aquasecurity/kube-bench#56]
Kubernetes v1.8 is now released :tada:, let's get some YAML profiles for this fancy new version as well :smile:

**Comment by lizrice** [comment]
Yes! There will be an update to the CIS spec very soon and then we can generate the YAML to match 😀

**Comment by luxas** [comment]
Cool! @lizrice Would you mind joining a SIG Cluster Lifecycle video call btw to discuss how we can have a better kubeadm <-> kube-bench integration? I'd eventually like to use sth like this in our automated tests.
(separate issue though)

**Comment by lizrice** [comment]
I'd love to. This is Tuesdays 5pm UK time, right? I can't make it this week but could do the 10th, if that works.

**Comment by luxas** [comment]
Yes, sounds good!

**Comment by timothysc** [comment]
@lizrice I'd be happy to help review e2e-prs that you might want to add.  Please denote any additions as [Feature:xyz] to allow for selective enablement. 

/cc @mattmoyer

**Comment by bitvector2** [comment]
What is the current status on this?  We would very much like to use and can help with the work effort...

**Comment by luxas** [comment]
@lizrice ^

@bitvector2 On updating this project for v1.8 or integrating with kubeadm?

**Comment by lizrice** [comment]
1.8 support is now released (yay!) 

I'll close this issue now and open another one for kubeadm integration. We would very much welcome help and/or pointers on how to get started with that (I'm not familiar with the codebase over there).
