### ISSUE TITLE
Add option to ignore check-failures

### ISSUE THREAD

**Issue by mrueg** [aquasecurity/kube-bench#564]
Some checks in the kube-bench might currently not be feasible for a user and the user wants to ignore them. 
Currently the user can only specify all tests except for those via `--check`.
It would be good if kube-bench could provide a CLI argument, that allows to soft-fail on specified tests, so they still would run but would not alter the return code:

1.1.1.2 and 1.1.1.3 fail, a user could run:
```kube-bench --expect-fail "1.1.1.2,1.1.1.3"``` and still the return code would be 0 (if all other checks pass)

**Comment by lizrice** [comment]
Another option is to modify the test YAML, would that suit your needs?

**Comment by mrueg** [comment]
I'd like to avoid that, maintaining numbers for the command seems to be easier than patching the yaml from a user perspective (especially with a kube-bench container using a readonly rootfs, although I have to admit this can of course be changed at buildtime).

**Comment by lizrice** [comment]
Another idea: `--skip` which has a comma separated list of tests that should be treated as if they were marked with "skip" - wdyt?

**Comment by mrueg** [comment]
skip works for the use case as well. soft-fail would allow to make that list smaller and smaller over time.

**Comment by lizrice** [comment]
I think we should go with `—skip` because it’s consistent with the terminology we use inside the YAML file, and it would have the same effect - kube-bench would just not run a test if it’s marked as `skip` either in YAML or with this parameter

**Comment by illyaMs** [comment]
Trying to figure out the draft implementation. Some questions so far (would be nice to have feedback/answers from maintainers):

1. Do I get it right that a proper place to introduce this new logic is the [filtering predicate](https://github.com/aquasecurity/kube-bench/blob/35cf28c140bdb6f84c3a29749780a08594300f69/cmd/common.go#L31)?
1. I see that having both `--group` and `--check` options at the same time is [explicitly prohibited](https://github.com/aquasecurity/kube-bench/blob/35cf28c140bdb6f84c3a29749780a08594300f69/cmd/common.go#L33). Should it be the same for this new `--skip` option? Or it is ok to have for example both `--skip` and `--group` options at the same time?
1. Should we have separate options like `--skipGroup` and `--skipCheck`, or having just `--skip` to support both filterings is enough?
1. Should `--skip` option take precedence over the `skip` field in test's yaml definition?

Thanks in advance.

**Comment by iahmad-khan** [comment]
Hi,

Do we need to rebuild the docker image for custom skip configurations? I am deploying to Kubernetes using job spec , is there a way to mount those skip configurations as configMap?

thanks.

**Comment by Wicked7000** [comment]
Created a PR for this please let me know if anything needs to be changed!

**Comment by lizrice** [comment]
fixed in #751
