### ISSUE TITLE
Openshift 4

### ISSUE THREAD

**Issue by aelbarkani** [aquasecurity/kube-bench#568]
Hi guys,

Are there any plans to support Openshift 4 ?

Thanks !

**Comment by lizrice** [comment]
We would love to support OpenShift 4 as soon as there is a hardening guide from Red Hat that we can implement

**Comment by rasheedamir** [comment]
any updates on this @lizrice ?

**Comment by hugohdz89** [comment]
Hello @lizrice not sure if this helps

https://bugzilla.redhat.com/show_bug.cgi?id=1756602

**A new version of the OpenShift 3.11 Security Guide has been updated and published for OpenShift 4.5. It was also back ported to OpenShift 4.4**. This content represents significant enhancements from the 3.11 guide, including coverage of:

* Red Hat Enterprise Linux CoreOS (RHCOS)
* Hardening
* Red Hat Universal Base Images (UBI)
* Red Hat Registry and Red Hat Ecosystem Catalog
* Red Hat Quay
* Multitenancy
* Admission plug-ins
* Network policies and isolation

To hold the new content, a new "Security" bucket was added to the docs.openshift.com left navigation. You can see the new content here:

https://docs.openshift.com/container-platform/4.5/security/container_security/security-understanding.html

While most of the updated Container Security Guide is conceptual information, some hands-on security content was added to the new Security bucket as well. This includes:

* Configuring certificates
* Certificate types and descriptions
* Allowing JavaScript-based access to the API server from additional hosts
* Encrypting etcd data
* Scanning pods for vulnerabilities

**Comment by robermar23** [comment]
Any updates on support for OpenShift 4?  Seems as if OpenShift 4.x does have a requisite hardening guide now?

**Comment by yoavrotems** [comment]
Yes and its out, you can use kube-bench version 0.6.0 or latest to use it :)
