### ISSUE TITLE
New check result type: not applicable

### ISSUE THREAD

**Issue by leodotcloud** [aquasecurity/kube-bench#575]
On certain platforms, few of the checks are not applicable and it doesn't make sense to skip them. Would it be possible to introduce this new type in kube-bench?

Example:
```
      - id: 1.4.1
        type: skip
        text: "Ensure that the API server pod specification file permissions are
    set to 644 or more restrictive (Scored)"
```

In a cluster create by [rke](https://github.com/rancher/rke), there is no pod spec file present at all, so the check is not applicable.

**Comment by lizrice** [comment]
I'm not sure I follow why it doesn't make sense to skip a test if it's not applicable? That's exactly the kind of reason why we imagined someone might want to mark a test as "skip". Am I missing something?
