### ISSUE TITLE
The check of cis-1.5-1.2.23 and cis-1.4-1.1.16 should accept any number

### ISSUE THREAD

**Issue by mozillazg** [aquasecurity/kube-bench#580]
https://github.com/aquasecurity/kube-bench/blob/77f66511e70c4b2c1f83988786e3de04ec7349db/cfg/cis-1.4/master.yaml#L257-L266
the current check limit the value of `--audit-log-maxage` must >= 30, but in CIS it accept any number > 0:

> set the --audit-log-maxage parameter to 30 **or as an appropriate number of days**

![图片](https://user-images.githubusercontent.com/485054/74321979-24845a00-4dbe-11ea-8204-7ece40f1d3d9.png)

**Comment by robertojrojas** [comment]
@lizrice Does this require review at the CIS Benchmark document level?

**Comment by lizrice** [comment]
The kube-bench implementation should match what's in the benchmark as closely as possible, and although I do agree the benchmark is ambiguous, my reading of it implies a recommendation of at least 30 days in most circumstances. I don't think that a check allowing any positive value is in the spirit of the recommendation being made here. 

I have raised a[ discussion in CIS](https://workbench.cisecurity.org/community/43/discussions/5735) with the aim of getting this language tightened up. 

All the benchmark recommendations should be followed with the application of judgement of whether they are applicable in a particular environment. Having YAML format tests allows for users to modify them to suit their own business requirements as needed.
