### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by coolpalani** [aquasecurity/kube-bench#587]
Could you add dashboard for view report post scanning completion.
It would be great to review all reports.

**Comment by neha-viswanathan** [comment]
Hi @yoavrotems @lizrice any pointers on this? Is this dashboard supposed to be displayed on the CLI or a UI?

**Comment by yoavrotems** [comment]
I don't believe there is any special specifications here, as always the more flexible the better :)

**Comment by lizrice** [comment]
This is supported by our [Starboard](github.com/aquasecurity/starboard) project. You can run a kube-bench job through the Starboard CLI, and have the results appear in a dashboard like Octant or Lens.
