### ISSUE TITLE
kubelet `--tls-*` checks don't validate the presence/absence of TLS (2.1.10)

### ISSUE THREAD

**Issue by anguslees** [aquasecurity/kube-bench#588]
I think `2.1.10 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate` is not a useful test, and should be deprecated/removed.

I think the test is trying to verify a CIS item that apiserver->kubelet communication is always encrypted (good).  It does this by checking for the existence of these two `--tls-*` flags.  I think _without_ these flags (or config equivalents), the kubelet generates a self-signed key pair - so this traffic **is always encrypted**.  Hence my proposal to just drop this specific test altogether, rather than "fix" it in some way.

Thoughts?  Should I put together a PR?

**Comment by lizrice** [comment]
In kube-bench we implement the tests as written in the CIS Benchmark. If you'd like to suggest changes to the benchmark itself please join the [CIS community](https://workbench.cisecurity.org/communities/43) and raise a ticket or a discussion there. Thanks!
