### ISSUE TITLE
Need help understanding WARN state and scoring mechanism

### ISSUE THREAD

**Issue by Docteur-RS** [aquasecurity/kube-bench#595]
Hey !

I'm a bit confused about the [WARN] state...  

Can someone explain the difference between "scored" and "not scored" ?

I also don't get how it influences the state ? **Scored** + **unable to test** creates what in the end ??  
And the other way around is not clear either. The worst case that blows each theories that I've got so far is the **warn** + **scrored**. This makes no sense what so ever ! :-p  

Thanks in advanced

**Comment by lizrice** [comment]
"Scored" or "Not scored" comes from the CIS benchmark itself (so if you find any cases where our test files don't match the CIS benchmark, please raise an issue). 

"Warn" means that the test needs manual attention: see https://github.com/aquasecurity/kube-bench#output

kube-bench might be unable to run a test because, for example, an executable that it needs to run is not available in the path. 

Does that help? Open to ideas on how to clarify the README

**Comment by Docteur-RS** [comment]
Thanks for your answer.  

 I got the following From the CIS documentation :  

**Scored**  
* Failure to comply with "Scored" recommendations will decrease the final benchmark score.
Compliance with "Scored" recommendations will increase the final benchmark score.  

**Not Scored**  
* Failure to comply with "Not Scored" recommendations will not decrease the final
benchmark score. Compliance with "Not Scored" recommendations will not increase the
final benchmark score.  

This could be part of the readme because
* The "scored" and "not scored" status appears everywhere in the output of kube-bench
* There is no explanation of the terms "scored" and "not scored" in the Readme
* The CIS definition of the status is quite hard to find on the internet.

---

```
There are three output states:

[PASS] and [FAIL] indicate that a test was run successfully, and it either passed or failed.
[WARN] means this test needs further attention, for example it is a test that needs to be run manually.
[INFO] is informational output that needs no further action.
Note:

If the test is Manual, this always generates WARN (because the user has to run it manually)
If the test is Scored, and kube-bench was unable to run the test, this generates FAIL (because the test has not been passed, and as a Scored test, if it doesn't pass then it must be considered a failure).
If the test is Not Scored, and kube-bench was unable to run the test, this generates WARN.
If the test is Scored, type is empty, and there are no test_items present, it generates a WARN.
```

Let's decompose the above paragraph taken from the readme:

PASS  
* Test was able to run + Test has PASSED  => **What about scored and not scored in this state ?**

WARN  
* (A) May have to be run manually => **What about scored and not scored ?**
* (B) Runned automatically + "not scored" + unable to run the test => **Lacks information in readme about why a test could not be run**

So I **guess** that all WARN + "scored" are type (A) because (B) is "not scored" only. This should also be in the Readme.  

FAIL  
* Test was able to run + Test has FAILED
* Runned automatically + "scored" + unable to run the test

The readme could use a board to sum up all the different cases.  

---

Lets take an example:  
Test:  
`1.1.9 Ensure that the Container Network Interface file permissions are set to 644 or more restrictive (Not Scored)`  

Remediation:  
`1.1.9 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 <path/to/cni/files>`

So, WARN + "not scored"  is type (B). Then it should mean that the test was not able to run.  
**Why is a simple chmod check was unable to run ?**

Second example:  
Test:  
`[WARN] 1.1.19 Ensure that the Kubernetes PKI directory and file ownership is set to root:root (Scored)`

Remediation:
`1.1.19 Run the below command (based on the file location on your system) on the master node.
For example,
chown -R root:root /etc/kubernetes/pki/`
So, WARN + "scored" means type (A). Then this should be a manual test... **Why isn't this automatic ? And if it must be run manualy, what should I do ? Should I make my own test based on the description of the "test" section ?**

---

A lot of questions here ! I hope that you can lift a few of my interogation ! 😄
