### ISSUE TITLE
CIS v1.5 Test 4.1.8 marked as FAIL but file perm/ownership is correct. 

### ISSUE THREAD

**Issue by pulberg** [aquasecurity/kube-bench#598]
Hi, thanks so much for the kube-bench tool, it has been really helpful to us.  I am trying to understand one of the tests that reports FAIL, but the file check comes back correctly.

My k8s platform is Rancher - 

OS - Ubuntu 18.04
Rancher - v2.3.5
k8s - v1.17.2
kube-bench - v0.2.3

I grabbed the kube-bench .deb release and installed, here is the cmd I am running on a "worker" node - 

`kube-bench --benchmark cis-1.5 run --targets node > k8sdev-kube-bench-worker.txt`

The specific test I am looking at is 4.1.8 - 

> 4.1.8 Ensure that the client certificate authorities file ownership is set to root:root (Scored)

After running kube-bench, test 4.1.8 comes back as FAIL -
`[FAIL] 4.1.8 Ensure that the client certificate authorities file ownership is set to root:root (Scored)`

The Rancher CIS Benchmark Guide for this [test](https://rancher.com/docs/rancher/v2.x/en/security/benchmark-2.3.5/#4-1-8-ensure-that-the-client-certificate-authorities-file-ownership-is-set-to-root-root-scored) suggests to run this script to check the file in question for 4.1.8 - 
`/bin/sh -c 'if test -e /etc/kubernetes/ssl/kube-ca.pem; then stat -c %U:%G /etc/kubernetes/ssl/kube-ca.pem; fi'`

If the file check is correct you should get back `root:root` which I do - 
`~$ /bin/sh -c 'if test -e /etc/kubernetes/ssl/kube-ca.pem; then stat -c %U:%G /etc/kubernetes/ssl/kube-ca.pem; fi'
root:root`

And looking at the file itself we can also see this - 
`~$ ll /etc/kubernetes/ssl/kube-ca.pem
-rw------- 1 root root 1017 Dec 12 11:36 /etc/kubernetes/ssl/kube-ca.pem`

So I am trying to figure out what could be going on here, since the file info comes back correct, but kube-bench is still marking this as FAIL.

Thanks.

**Comment by lizrice** [comment]
Hi @pulberg thanks for reporting this. 

We just merged a change #565 to master that changes the way we do file permissions checks, so it would be great if you could clone the master branch and try with that. If you still see the problem please could you run with `-v 10 --logtostderr` and send the log output?

**Comment by pulberg** [comment]
Grabbed Master and built, right away I see something that may be the actual issue.  There is a difference between what you are checking for in test 4.1.8 and where my `--client-ca-file` is - 

Log from kube-bench - 

`I0316 17:28:54.261858   18457 check.go:192] Check.ID: 4.1.8 Command: "/bin/sh -c 'if test -e /etc/kubernetes/pki/ca.crt; then stat -c %U:%G /etc/kubernetes/pki/ca.crt; fi' " TestResult: false State: "FAIL"`

The path and file to be tested are totally different than where my `--client-ca-file` is - 
kube-bench master test 4.1.8 - 
`/bin/sh -c 'if test -e /etc/kubernetes/pki/ca.crt; then stat -c %U:%G /etc/kubernetes/pki/ca.crt; fi'`

My `--client-ca-file` is - 
`/etc/kubernetes/ssl/kube-ca.pem`

In looking at the "official" CIS Benchmark v1.5 it says to derive the `--client-ca-file` by running 
`ps -ef | grep kubelet` which shows the correct path on my node - 

`--client-ca-file=/etc/kubernetes/ssl/kube-ca.pem`

It looks like kube-bench is not able to determine the correct `--client-ca-file` path which is resulting in the FAIL (i'd argue that this isn't correct either, there should be a call out when the test can't run due to not finding files/paths/etc).

**Comment by lizrice** [comment]
We should enhance `kube-bench` to search for the right config file live, as described in the spec. But meanwhile, a workaround is to configure the `node.kubelet.cafile` in `cfg/config.yaml` to include `/etc/kubernetes/ssl/kube-ca.pem` in the list. Could you give that a try?
