### ISSUE TITLE
Bump a new version?

### ISSUE THREAD

**Issue by mozillazg** [aquasecurity/kube-bench#599]
All issues of v0.3.0 (https://github.com/aquasecurity/kube-bench/milestone/6) have been fixed/closed, maybe it's time to bump a new version?

**Comment by hlarubi** [comment]
Hi,

Would the bump include the support for newer Kubernetes versions by any chance (1.16 maybe?)?

Thanks!

**Comment by lizrice** [comment]
@mozillazg thanks I completely forgot we hadn't already done this! I have just tagged it

@hlarubi 1.16 Kubernetes is covered by the 1.5.* version of the CIS Benchmark
