### ISSUE TITLE
Getting issue in running Kube-Bench

### ISSUE THREAD

**Issue by Anuj-B** [aquasecurity/kube-bench#600]
Hi , 

I am trying to run Kube-Bench on master node but getting below  issue 
"[FAIL] No config settings for master"
/etc/kubernetes/config/ doesn't exist in our setup .

Please suggest the changes required to run tool

**Comment by lizrice** [comment]
This error tells us that kube-bench is not finding the config file which by default is expected to live at `cfg/config.yaml` 

Please could you indicate the command you used to run kube-bench?

**Comment by Anuj-B** [comment]
Hi ,

I am using below commands one by one .

1.     kube-bench master

2.     kube-bench node --version 1.13

3. kube-bench node --benchmark cis-1.4


BR,

Anuj

**Comment by lizrice** [comment]
Do you have the `cfg` directory in the location where you are running those commands?

**Comment by Anuj-B** [comment]
Yes, directory is there and it is having config.xml

**Comment by gliptak** [comment]
try overriding ```cfg``` location

```
./kube-bench --config-dir `pwd`/cfg --config `pwd`/cfg/config.yaml
```

**Comment by yoavrotems** [comment]
Hi ! did @gliptak  answer worked for you?

**Comment by gliptak** [comment]
@yoavrotems I didn't run into this. just pointing a fellow traveler

**Comment by Anuj-B** [comment]
Hi ,

It didn't work for me .

BR,
Anuj

**Comment by yoavrotems** [comment]
Hey could you please run it again with -v 3 --logtostderr and submit here ?

**Comment by yoavrotems** [comment]
Closing it due to no response.
If this is still an issue please let us know and we will reopen this

**Comment by LQss11** [comment]
make sure the directory exists which will include config files and this is what you will see when you type `kube-bench -h`:
```sh
-D, --config-dir string                config directory (default "/etc/kube-bench/cfg")
```
>When you download the release with the same version you through this [link](https://github.com/aquasecurity/kube-bench/releases) from the official release download page you will find a cfg directory there
