### ISSUE TITLE
--outputfile flag for kube-bench is not working

### ISSUE THREAD

**Issue by karthiksiva-github** [aquasecurity/kube-bench#603]
Hi,

./kube-bench --outputfile doesn't seem to work. I find two issues here

1) json log is not getting generated in the defined path
2) There seems to be no validation done for the path provided in the outputfile.

Kindly check and let know when the issue will be resolved .

Thanks,
Karthik

**Comment by mozillazg** [comment]
`--outputfile` should use with `--json` like this: `./kube-bench  --json --outputfile result.json`

**Comment by karthiksiva-github** [comment]
Thanks @mozillazg  . It worked.. However the help menu can be updated to avoid confusions.

**Comment by karthiksiva-github** [comment]
Hi @mozillazg,

./kube-bench --json --outputfile /tmp/result1.json is not logging all the benchmark checks in /tmp/result1.json..
Ideally all the info displayed as part of ./kube-bench --json should be logged in /tmp/result1/json as well. But it doesn't seem to happen.

**Comment by mozillazg** [comment]
@karthiksiva-github Looks like it is a bug.

**Comment by karthiksiva-github** [comment]
Not sure in which release will it be fixed.. Anyway @mozillazg thanks for confirming

**Comment by mozillazg** [comment]
@karthiksiva-github You can use `./kube-bench --json > result.json` as a workaround.
