### ISSUE TITLE
unable to get benchmark version. error: config file is missing 'version_mapping' section

### ISSUE THREAD

**Issue by krangerich** [aquasecurity/kube-bench#613]
Download kube-bench_0.3.0_linux_amd64.tar.gz and extract.

1. Run `./kube-bench master` as stated in documentation:

unable to determine benchmark version: config file is missing 'version_mapping' section

2. Run `./kube-bench run`:

unable to get benchmark version. error: config file is missing 'version_mapping' section

So either version 0.3.0 is broken or the documentation of a minimum working example is wrong.

**Comment by gliptak** [comment]
https://github.com/aquasecurity/kube-bench/issues/600

**Comment by krangerich** [comment]
This solution works, but then the documentation should be fixed. A basic example has to work out of the box.

**Comment by lizrice** [comment]
We need to enhance the documentation to point out that not only do you need the executable downloaded, but also the config files and tests

**Comment by LQss11** [comment]
make sure the directory exists which will include config files and this is what you will see when you type `kube-bench -h`:
```sh
-D, --config-dir string                config directory (default "/etc/kube-bench/cfg")
```
>When you download the release with the same version you through this [link](https://github.com/aquasecurity/kube-bench/releases) from the official release download page you will find a cfg directory there
