### ISSUE TITLE
Add support for saving scan results to PgSQL

### ISSUE THREAD

**Issue by bitvector2** [aquasecurity/kube-bench#62]
See PR #61

**Comment by lizrice** [comment]
Hi @bitvector2! Thanks for this PR, I'm just taking a look now. I'm curious to hear more about the background and the use case, if you have a couple of mins to describe them? Thanks!

**Comment by bitvector2** [comment]
Hi @lizrice we have about a dozen k8s clusters, each with 32 nodes and we are wanting to make a daemonset out of kube-bench, plus a cronjob.  We want to apply a centralized set of audits to all nodes (without redeploying pods because audits were updated) with centralized storage of scan results, and all of this occurring regularly over time.  Taking the path the least resistance this would be Viper remote configs coming from a central etcd cluster, and all kube-bench instances writing to a database.  We like PgSQL via Amazon RDS thus the PR as an ice breaker.l

**Comment by lizrice** [comment]
Nice. It would be great if we could incorporate the daemonset config into kube-bench, if you'd be open for sharing that? Also, curious to know if you have a way of figuring out which test set (master / node / federated) to run or is that part of the config you'll pull from etcd?

**Comment by lizrice** [comment]
Fixed in #61
