### ISSUE TITLE
Why are some of the tests related to Kubernetes policies marked as `manual`?

### ISSUE THREAD

**Issue by neha-viswanathan** [aquasecurity/kube-bench#620]
I was wondering why some of the tests related to policies were marked as `manual`.  My understanding is that the tests are manual for now and that these tests will be automated at a later point in time. 
Is my assumption correct? Please correct me if I'm wrong. Thanks!

**Comment by mozillazg** [comment]
@neha-viswanathan There are two reason:

* Some recommendations(for example: `5.1.4 Minimize access to create pods`) don't include tests(which can't test via command) in document of CIS Kubernetes Benchmark.
* Some recommendations(for example: https://github.com/aquasecurity/kube-bench/issues/623) need `kube-bench` to access api server to run test, but `kube-bench` don't support it yet.
