### ISSUE TITLE
Minimize the admission of containers with allowPrivilegeEscalation (Scored)

### ISSUE THREAD

**Issue by yaminisridaran** [aquasecurity/kube-bench#623]
Kube-bench tool displaces warning for **Minimize the admission of containers with allowPrivilegeEscalation (Scored)**.  I have configured one psp in my k8s cluster and psp has allowPrivilegeEscalation is set to false. I have deployed job.yaml in my cluster.
spec:
    allowPrivilegeEscalation: false
    allowedCapabilities:
    - NET_ADMIN

Can anyone please let me know whether I am missing anything here

**Comment by mozillazg** [comment]
@yaminisridaran Because the `kube-bench` doesn't check the psp yet, this check is marked as `manual`:

https://github.com/aquasecurity/kube-bench/blob/master/cfg/cis-1.5/policies.yaml#L97-L103

**Comment by lizrice** [comment]
I hope this answers your question (thanks @mozillazg!)
