### ISSUE TITLE
How to install Kube-bench commands in Windows or Ubuntu machine

### ISSUE THREAD

**Issue by nidiculageorge** [aquasecurity/kube-bench#624]
nidicula@TOPS-ONCALL:~$ kube-bench master
kube-bench: command not found

Could someone help

**Comment by mozillazg** [comment]
@nidiculageorge You can download it from release page: https://github.com/aquasecurity/kube-bench/releases 

BTW, kube-bench don't support Windows yet.

**Comment by nidiculageorge** [comment]
How can we run againsta cluster, for CIS benchmark checking

**Comment by mozillazg** [comment]
@nidiculageorge Just run ./kube-bench or use Docker:

https://github.com/aquasecurity/kube-bench#installing-from-sources
https://github.com/aquasecurity/kube-bench#installing-from-a-container

**Comment by nidiculageorge** [comment]
Hi @mozillazg 

When I try to run the kube-bench installation in ubuntu i am getting the following error

![image](https://user-images.githubusercontent.com/43850474/82747729-ce11b900-9db9-11ea-8c12-c1688f9747e9.png)


I am running the file from the location in which the package is there

**Comment by nidiculageorge** [comment]
Hi @mozillazg 

When i try to run the following i could see the following error

kube-bench master

failed to get a set of executables needed for tests: unable to detect running programs for component "kubelet"
