### ISSUE TITLE
Take a time to checking if there is any scored check which hasn't an audit command when possible

### ISSUE THREAD

**Issue by mozillazg** [aquasecurity/kube-bench#635]
There are some scored checks not have an audit command when it is possible been check via command. For example:

https://github.com/aquasecurity/kube-bench/blob/1b5b6c2afe5fb1e0060ae96346f77484842cef75/cfg/cis-1.5/node.yaml#L100-L106

And some scored checks have been marked as `manual` even if it has an audit command. For example:

https://github.com/aquasecurity/kube-bench/blob/1b5b6c2afe5fb1e0060ae96346f77484842cef75/cfg/cis-1.5/master.yaml#L288-L296

**Comment by lizrice** [comment]
Fixed with #640 and #641, but please open a new issue if you find any more tests incorrectly marked as manual. Thanks!
