### ISSUE TITLE
Not writing logs into output file. 

### ISSUE THREAD

**Issue by Bujail** [aquasecurity/kube-bench#637]
kube-bench not writing logs into output file. I ran kube-bench as follows.

kube-bench master --version 1.15 --log_dir /tmp/results --outputfile /tmp/results/output.xml

Am I missing anything here?

**Comment by yoavrotems** [comment]
Hey, are sure the /tmp/results directory is exist? 
When I run it I get the logs, so could make sure the dir is exist? and if so maybe provide more information?  (Your env, run it with -v=3, and etc)

**Comment by yoavrotems** [comment]
OK since I don't see the problem or able to reproduce it I'm closing the issue, 
please let us now if its still an issue and post some more information.
