### ISSUE TITLE
[EKS] running kubebench is only showing Node results

### ISSUE THREAD

**Issue by sgandon** [aquasecurity/kube-bench#644]
I am not sure if  this is something I did but I am simply running the job-eks.yaml but unlike the documentation I did not rebuilt the image I just used the public one from docker hub.
```
          image: aquasec/kube-bench:latest
```
 when running this job I only get a results from the `Node` config (3.X)
Looking at the eks-1.0 config there are multiple categories of tests, how to run them ?
I have tried to run those following the root doc by using the option `--targets`
```
         command: ["kube-bench", "node", "--benchmark", "eks-1.0", "--targets", "node, policies, managedservices"]
```
But  "kube-bench"  fails saying it does not support the `--targets` what am I doing wrong ?

**Comment by fert-f** [comment]
When I accessed CLI to troubleshoot this bug I tried:
`kube-bench --benchmark eks-1.0 run --targets managedservice
The specified --targets "managedservice" does not apply to the CIS Benchmark eks-1.0 \n Valid targets []`
while:
```
kube-bench --benchmark gke-1.0 run --targets managedservice
The specified --targets "managedservice" does not apply to the CIS Benchmark gke-1.0 \n Valid targets [master node controlplane etcd policies managedservices]
```

**Comment by thehunt33r** [comment]
This should be addressed once this is merged: https://github.com/aquasecurity/kube-bench/pull/648

**Comment by yoavrotems** [comment]
Thanks @thehunt33r for the comment and solution :) 
closing this issue.
