### ISSUE TITLE
Test 1.2.13 Warns when PSP is included in --enable-admission-plugins instead of Passing?

### ISSUE THREAD

**Issue by distortedsignal** [aquasecurity/kube-bench#650]
From the CIS 1.5.1 guide:

---

# 1.2.13 Ensure that the admission control plugin SecurityContextDeny is set if PodSecurityPolicy is not used (Not Scored)

### Profile Applicability

* Level 1

### Description

The SecurityContextDeny admission controller can be used to deny pods which make use of some SecurityContext fields which could allow for privilege escalation in the cluster. This should be used where PodSecurityPolicy is not in place within the cluster.

...

### Audit

Run the following command on the master node:

```sh
ps -ef | grep kube-apiserver
```

Verify that the `--enable-admission-plugins` argument is set to a value that includes `SecurityContextDeny`, **if `PodSecurityPolicy` is not included**. (emphasis mine)

---

Running this command on my K8s Master node (and doing some post-processing on the text to make it easier to read):

```sh
> ps -ef | grep -v grep | grep kube-apiserver
kube-apiserver ... --enable-admission-plugins=PodPreset,NodeRestriction,PodSecurityPolicy ...
```

However, when I run kube-bench against just that test...

```sh
> kube-bench --benchmark cis-1.5 --check="1.2.13"
[INFO] 1 Master Node Security Configuration
[INFO] 1.2 API Server
[WARN] 1.2.13 Ensure that the admission control plugin SecurityContextDeny is set if PodSecurityPolicy is not used (Not Scored)

== Remediations ==
1.2.13 Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml
on the master node and set the --enable-admission-plugins parameter to include
SecurityContextDeny, unless PodSecurityPolicy is already in place.
--enable-admission-plugins=...,SecurityContextDeny,...

```

From my reading of the text of the CIS benchmark, since I have `PodSecurityPolicy` set in the `--enable-admission-plugins` flag, this should pass. Could you please explain why I am receiving a `Warn` from this test?

**Comment by mozillazg** [comment]
@distortedsignal Because the `kube-bench` only checked the `SecurityContextDeny` plugin not check the `PodSecurityPolicy` :

https://github.com/aquasecurity/kube-bench/blob/ea4eaa6fd51f3a157d1309f644ea8021d369f109/cfg/cis-1.5/master.yaml#L519-L534

**Comment by distortedsignal** [comment]
Looks like #651 should fix this.
