### ISSUE TITLE
Easily-missed bad version check

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#655]
If kube-bench is using `kubectl` to auto-detect the running version of kubernetes, but the kubeconfig isn't available, the version check will fail and kube-bench falls back to a default of kubernetes 1.11. 

I found this easily by running kubernetes on a vagrant machine. The kubeconfig file was installed for the user called vagrant, but running `kube-bench` as root meant kubeconfig was not set up. 

In this situation `-v 3 --logtostderr`  includes these logs:

```
I0803 17:05:45.584195   12442 util.go:53] Client Version: v1.18.3
The connection to the server localhost:8080 was refused - did you specify the right host or port?
I0803 17:05:45.584503   12442 util.go:351] Unable to get Kubernetes version from kubectl, using default version: 1.11
```

We should update the default version to a current version (say, 1.18) rather than an ancient version of kubernetes that is no longer supported

We should emit a warning in this situation to suggest specifying the version or ensuring that kubeconfig is available.

**Comment by yoavrotems** [comment]
PRs #656 and https://github.com/aquasecurity/kube-bench/pull/657 solves this issue
