### ISSUE TITLE
EKS "exec format error"

### ISSUE THREAD

**Issue by simar7** [aquasecurity/kube-bench#671]
_Originally posted by @manjo-git in https://github.com/aquasecurity/kube-bench/pull/628#issuecomment-671417026_

I have EKS deployed with m6.large (ARM64), and I am using  image: aquasec/kube-bench:latest in my jobs-eks.yaml and I get an "exec format error". My jobs-eks.yaml can be found here: https://pastebin.ubuntu.com/p/4MvfX5XHBh/

$ kubectl get pods --all-namespaces
NAMESPACE     NAME                       READY   STATUS              RESTARTS   AGE
default       kube-bench-t62lc           0/1     ContainerCreating   0          2s
default       kube-bench-zwz4r           0/1     Error               0          7s
kube-system   aws-node-fxhxv             1/1     Running             0          6m32s
kube-system   aws-node-mgr89             1/1     Running             0          6m32s
kube-system   aws-node-q7fsq             1/1     Running             0          6m31s
kube-system   coredns-59dd559b88-csjll   1/1     Running             0          18m
kube-system   coredns-59dd559b88-x6t9s   1/1     Running             0          18m
kube-system   kube-proxy-6b958           1/1     Running             0          6m32s
kube-system   kube-proxy-p22qx           1/1     Running             0          6m32s
kube-system   kube-proxy-xx7tl           1/1     Running             0          6m31s

$ kubectl logs kube-bench-zwz4r
standard_init_linux.go:211: exec user process caused "exec format error"

Can you please point me in the right direction as to how to use the public kube-bench image for ARM64 EKS ? The instructions https://github.com/aquasecurity/kube-bench#running-in-an-eks-cluster seems to work only for AMD64 because AWS has command lines tools only on AMD64 and not on ARM64.

**Comment by lizrice** [comment]
Aha, is this on Graviton2 machines in AWS?

**Comment by simar7** [comment]
> Aha, is this on Graviton2 machines in AWS?

hi @manjo-git would you know?

**Comment by manjo-git** [comment]
Yes this is on Graviton2 system in AWS.

**Comment by manjo-git** [comment]
Hello, is there any update on this one? I would like to give it a go on the graviton2 that just went GA on AWS today. https://aws.amazon.com/blogs/containers/eks-on-graviton-generally-available/

**Comment by lizrice** [comment]
@manjo-git would you have time to try out this image that I've pushed to Docker Hub?  `aquasec/kube-bench:8780c8e` It should have both arm64 and amd64 support:

**Comment by manjo-git** [comment]
`

$ cat job-eks-v2.yaml 
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
spec:
  template:
    spec:
      hostPID: true
      containers:
        - name: kube-bench
          # Push the image to your ECR and then refer to it here
          image: aquasec/kube-bench:8780c8e
          command: ["kube-bench", "node", "--benchmark", "eks-1.0"]
          volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"

$ kubectl get pods
NAME               READY   STATUS   RESTARTS   AGE
kube-bench-474zm   0/1     Error    0          35s
kube-bench-5lh28   0/1     Error    0          51s
kube-bench-jd6v7   0/1     Error    0          45s
kube-bench-p6dfw   0/1     Error    0          15s

$ for i in $(kubectl get pods | cut -f 1 -d " " | grep -v -i name) ; do  echo "-- logs for $i --" ; kubectl logs $i ; done
-- logs for kube-bench-474zm --

failed to get a set of executables needed for tests: unable to detect running programs for component "kubelet"
-- logs for kube-bench-5lh28 --

failed to get a set of executables needed for tests: unable to detect running programs for component "kubelet"
-- logs for kube-bench-jd6v7 --

failed to get a set of executables needed for tests: unable to detect running programs for component "kubelet"
-- logs for kube-bench-p6dfw --

failed to get a set of executables needed for tests: unable to detect running programs for component "kubelet"

`

**Comment by lizrice** [comment]
OK, so the original problem of running on an ARM processor is fixed now. The remaining part of this issue is probably fixed by #702 so I'm going to close for now, please open a new issue if you still see "unable to detect running programs"
