### ISSUE TITLE
Unable to fetch compliance status for few of the CIS recommendations

### ISSUE THREAD

**Issue by ankitsrao** [aquasecurity/kube-bench#680]
**What steps did you take and what happened:**

1) I'm running the kube-bench utility on my Kubernetes clusters (deployed on AWS EC2 instances), and the scan gets complete, but few of the recommendations seem missing.

Command used : kube-bench --benchmark cis-1.5

Below are the CIS control IDs (CIS Kubenetes Benchmark 1.5.0), which do not come up in the kube-bench scan:

- 1.1.9, 1.1.10, 1.1.20, 1.1.21
- 1.2.1, 1.2.10, 1.2.12, 1.2.13, 1.2.33, 1.2.34, 1.2.35
- 1.3.1
- 4.2.9

I'm successfully able to see the scan data for all other CIS recommendations of these categories.
I understand that the recommednations in  CIS category 5, require some manual intervention and hecne not worried about them.

2) Also, I've already commented regarding the etcd recommendations in thread https://github.com/aquasecurity/kube-bench/issues/667
So, for etcd recommendations, the kube-bench scan shows the recommendations as FAIL, even though we follow the remedoation steps specified by CIS.

**What did you expect to happen:**
- I expected that kube-bench scans and provides the compliance details for all policies in the first 4 categories of the CIS Kubernetes Benchmark 1.5.0, which in my case is not happening. Some policies do not come up in the scan.
- I would therefore, request someone to provide details as to why these recommendations do not come up in the kube-bench scan.
- Is there something that I'm doing wrong or some additional steps I need to follow to retireve the data for these recommendations
- Also, please provide details regarding the incorrect scan results for etcd recommendations (CIS Control ID: 2.1 to 2.7)

**Environment** 

Used Latest version of kube-bench, Kubernetes version : 1.18.0

**Anything else you would like to add:**

No

Thank you.

**Comment by lizrice** [comment]
Hi @ankitsrao, please could you attach the output you do get? If you can run again with parameters `-v 3 --logtostderr` that would be even better. 

Are you running on a master or worker node?

**Comment by ankitsrao** [comment]
Hi @lizrice ,

Actually, I would like to add some more details. So basically, the status for these policies appear WARN.
It is mentioned in the documentation that [WARN] means this test needs further attention, for example it is a test that needs to be run manually. So, while for many of the recommendations, that cleared my doubt, but for some I've the below queries:

Just to showcase and example, below are the status of recommendation 1.2.10, 1.2.11, 1.2.12, 1.2.13
[WARN] 1.2.10 Ensure that the admission control plugin EventRateLimit is set (Not Scored)

[PASS] 1.2.11 Ensure that the admission control plugin AlwaysAdmit is not set (Scored)

[WARN] 1.2.12 Ensure that the admission control plugin AlwaysPullImages is set (Not Scored)

[WARN] 1.2.13 Ensure that the admission control plugin SecurityContextDeny is set if PodSecurityPolicy is not used (Not Scored)

So, here the process to fetch the settings is the same, but is it that only becasue, recommedations 1.2.10, 1.2.12, 1.2.13 are marked as "Not Scored" by CIS, the tool is marking then as WARN. Because what I felt here is, if the tool is able to retireve the compliance status for 1.2.11, it should be able to do the same for the remaining three as well.

I could put the analogy for these recommendations only. But I observed that all the recommednations that I have mentioned i.e:

- 1.1.9, 1.1.10, 1.1.20, 1.1.21
- 1.2.1, 1.2.10, 1.2.12, 1.2.13, 1.2.33, 1.2.34, 1.2.35
- 1.3.1
- 4.2.9

 All these have been marked "Not-Scored" by CIS.

So, now it comes down to a generic question that, does the kube-bench tool not scan for the recommendations that are marked "Not Scored" by CIS.

Also, to add, I'm running the tool on my master node.

I've attached the output in a text file with this thread.
[kube-bench.log](https://github.com/aquasecurity/kube-bench/files/5119203/kube-bench.log)

Thank you

**Comment by mozillazg** [comment]
@ankitsrao 

> So, here the process to fetch the settings is the same, but is it that only becasue, recommedations 1.2.10, 1.2.12, 1.2.13 are marked as "Not Scored" by CIS, the tool is marking then as WARN?

No, 1.2.10, 1.2.12, 1.2.13 are marked as WARN because of kube-bench run test failed not only because of they are marked as "Not Scored" by CIS.

> So, now it comes down to a generic question that, does the kube-bench tool not scan for the recommendations that are marked "Not Scored" by CIS.

No, kube-bench try to run test for all recommendations when possible (all tests can be found in https://github.com/aquasecurity/kube-bench/tree/master/cfg/cis-1.5).


The state will be marked as WARN in the below case:

* If the test is Manual（is defined in https://github.com/aquasecurity/kube-bench/tree/master/cfg/cis-1.5 and CIS）, this always generates WARN (because the user has to run it manually)
* If the test is Not Scored, and kube-bench was unable to run the test(run test failed or no test is defined in https://github.com/aquasecurity/kube-bench/tree/master/cfg/cis-1.5）, this generates WARN.
* If the test is Scored, type is empty, and there are no test_items present（is defined in https://github.com/aquasecurity/kube-bench/tree/master/cfg/cis-1.5）, it generates a WARN.

BTW, you can run kube-bench with parameters `-v 3 --logtostderr` to get debug log which include the reason why the recommendation was marked as WARN :

```
kube-bench -v 3 --logtostderr
```

**Comment by ankitsrao** [comment]
Thank you @mozillazg for the info.
Will surely revaildate my results based on these details.
