### ISSUE TITLE
inconsistent results for openshift v3.11 - Kube-bench

### ISSUE THREAD

**Issue by dyapas** [aquasecurity/kube-bench#697]
**What steps did you take and what happened:**
i am running kube-bench tool for Openshiftv3.11 and i see inconsistent result for similar tests.

file: cfg/rh-0.7/master.yaml 

section      - id: 5.2
        text: "Verify the default OpenShift setting for the client-cert-auth argument"
        audit: "/bin/sh -c'/usr/local/bin/master-exec etcd etcd grep ETCD_CLIENT_CERT_AUTH=true /proc/1/environ; grep ETCD_CLIENT_CERT_AUTH /etc/etcd/etcd.conf'"
        tests:
          bin_op: and
          test_items:
            - flag: "Binary file /proc/1/environ matches"
              compare:
                op: has
                value: "Binary file /proc/1/environ matches"
              set: true
            - flag: "ETCD_CLIENT_CERT_AUTH=true"
              compare:
                op: has
                value: "ETCD_CLIENT_CERT_AUTH=true"
              set: true
        remediation: |
          Reset to the OpenShift default configuration.
        scored: true

output when i ran the command individually:
ocpm003 rh-0.7]# /usr/local/bin/master-exec etcd etcd grep ETCD_CLIENT_CERT_AUTH=true /proc/1/environ; grep ETCD_CLIENT_CERT_AUTH /etc/etcd/etcd.conf
Binary file /proc/1/environ matches
ETCD_CLIENT_CERT_AUTH=true

This is flagged as "FAILED"

***********
for section 5.5:
 - id: 5.5
        text: "Verify the OpenShift default configuration for the peer-client-cert-auth"
        audit: "/bin/sh -c '/usr/local/bin/master-exec etcd etcd grep ETCD_PEER_CLIENT_CERT_AUTH=true /proc/1/environ; grep ETCD_PEER_CLIENT_CERT_AUTH /etc/etcd/etcd.conf'"
        tests:
          bin_op: and
          test_items:
            - flag: "Binary file /proc/1/environ matches"
              compare:
                op: has
                value: "Binary file /proc/1/environ matches"
              set: true
            - flag: "ETCD_PEER_CLIENT_CERT_AUTH=true"
              compare:
                op: has
                value: "ETCD_PEER_CLIENT_CERT_AUTH=true"
              set: true
        remediation: |
          Reset to the OpenShift default configuration.
        scored: true
`Output`: 
cpm003 rh-0.7]# /usr/local/bin/master-exec etcd etcd grep ETCD_PEER_CLIENT_CERT_AUTH=true /proc/1/environ; grep ETCD_PEER_CLIENT_CERT_AUTH /etc/etcd/etcd.conf
`Binary file /proc/1/environ matches
ETCD_PEER_CLIENT_CERT_AUTH=true`

This test is "PASS".

Section 5.2 is looking for Binary file /proc/1/environ matches & ETCD_CLIENT_CERT_AUTH=true and the etcd result returned same -- but the test is FAILED

Section 5.5 is looking for Binary file /proc/1/environ matches & ETCD_PEER_CLIENT_CERT_AUTH=true and the etcd result returned same -- but the test is PASSED.

Same issue with section 5.6 also. 

[A clear and concise description of what the bug is, and what commands you ran. If possible please supply logs generated with the `-v 3` parameter.)

**What did you expect to happen:**

**Environment** 

[Please specify the version of kube-bench and Kubernetes]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Comment by yoavrotems** [comment]
This indeed seems very strange, could you add the "-v 3 --include-test-output" logs?

**Comment by atomanonymous** [comment]
i would like to work on this could u guide me through this?

**Comment by yoavrotems** [comment]
Hey we updated the specs and added ocp 4.X support if still having issues please open a new issue and include also the debug logs (-v 3) 
Thank you.
