### ISSUE TITLE
Fails to scan kops created clusters.

### ISSUE THREAD

**Issue by zapman449** [aquasecurity/kube-bench#7]
kops deploys most of the kubernetes binaries inside docker containers.  So the output looks like this:

```
$ ./kube-bench master
[INFO] Using config file: {A PATH}/config.yaml
[WARN] kube-apiserver: command not found on path - version check skipped
[WARN] kube-scheduler: command not found on path - version check skipped
[WARN] kube-controller-manager: command not found on path - version check skipped
[WARN] config file /etc/kubernetes/apiserver does not exist
[WARN] config file /etc/kubernetes/scheduler does not exist
[WARN] config file /etc/kubernetes/controller-manager does not exist
[WARN] config file /etc/kubernetes/config does not exist
[WARN] config file /etc/etcd/etcd.conf does not exist
[WARN] config file /etc/sysconfig/flanneld does not exist
yaml: line 61: did not find expected key
```

Please let me know if I can help with further triage

**Comment by lizrice** [comment]
Thanks @zapman449! Just to be clear, is that {A PATH} a redaction, or literally what's output?

**Comment by lizrice** [comment]
Sorry about this - I think you were the victim of a badly-formatted YAML file that got checked in!  Could you try again please, making sure you have the latest version by re-pulling aquasec/kube-bench:latest and reinstalling before you re-run it? 

I think you will still get warning messages about missing config files (we need to figure out how to handle them being installed to different places and with different names by different tools) but you should at least get some test output

**Comment by zapman449** [comment]
Fair.  I tried again, but this time it's worse:

```
$ ./kube-bench master
wait: error running audit command exit status 1
```

**Comment by lizrice** [comment]
Hi @zapman449 - we now have 
 * a flag for specifying the installation tool e.g. --installation kops 
 * the ability to specify in config.yaml the binaries and config files as used by different installation tools. 

However, we don't know whether we have the right config & binary locations for kops, so if you have a moment to give it a whirl that would be wonderful! 

There's also a --verbose flag for getting more information in the event of errors

**Comment by zapman449** [comment]
Thank you. I was able to generate a report but with several warnings/caveats.

```
$ ./kube-bench master --installation kops
apiserver: command not found in path, error: exec: "apiserver": executable file not found in $PATH
scheduler: command not found in path, error: exec: "scheduler": executable file not found in $PATH
controller-manager: command not found in path, error: exec: "controller-manager": executable file not found in $PATH
failed to run: [ps -C apiserver,scheduler,controller-manager -o cmd --no-headers], error: exit status 1
apiserver: command not found on path - version check skipped, error: exec: "apiserver": executable file not found in $PATH
failed to run:[apiserver --version], error: exec: "apiserver": executable file not found in $PATH

failed to run: ps -ef | grep etcd | grep -v grep | grep -o data-dir=.* | cut -d= -f2 | xargs stat -c %a
failed command:[grep -o data-dir=.*], error: exit status 1
failed to run: ps -ef | grep etcd | grep -v grep | grep -o data-dir=.* | cut -d= -f2 | xargs stat -c %a
failed command:[xargs stat -c %a], error: exit status 123
```

**Comment by zapman449** [comment]
I believe this issue can be closed however...

**Comment by lizrice** [comment]
Thanks - I'm hoping this means you got useful output as well as the warnings :-) 

The first few errors look like they are covered by #20 , and I'm going to raise another issue about the other output errors.

**Comment by zapman449** [comment]
Yes... I got the report.  More failures than I'm comfortable sharing... ;-)
