### ISSUE TITLE
Segmentation violation 

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/kube-bench#70]
Got segmentation violation when running kube-bench as root.
centos:7
Kubernetes 1.8.1

Note that I am only getting this when running as root. It does work when running as non-root user.

[root@ec2-user]# ./kube-bench master
[WARN] Missing config file for flanneld
[WARN] Missing config file for kubernetes
[WARN] Missing config file for apiserver
[WARN] Missing config file for scheduler
[WARN] Missing config file for controllermanager
[WARN] Missing config file for etcd
[WARN] Missing config file for flanneld
[WARN] Missing config file for kubernetes
[WARN] Kubernetes version check skipped, with error getting kubectl version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8153c5]

goroutine 1 [running]:
github.com/aquasecurity/kube-bench/cmd.runChecks(0x90268a, 0x6)
	/go/src/github.com/aquasecurity/kube-bench/cmd/common.go:65 +0x285
github.com/aquasecurity/kube-bench/cmd.glob..func2(0xb40400, 0xb642b0, 0x0, 0x0)
	/go/src/github.com/aquasecurity/kube-bench/cmd/master.go:28 +0x36
github.com/spf13/cobra.(*Command).execute(0xb40400, 0xb642b0, 0x0, 0x0, 0xb40400, 0xb642b0)
	/go/src/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/spf13/cobra.(*Command).ExecuteC(0xb40840, 0x865c00, 0x0, 0x0)
	/go/src/github.com/spf13/cobra/command.go:783 +0x349
github.com/spf13/cobra.(*Command).Execute(0xb40840, 0xb642b0, 0x0)
	/go/src/github.com/spf13/cobra/command.go:736 +0x2b
github.com/aquasecurity/kube-bench/cmd.Execute()
	/go/src/github.com/aquasecurity/kube-bench/cmd/root.go:53 +0x9b
main.main()
	/go/src/github.com/aquasecurity/kube-bench/main.go:22 +0x20

**Comment by ttousai** [comment]
@jerbia can you please share the revision of kube-bench you are running?

**Comment by lizrice** [comment]
I think this should be fixed by #69

**Comment by lizrice** [comment]
I'm going to close, but please reopen if you still see it
