### ISSUE TITLE
kube-bench should detect node type automatically

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#72]
We should be able to automatically determine the tests to run on a node: 

* run the node tests on all nodes
* run the master tests if any of kube-api-server, kube-controller-manager or kube-scheduler are running (including checking alternative names for these components on different platforms, as specified in the config)
* ~~run the federation tests if any of federation-apiserver or federation-controller-manager are running~~

**Comment by nishitm** [comment]
@lizrice any progress on this issue? Even I am curious about these features.

**Comment by lizrice** [comment]
No need for federation any more
