### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by mrBingDev** [aquasecurity/kube-bench#721]
Add LICENSE in the Documentation(README.md)

**Comment by mrBingDev** [comment]
Can I work on this?

**Comment by lizrice** [comment]
I'm generally not a fan of this because it duplicates what's already defined in the LICENSE file (which GitHub picks up in the UI as well). That said, we inconsistently do include this in some other READMEs, so we are deciding whether we want to standardize one way or another.

**Comment by lizrice** [comment]
Thanks for the idea, but we have concluded that we don't want to duplicate this info in the README.
