### ISSUE TITLE
Add —exit-code 

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#723]
At the moment, if kube-bench runs successfully, it exits with a zero exit code even if there are failed tests. Let’s add a `—exit-code` option, much like already exists for Trivy. If `—exit-code` is specified, and any of the tests result in FAIL, exit the kube-bench executable with the value specified by `exit-code`

See discussion #566

**Comment by malathit** [comment]
@lizrice I am a developer with some experience on kubernetes. Recently, I saw your lecture in kubecon 2020 and it was wonderful. I would like to work on this and get this done in a week or two max. Can you please assign this issue so that I can work on this if resolving this is not urgent?

**Comment by Wicked7000** [comment]
As there wasn't an update on this Issue for a couple of days I decided to go ahead and make the set of changes, please let me know if they are acceptable or if anything else is needed. (Or if someone else is going to pick up the changes)
Thanks!
