### ISSUE TITLE
Test 1.1.19 Failed 

### ISSUE THREAD

**Issue by fenixam** [aquasecurity/kube-bench#726]
**What steps did you take and what happened:**
kube-bench master -c 1.1.19 -v 3

[A clear and concise description of what the bug is, and what commands you ran. If possible please supply logs generated with the `-v 3` parameter.)
[FAIL] 1.1.19 Ensure that the Kubernetes PKI directory and file ownership is set to root:root (Automated)
**What did you expect to happen:**

PASS
 - Output:
 "root:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\n"

find /etc/kubernetes/pki/ | xargs stat -c %U:%G returns:
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root
root:root

**Environment** 
Linux version 5.4.0-1024-aws (buildd@lgw01-amd64-035) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2))
Kubernetes 1.19

[Please specify the version of kube-bench and Kubernetes]
kube-bench_0.4.0_linux_amd64.deb
**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

I1007 16:49:56.444719  131465 check.go:267] Command "find /etc/kubernetes/pki/ | xargs stat -c %U:%G"
 - Output:
 "root:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\nroot:root\n"
I1007 16:49:56.444785  131465 check.go:202] 1 tests
I1007 16:49:56.444803  131465 test.go:129] In flagTestItem.findValue , match false, s root:root, t.Flag root root
I1007 16:49:56.445297  131465 test.go:198] flagFound false
I1007 16:49:56.445732  131465 test.go:147] In pathTestItem.findValue
I1007 16:49:56.445764  131465 test.go:198] flagFound false
I1007 16:49:56.445775  131465 check.go:245] Returning from execute on tests: finalOutput &check.testOutput{testResult:false, flagFound:false, actualResult:"", ExpectedResult:"'' is present"}
I1007 16:49:56.445803  131465 check.go:173] Check.ID: 1.1.19 Command: "" TestResult: false State: "FAIL"
[INFO] 1 Master Node Security Configuration
[INFO] 1.1 Master Node Configuration Files
[FAIL] 1.1.19 Ensure that the Kubernetes PKI directory and file ownership is set to root:root (Automated)

== Remediations ==
1.1.19 Run the below command (based on the file location on your system) on the master node.
For example,
chown -R root:root /etc/kubernetes/pki/

**Comment by lizrice** [comment]
Thank you for the logs. From this line I'm pretty sure I can see the problem is a simple typo: 

```
I1007 16:49:56.444803 131465 test.go:129] In flagTestItem.findValue , match false, s root:root, t.Flag root root
```

The test configuration for 1.1.19 in cis-1.6 is looking for `root root` (with a space) but it should be looking for `root:root`(with a colon)
