### ISSUE TITLE
Suggest revising test 1.3.6 to ensure RotateKubeletServerCertificate is not found or not false

### ISSUE THREAD

**Issue by jeffnai-github** [aquasecurity/kube-bench#743]
By default, kube-apiserver sets [RotateKubeletServerCertificate=true](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options) In test 1.3.6, instead of looking for "RotateKubeletServerCertificate=true", I'd like to suggest the following:

      - id: 1.3.6
        text: "Ensure that the RotateKubeletServerCertificate argument is set to true (Automated)"
        audit: "/bin/ps -ef | grep $controllermanagerbin | grep -v grep"
        tests:
          bin_op: or
          test_items:
            - flag: "--feature-gates"
              compare:
                op: nothave
                value: "RotateKubeletServerCertificate=false"
            - flag: "--feature-gates"
              set: false

**Comment by mozillazg** [comment]
Yes, you are right.

From https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

<img width="601" alt="image" src="https://user-images.githubusercontent.com/485054/98821429-8287c000-246a-11eb-9bc0-f8432d5b6913.png">

From https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
<img width="752" alt="image" src="https://user-images.githubusercontent.com/485054/98821476-93d0cc80-246a-11eb-86b6-796efe89ec72.png">

From CIS:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/485054/98821597-ba8f0300-246a-11eb-9652-0adb1ed572fc.png">
