### ISSUE TITLE
The job task cannot be run simultaneously on each master node

### ISSUE THREAD

**Issue by zhaocheng173** [aquasecurity/kube-bench#744]
I currently have three master nodes. The question I want to ask is that I am running with job-master, but I can only see jobs running on my M1-m2 node. Shouldn't it be running on all master nodes at the same time
```
[root@m1 ~]# kubectl get node
NAME    STATUS   ROLES    AGE     VERSION
m1      Ready    master   2d16h   v1.18.8
m1-m2   Ready    master   2d15h   v1.18.8
m1-m3   Ready    master   2d15h   v1.18.8
m2      Ready    worker   2d16h   v1.18.8
```
Only one such task was generated
```
[root@m1 ~]# kubectl get po -A -o wide|grep bench
kube-system         kube-bench-master-hfllw                       0/1     Completed   0          14s     172.31.155.197   m1-m2   <none>           <none>

```
Now my nodes are no stain, or is this check master job if I have a lot of the master node, I can only run so can just have a job, or do I have to on each master nodes are marked nodeName to just go, I have some doubts, the trouble you, can you tell me the principle, or can only run a job at the master
```
[root@m1 ~]# kubectl describe no |egrep "Roles|Taints"
Roles:              master
Taints:             <none>
Roles:              master
Taints:             <none>
Roles:              master
Taints:             <none>
Roles:              worker
Taints:             <none>

```

**Comment by mozillazg** [comment]
> The question I want to ask is that I am running with job-master, but I can only see jobs running on my M1-m2 node

This is expected and that is how k8s job work: https://kubernetes.io/docs/concepts/workloads/controllers/job/

**Comment by zhaocheng173** [comment]
So in this case, if I have three master nodes, do I need to tag each node and run three job-master jobs at the same time to check the benchmark for the master node, or do I just run one job at the master

**Comment by mozillazg** [comment]
@zhaocheng173 

If all of your master nodes have same configurations you can just run one job, otherwise run multiple jobs for these nodes is a better idea.

**Comment by zhaocheng173** [comment]
thanks
