### ISSUE TITLE
Latest installation fails

### ISSUE THREAD

**Issue by vdboor** [aquasecurity/kube-bench#78]
Running the installation doesn't seem to do much. It only generates an empty `cfg` folder:

```
$ docker run --rm -v `pwd`:/host aquasec/kube-bench:latest
Unable to find image 'aquasec/kube-bench:latest' locally
latest: Pulling from aquasec/kube-bench
b56ae66c2937: Pull complete 
1963e5f576aa: Pull complete 
ee1b6cb1f583: Pull complete 
729afdc9bc53: Pull complete 
Digest: sha256:896995e04785b95fe45de7e6207f68b7f207a461d169e27db8c8ebad2f2632d0
Status: Downloaded newer image for aquasec/kube-bench:latest
cp: can't stat './kube-bench/cfg/*': Not a directory
===============================================
kube-bench is now installed on your host       
Run ./kube-bench to perform a security check   
===============================================
cp: can't stat './kube-bench/kube-bench': Not a directory

$ tree
.
└── cfg

1 directory, 0 files
```

**Comment by vendrov** [comment]
Where can we find older images?

**Comment by ttousai** [comment]
@vdboor as a workaround try applying the change at here https://github.com/aquasecurity/kube-bench/pull/77/commits/882fa5dd16ecced362242c94e932752bc63846d0 to entrypoint.sh in your checkout, the build an image from the Dockerfile included.

It is supposed to be merged into master. I will look into it and see what is going on.

**Comment by jaycoon** [comment]
Any update on the merge? I've been recommending kube-bench, though need to mention the workaround as well since we have seen the same issue.

**Comment by lizrice** [comment]
It's in master but we haven't done a release since that change. I have just made a new release that should include it.

**Comment by jaycoon** [comment]
Awesome, thanks! I see the docker image is building now.
