### ISSUE TITLE
Some changes are reverted after rename master branch to main

### ISSUE THREAD

**Issue by mozillazg** [aquasecurity/kube-bench#780]
These changes are reverted:

* https://github.com/aquasecurity/kube-bench/pull/755
* https://github.com/aquasecurity/kube-bench/pull/767
* https://github.com/aquasecurity/kube-bench/commit/6bbbd5305458168224a41d118d22750abd6314ba
* others I don't know...

**Comment by lizrice** [comment]
Sorry about this! My fault. We are working on restoring all these...

**Comment by yoavrotems** [comment]
Hey we restored all changes, if you notice something we missed please let us know @mozillazg 
Thanks :)
