### ISSUE TITLE
use glide or godep for dependencies

### ISSUE THREAD

**Issue by jaxxstorm** [aquasecurity/kube-bench#79]
I can't see any method on this repo for adding and installing depedencies at the moment, so building the app is more difficult than it needs to be.

Simply doing `glide init` and `glide i` helped, but wanted to get an idea of what you guys wanted before sending a PR

**Comment by lizrice** [comment]
You're right, this really should be addressed. We use a mixture of things internally, and Glide seems fine, so I'd be happy to take a PR with that. Thanks!

**Comment by jaxxstorm** [comment]
Added #81
