### ISSUE TITLE
use goreleaser for final builds

### ISSUE THREAD

**Issue by jaxxstorm** [aquasecurity/kube-bench#80]
I've found goreleaser really improves the release process for golang tools: 

https://goreleaser.com/

This way, there isn't a reliance on the Makefile and the docker installation method. Gorelease can build docker images as well in an automated way. If there's any interest here, I'm happy to send a PR.

**Comment by lizrice** [comment]
Thanks, this is new to me and from a quick read of the docs it looks really neat. I'd be very happy to see a PR for adding it here!

**Comment by jaxxstorm** [comment]
Awesome! Need to figure out #79 first

**Comment by marcellodesales** [comment]
@lizrice Since #81 has been merged, could you guys release the static binaries for download? I'm trying to automate steps to include kube-bench into clusters using our CLIs. We use linux, so I'm waiting on a release instead of building locally...

`goreleaser` looks so good!

**Comment by jaxxstorm** [comment]
@marcellodesales I have #83 open for this, hopefully they'll merge it soon

**Comment by lizrice** [comment]
Hi @jaxxstorm, it's very possible I've misunderstood, but should this have created a binary and added it to the release here on GitHub when I tagged a new build?

**Comment by jaxxstorm** [comment]
@lizrice yes it should, according to the travis build, the docker build step seems to be failing:

https://travis-ci.org/aquasecurity/kube-bench/jobs/335069990#L811 which is preventing the release from succeeding.

**Comment by lizrice** [comment]
...and we get stuck at the Docker push stage due to a lack of credentials :-(   Any idea how we configure this in goreleaser? A quick google didn't immediately enlighten me...

Alternatively we could have goreleaser just build the binaries, and have the Docker Hub automated build make the image - wdyt @jaxxstorm?

**Comment by jaxxstorm** [comment]
That works, but you can set the docker credentials as a secure variable like so:

https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry

Would simply need to add a `docker login` command to the `.travis.yml` file in the after_success section.

Have a look here for the way to specify the secure variables:
https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml
https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables

Let me know which way you want to go, and I can remove the docker section from the goreleaser config

**Comment by lizrice** [comment]
I'm inclined to go the easy route! Let's just use the Docker automated build for the image. 

And thank YOU for your patience and your contributions! I agree, it's going to be neat to have the binaries created automatically. We're almost there...one...final..push (I hope!)

**Comment by jaxxstorm** [comment]
Ready to go @lizrice

**Comment by lizrice** [comment]
Woohoo, it works - thank you @jaxxstorm!
