### ISSUE TITLE
String matching against node-config.yaml appears broken

### ISSUE THREAD

**Issue by cohoe** [aquasecurity/kube-bench#806]
**What steps did you take and what happened:**

I am benchmarking an ocp3.11 cluster using rh-0.7-node. Several benchmarks continue to fail after remediations have been applied. For example, 7.3 ('authorization-mode' is not present OR 'authorization-mode' has 'Webhook') and 7.6 ('streaming-connection-idle-timeout' is not present OR '5m' is not present). Both benchmarks fail even after the remediation has been applied. 

I enabled debug logging in the job and made absolutely sure the job was scheduling on appropriate nodes. From the debug output it seems that kube-bench is successfully running the audit command but not parsing its output correctly.

```
I0121 16:26:41.813816    2659 check.go:292] Command "grep -A1 authorization-mode /etc/origin/node/node-config.yaml"
 - Output:
 "  authorization-mode:\n  - Webhook\n"
I0121 16:26:41.813840    2659 check.go:215] 2 tests
I0121 16:26:41.813883    2659 test.go:148] In flagTestItem.findValue authorization-mode, match true, s   authorization-mode:
  - Webhook, t.Flag authorization-mode
I0121 16:26:41.813898    2659 test.go:235] found true
I0121 16:26:41.813926    2659 test.go:148] In flagTestItem.findValue authorization-mode, match true, s   authorization-mode:
  - Webhook, t.Flag authorization-mode
I0121 16:26:41.813935    2659 test.go:235] found true
I0121 16:26:41.813951    2659 check.go:270] Returning from execute on tests: finalOutput &check.testOutput{testResult:false, flagFound:false, actualResult:"  authorization-mode:\n  - Webhook", ExpectedResult:"'authorization-mode' is not present OR 'authorization-mode' has 'Webhook'"}
I0121 16:26:41.813981    2659 check.go:178] Check.ID: 7.3 Command: "" TestResult: false State: "FAIL" 
...
...
I0121 16:26:41.824774    2659 check.go:292] Command "grep -A1 streaming-connection-idle-timeout /etc/origin/node/node-config.yaml"
 - Output:
 "  streaming-connection-idle-timeout:\n  - \"5m\"\n"
I0121 16:26:41.824795    2659 check.go:215] 2 tests
I0121 16:26:41.825096    2659 test.go:148] In flagTestItem.findValue streaming-connection-idle-timeout, match true, s   streaming-connection-idle-timeout:
  - "5m", t.Flag streaming-connection-idle-timeout
I0121 16:26:41.825110    2659 test.go:235] found true
I0121 16:26:41.825151    2659 test.go:148] In flagTestItem.findValue ", match true, s   streaming-connection-idle-timeout:
  - "5m", t.Flag 5m
I0121 16:26:41.825160    2659 test.go:235] found true
I0121 16:26:41.825166    2659 check.go:270] Returning from execute on tests: finalOutput &check.testOutput{testResult:false, flagFound:false, actualResult:"  streaming-connection-idle-timeout:\n  - \"5m\"", ExpectedResult:"'streaming-connection-idle-timeout' is not present OR '5m' is not present"}
I0121 16:26:41.825179    2659 check.go:178] Check.ID: 7.6 Command: "" TestResult: false State: "FAIL" 
```

**What did you expect to happen:**

Pre-remediation: The benchmarks fail and give remediation instructions.
Post-remediation: The benchmarks pass.

**Environment** 

Kube-Bench: v.0.5.0
Kubernetes: v1.11.0+d4cacc0
OpenShift: v3.11.0+1cd89d4-542
OpenShift Distribution: OKD

**Anything else you would like to add:**

I find it odd that in the final log for each check the command is an empty string. Might be a red herring though.
```
I0121 16:26:41.813981    2659 check.go:178] Check.ID: 7.3 Command: "" TestResult: false State: "FAIL" 
I0121 16:26:41.825179    2659 check.go:178] Check.ID: 7.6 Command: "" TestResult: false State: "FAIL" 
```

**Comment by yoavrotems** [comment]
Hey, thank you for this issue.
There are multiple issue hidden here the first one is misleading logs, this is what took me a while to figure out how to improve it in order to better understanding why tests or failing or why kube-bench is misbehaving.
This PR https://github.com/aquasecurity/kube-bench/pull/822 will solve this issue. 
Now when running it with better logs we can see the issue here is that "audit" is not expecting yaml list output, aka
```
kubeletArgs:
  - First value
  - Second value
  
 ```
For this kind of value there is audit_config, which using jsonpath and could handle yaml and json formats, I working on updating the rh-0.7 yaml to better use the kube-bench engine and should make a PR in the very few days in the meanwhile I opened a issue https://github.com/aquasecurity/kube-bench/issues/824
