### ISSUE TITLE
unable to determine benchmark version: config file is missing 'version_mapping' section

### ISSUE THREAD

**Issue by hryamzik** [aquasecurity/kube-bench#835]
**Overview**

[A clear and concise description of what the bug is] 

**How did you run kube-bench?**

I'm trying to get kube-bench running on EKS node. I have two points of reference here, [aws docs](https://www.eksworkshop.com/intermediate/300_cis_eks_benchmark/ssh-into-node/) and [README](https://github.com/aquasecurity/kube-bench#download-and-install-binaries).

1. Installation option one:

```
KUBEBENCH_URL=$(curl -s https://api.github.com/repos/aquasecurity/kube-bench/releases/latest | jq -r '.assets[] | select(.name | contains("amd64.rpm")) | .browser_download_url')
yum install -y $KUBEBENCH_URL
kube-bench --benchmark eks-1.0
```

2. Installation option two:

```
curl -L $(curl -s https://api.github.com/repos/aquasecurity/kube-bench/releases/latest | jq -r '.assets[] | select(.name | contains("amd64.tar.gz")) | .browser_download_url') -o kube-bench_linux_amd64.tar.gz
tar -xvf kube-bench_linux_amd64.tar.gz
./kube-bench --config-dir `pwd`/cfg --config `pwd`/cfg/config.yaml
```

OK, config files are not there. Current release is `0.5.0`. That seem to be the right way:

```
./kube-bench --config-dir `pwd`/cfg/eks-1.0 --config `pwd`/cfg/eks-1.0/config.yaml
```

**What happened?**

Result:

```
unable to determine benchmark version: config file is missing 'version_mapping' section
```

**What did you expect to happen:**

Actual test results! I got them in a container-based approach but wanted to get at a bit lower level.

**Environment** 

`0.5.0`

```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else you would like to add:**

Might be related to #613

**Comment by jorgegutierrez2077** [comment]
Man I feel your pain, to make it work you need to download the config files on https://github.com/aquasecurity/kube-bench/tree/main/cfg 
and place them under /etc/kube-bench/cfg/ once you have that the checks actually work

That is vaguely described on https://github.com/aquasecurity/kube-bench#installation:
_install the latest binaries from the Releases page, though **please note that you also need to download the config and test files from the cfg directory**. See Download and Install binaries for details._

**Comment by hryamzik** [comment]
@jorgegutierrez2077 makes sense, ty. I've downloaded just the `config.yaml` (`wget -O cfg/config.yaml https://raw.githubusercontent.com/aquasecurity/kube-bench/main/cfg/config.yaml`) and seem to get it working, other configs are there out of the box:

```
# find cfg/
cfg/
cfg/aks-1.0
cfg/aks-1.0/config.yaml
cfg/aks-1.0/controlplane.yaml
cfg/aks-1.0/managedservices.yaml
cfg/aks-1.0/master.yaml
cfg/aks-1.0/node.yaml
cfg/aks-1.0/policies.yaml
cfg/cis-1.5
cfg/cis-1.5/config.yaml
cfg/cis-1.5/controlplane.yaml
cfg/cis-1.5/etcd.yaml
cfg/cis-1.5/master.yaml
cfg/cis-1.5/node.yaml
cfg/cis-1.5/policies.yaml
cfg/cis-1.6
cfg/cis-1.6/config.yaml
cfg/cis-1.6/controlplane.yaml
cfg/cis-1.6/etcd.yaml
cfg/cis-1.6/master.yaml
cfg/cis-1.6/node.yaml
cfg/cis-1.6/policies.yaml
cfg/eks-1.0
cfg/eks-1.0/config.yaml
cfg/eks-1.0/controlplane.yaml
cfg/eks-1.0/managedservices.yaml
cfg/eks-1.0/master.yaml
cfg/eks-1.0/node.yaml
cfg/eks-1.0/policies.yaml
cfg/gke-1.0
cfg/gke-1.0/config.yaml
cfg/gke-1.0/controlplane.yaml
cfg/gke-1.0/etcd.yaml
cfg/gke-1.0/managedservices.yaml
cfg/gke-1.0/master.yaml
cfg/gke-1.0/node.yaml
cfg/gke-1.0/policies.yaml
cfg/rh-0.7
cfg/rh-0.7/config.yaml
cfg/rh-0.7/master.yaml
cfg/rh-0.7/node.yaml
```

**Comment by mozillazg** [comment]
@hryamzik This issue has been fixed via https://github.com/aquasecurity/kube-bench/pull/813, but there isn't a new release for this fix yet.

**Comment by yoavrotems** [comment]
Thanks @mozillazg is correct and now when 0.6.0 is released this should not be an issue anymore.

**Comment by ak2766** [comment]
Is this a regression and should I open a new bug?

I've just downloaded version 0.9.2 (i.e. latest) and I'm getting this error as well.

```
$ > pwd
/opt/fossapps/kube-bench-v0.9.2

$ > tree -L 2 .
.
├── cfg
│   ├── ack-1.0
│   ├── aks-1.0
│   ├── cis-1.20
│   ├── cis-1.23
│   ├── cis-1.24
│   ├── cis-1.24-microk8s
│   ├── cis-1.5
│   ├── cis-1.6
│   ├── cis-1.6-k3s
│   ├── cis-1.7
│   ├── cis-1.8
│   ├── cis-1.9
│   ├── config.yaml
│   ├── eks-1.0.1
│   ├── eks-1.1.0
│   ├── eks-1.2.0
│   ├── eks-stig-kubernetes-v1r6
│   ├── gke-1.0
│   ├── gke-1.2.0
│   ├── gke-1.6.0
│   ├── k3s-cis-1.23
│   ├── k3s-cis-1.24
│   ├── k3s-cis-1.7
│   ├── k3s-cis-1.8
│   ├── rh-0.7
│   ├── rh-1.0
│   ├── rke2-cis-1.23
│   ├── rke2-cis-1.24
│   ├── rke2-cis-1.7
│   ├── rke-cis-1.23
│   ├── rke-cis-1.24
│   ├── rke-cis-1.7
│   └── tkgi-1.2.53
└── kube-bench

$ > ./kube-bench version
0.9.2

$ > ./kube-bench

unable to determine benchmark version: config file is missing 'version_mapping' section
```

**Comment by ak2766** [comment]
As an FYI, I was able to get it to work by:

```sudo ln -s /opt/fossapps/kube-bench-v0.9.2 /etc/kube-bench```

But why force this?  The application ought to check not just `/etc/kube-bench` but also the directory where the `kube-bench` binary is running from - IMHO!

**Comment by afdesk** [comment]
@ak2766 thanks for the report
I'll take a look

**Comment by afdesk** [comment]
oh, sorry, I missed. 
you're right, a default config folder is `/etc/kube-bench` by design
you can redefine it:
```sh
$ ./kube-bench --config-dir ./cfg
```
