### ISSUE TITLE
ETCD ownership related checks will always failed when running in container

### ISSUE THREAD

**Issue by mozillazg** [aquasecurity/kube-bench#842]
**Overview**

ETCD ownership related checks will always failed when running in container. Because of there is no user named `etcd` in container.

Maybe we should mount the `/etc/passwd` and `/etc/group` from host when running in container (need update README.md and job-master.yaml)?

**How did you run kube-bench?**

```
kubectl apply -f job-master.yaml 
```

**What happened?**

ETCD ownership related checks always failed.

https://github.com/aquasecurity/kube-bench/blob/50fce51da7f231b02668af4a4bb34bf6dbdf0e04/cfg/cis-1.6/master.yaml#L158-L164

**What did you expect to happen:**

Not failed when the ownership of ETCD data-dir is `etcd:etcd`.

**Environment** 

[What is your version of kube-bench? (run `kube-bench version`)]

v0.5.0

**Comment by yoavrotems** [comment]
Hey @mozillazg thanks for informing us about this issue, currently I'm working on different issues but I will mark it as good first issue and help wanted
