### ISSUE TITLE
Not clear on 4.6 Verify the scheduler pod specification file ownership set by OpenShift

### ISSUE THREAD

**Issue by adshafqat** [aquasecurity/kube-bench#843]
Hi,

We are running kube-bench v3 tests on OpenShift 3.11 cluster and some of the tests are failing with no clear explanation

For example
4.6 Verify the scheduler pod specification file ownership set by OpenShift

Test is suggesting to set the ownership of  /etc/origin/node/pods/controller.yaml file to root:root

The ownership is already set to root, an idea why this test is failing? Is this due to a bug or I am missing something obvious.

[root@dvraosmsw01 ~]# ls -lrt /etc/origin/node/pods/
total 12
-rw-------. 1 root root 1357 Nov 27 18:33 etcd.yaml
-rw-------. 1 root root 1787 Nov 27 18:39 apiserver.yaml
-rw-------. 1 root root 1888 Nov 27 18:39 controller.yaml

**Comment by yoavrotems** [comment]
Hey sorry about the late response but this is what we worked on! 
All is updated and also added ocp 4.X tests 
I'm closing this issue, but if it keeps failing, please open a new issue and include the -v 3 logs and also the needed information about the files, if its the file permissions from stat output or the file content, this way we would have a better indication on where is the problem if it's still a problem of course.
