### ISSUE TITLE
3.7 Manage certificate rotation is looking at wrong OpenShift config file

### ISSUE THREAD

**Issue by adshafqat** [aquasecurity/kube-bench#845]
Hi,
We are running kube-bench v3 tests in OpenShift 3.11. Below test is failing because RotateKubeletClientCertificate value is not set in master-config.yaml file. In OpenShift 3.11, instead of master-config.yaml, this value is configured in /etc/origin/node/node-config.yaml file both on Master and worker nodes.

     - id: 3.7
        text: "Manage certificate rotation"
        audit: "grep -B3 RotateKubeletServerCertificate=true /etc/origin/master/master-config.yaml"

Test scripts should be updated to include to check this value in /etc/origin/node/node-config.yaml file.

**Comment by yoavrotems** [comment]
Hey first thing we updated ocp 3.11 config (rh-0.7) and secondly created new config for ocp 4.X. 
Both are based on redhat hardening guide and we try to stay as close to the spec as possible. 
And I think that this test is also is checked in node segment too in test 7.14 no?

**Comment by yoavrotems** [comment]
Ping @adshafqat

**Comment by yoavrotems** [comment]
Because we updated ocp3 and added ocp4 I assume this problem is solved. 
If after updating kube-bench it is still an issue please let us know
