### ISSUE TITLE
gke - no tests seem to be run under 'managedservices' section

### ISSUE THREAD

**Issue by jakubpawlowski** [aquasecurity/kube-bench#848]
**Overview**

No tests seem to be run under 'managedservices' section. Everything is marked as 'WARN' (meaning manual run required). 

**How did you run kube-bench?**

Using job-gke.yaml

**What did you expect to happen:**

At least some of the tests are run by kube-bench

**Environment** 

kube-bench 0.5

gke - 1.18

**Comment by yoavrotems** [comment]
Hey you are correct, this is no bug. 
Test mark as manual are requiring *manual* user intervention, there are few cases for this situation: for example something that need to be set in the organization level and will be different from organization to organization, other example is when the output could not be predicted - `make sure all group member should be in this group` we can't know upfront which users should be in this specific group, we can know when its default users such as root or ectd. 
We are going to update the gke spec very soon, if you see a specific test that you don't get why its "manual" or you have a idea about how to make it automated you are welcome to reach out to us by opening a specific issue for this test. 
Thank you in advance
