### ISSUE TITLE
GKE CIS 4.2.1, 4.2.2 and 4.2.3 False Positives

### ISSUE THREAD

**Issue by Red-Five** [aquasecurity/kube-bench#852]
Reporting possible false positives on GKE CIS 4.2.1, 4.2.3 and 4.3.3.
Running the kube-bench/job-gke.yaml against a Standard GKE Starter cluster (v1.18.15-gke.1501)

Results
[FAIL] 4.2.1 Ensure that the --anonymous-auth argument is set to false (Scored)
[FAIL] 4.2.2 Ensure that the --authorization-mode argument is not set to AlwaysAllow (Scored)
[FAIL] 4.2.3 Ensure that the --client-ca-file argument is set as appropriate (Scored)

Upon investigation, the corresponding kube-config.yaml's on each worker node cluster did already have the settings
specified in the remediation sections of the CIS GKE benchmark pdf.

![image](https://user-images.githubusercontent.com/25078066/112196216-30f1fd80-8be1-11eb-9a43-126a5c5b8755.png)

The tests should have passed and are expected to pass as per Google documentation https://cloud.google.com/kubernetes-engine/docs/concepts/cis-benchmarks#status

**Comment by Red-Five** [comment]
Look like this is a duplicate (or at least a subset) of https://github.com/aquasecurity/kube-bench/issues/802

**Comment by Red-Five** [comment]
I'm not at all familiar with how this app works so below comments might be way off base :-) 

A possibility is that this check
![image](https://user-images.githubusercontent.com/25078066/112215246-871d6b80-8bf6-11eb-8aba-57b1900f8546.png)
 
is passing the audit_config test and failing the audit test.

Also checking for path .authentication.anonymous.enabled in the audit test doesn't seem correct, since that is only applicable for the audit_config test.

Does this correctly differentiate between checking for the --anonymous-auth flag in the audit test case and checking for .authentication.anonymous.enabled in the audit_config test case?

Does the test case use an OR operator so that it passes if either the audit or audit_config test cases passes?

**Comment by Red-Five** [comment]
Also this document https://github.com/aquasecurity/kube-bench/blob/main/docs/README.md#configuration-and-variables
doesn't mention the use of the audit_config field or how it would behave when combined with an audit field.

**Comment by yoavrotems** [comment]
Hey first thing sorry for the late response,
Secondly about the audit_config and audit, only when audit fails it will proceed to audit_config,  so it will behave as OR basically yes.
About the tests failing it could be because it checks maybe different configs then the one node is using, it shouldn't do so, but it could explain why test is fail while config has the correct values. 
If you will join the debug information (-v 3 ) we could get a better understanding of what happened. 
Make sure to update the repo first because we did some bug fix lately and new version release 
Oh and also I want to update the gke spec we have to compliance with 1.1.0 so please ping me when you have more information because it could be vary valuable information before adding new spec

**Comment by yoavrotems** [comment]
Hey I just tested it on my env for updating the yaml and those tests seems to be fine. 
I'm closing this issue if you still having false positives please reopen it with the logs attached.

**Comment by THordeq** [comment]
Hello everyone, 
We have the same issue when we run this job `job-gke.yaml` into our cluster. 

Specs:
- Cluster version:  1.18.17-gke.100
- 
![secu](https://user-images.githubusercontent.com/11784930/118651495-e8704e00-b7e5-11eb-9943-76855693368e.png)

Commands run: 

```
kube-bench node --benchmark gke-1.0
kube-bench --benchmark gke-1.0 run --targets node
kube-bench --benchmark cis-1.5 run --targets node
kube-bench --benchmark cis-1.6 run --targets node
```

When we look about kubelet config on nodes, we have: 

```

   "kubeletconfig":{
      "staticPodPath":"/etc/kubernetes/manifests",
      "syncFrequency":"1m0s",
      "fileCheckFrequency":"20s",
      "httpCheckFrequency":"20s",
      "address":"0.0.0.0",
      "port":10250,
      "readOnlyPort":10255,
      "serverTLSBootstrap":true,
      "authentication":{
         "x509":{
            "clientCAFile":"/etc/srv/kubernetes/pki/ca-certificates.crt"
         },
         "webhook":{
            "enabled":true,
            "cacheTTL":"2m0s"
         },
         "anonymous":{
            "enabled":false
         }
      },
      "authorization":{
         "mode":"Webhook",
         "webhook":{
            "cacheAuthorizedTTL":"5m0s",
            "cacheUnauthorizedTTL":"30s"
         }
      },
```

And the ouput :

```
[INFO] 4.2 Kubelet
[FAIL] 4.2.1 Ensure that the anonymous-auth argument is set to false (Scored)
[FAIL] 4.2.2 Ensure that the --authorization-mode argument is not set to AlwaysAllow (Scored)
[FAIL] 4.2.3 Ensure that the --client-ca-file argument is set as appropriate (Scored)
[PASS] 4.2.4 Ensure that the --read-only-port argument is set to 0 (Scored)
[PASS] 4.2.5 Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Scored)
[FAIL] 4.2.6 Ensure that the --protect-kernel-defaults argument is set to true (Scored)
[PASS] 4.2.7 Ensure that the --make-iptables-util-chains argument is set to true (Scored)
[PASS] 4.2.8 Ensure that the --hostname-override argument is not set (Not Scored)
[WARN] 4.2.9 Ensure that the --event-qps argument is set to 0 or a level which ensures appropriate event capture (Not Scored)
[FAIL] 4.2.10 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Scored)
[PASS] 4.2.11 Ensure that the --rotate-certificates argument is not set to false (Scored)
[PASS] 4.2.12 Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)
[WARN] 4.2.13 Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers (Not Scored)

```

with details & recommendations: 

```
4.2.1 If using a Kubelet config file, edit the file to set authentication: anonymous: enabled to
false.
If using executable arguments, edit the kubelet service file
/etc/systemd/system/kubelet.service on each worker node and
set the below parameter in KUBELET_SYSTEM_PODS_ARGS variable.
--anonymous-auth=false
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload
systemctl restart kubelet.service
4.2.2 If using a Kubelet config file, edit the file to set authorization: mode to Webhook. If
using executable arguments, edit the kubelet service file
/etc/systemd/system/kubelet.service on each worker node and
set the below parameter in KUBELET_AUTHZ_ARGS variable.
--authorization-mode=Webhook
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload
systemctl restart kubelet.service
4.2.3 If using a Kubelet config file, edit the file to set authentication: x509: clientCAFile to
the location of the client CA file.
If using command line arguments, edit the kubelet service file
/etc/systemd/system/kubelet.service on each worker node and
set the below parameter in KUBELET_AUTHZ_ARGS variable.
--client-ca-file=<path/to/client-ca-file>
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload
systemctl restart kubelet.service
```

Do you have an idea about that ? Thanks for your help

**Comment by yoavrotems** [comment]
Hey could you please attach the debug logs? (run it with the flag -v 3) @THordeq

**Comment by THordeq** [comment]
I've attach the debug logs, tell me if you want more information

[kube-bench-github-issue.txt](https://github.com/aquasecurity/kube-bench/files/6507540/kube-bench-github-issue.txt)

**Comment by yoavrotems** [comment]
Hey thanks for the logs, I can now see the the problem is that you and the kube-bench are probably looking at different files.


> Reporting possible false positives on GKE CIS 4.2.1, 4.2.3 and 4.3.3.
> Running the kube-bench/job-gke.yaml against a Standard GKE Starter cluster (v1.18.15-gke.1501)
> 
> Results
> [FAIL] 4.2.1 Ensure that the --anonymous-auth argument is set to false (Scored)
> [FAIL] 4.2.2 Ensure that the --authorization-mode argument is not set to AlwaysAllow (Scored)
> [FAIL] 4.2.3 Ensure that the --client-ca-file argument is set as appropriate (Scored)
> 
> Upon investigation, the corresponding kube-config.yaml's on each worker node cluster did already have the settings
> specified in the remediation sections of the CIS GKE benchmark pdf.
> 
> ![image](https://user-images.githubusercontent.com/25078066/112196216-30f1fd80-8be1-11eb-9a43-126a5c5b8755.png)
> 
> The tests should have passed and are expected to pass as per Google documentation https://cloud.google.com/kubernetes-engine/docs/concepts/cis-benchmarks#status

You said you are using kube-config.yaml (which is costume? ) but in the logs you can see that 

> I0519 09:31:33.944547  254140 util.go:382] Substituting $kubeletconf with '/var/lib/kubelet/kubeconfig'

If you look farther in the ps logs you can see that this is really the config you are using:

> I0519 09:31:33.959989  254140 check.go:299] Command: "/bin/ps -fC kubelet"
> I0519 09:31:33.960003  254140 check.go:300] Output:
>  "UID          PID    PPID  C STIME TTY          TIME CMD\nroot        1560       1  3 07:09 ?        00:04:42 /home/kubernetes/bin/kubelet --v=2 --cloud-provider=gce --experimental-check-node-capabilities-before-mount=true --experimental-mounter-path=/home/kubernetes/containerized_mounter/mounter --cert-dir=/var/lib/kubelet/pki/ --cni-bin-dir=/home/kubernetes/bin **--kubeconfig=/var/lib/kubelet/kubeconfig** --image-pull-progress-deadline=5m --experimental-kernel-memcg-notification=true --max-pods=16 --non-masquerade-cidr=0.0.0.0/0 --network-plugin=cni --volume-plugin-dir=/home/kubernetes/flexvolume --node-status-max-images=25 --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --runtime-cgroups=/system.slice/containerd.service --registry-qps=10 --registry-burst=20 --config /home/kubernetes/kubelet-config.yaml --pod-sysctls=net.core.somaxconn=1024,net.ipv4.conf.all.accept_redirects=0,net.ipv4.conf.all.forwarding=1,net.ipv4.conf.all.route_localnet=1,net.ipv4.conf.default.

The tests are failing because Kubeconfig content is: 

> "
> apiVersion: v1
> kind: Config
> clusters:
> - cluster:
>     server: https://10.0.0.2
>     certificate-authority: '/etc/srv/kubernetes/pki/ca-certificates.crt'
>   name: default-cluster
> contexts:
> - context:
>     cluster: default-cluster
>     namespace: default
>     user: exec-plugin-auth
>   name: default-context
> current-context: default-context
> users:
> - name: exec-plugin-auth
>   user:
>     exec:
>       apiVersion: \"client.authentication.k8s.io/v1alpha1\"
>       command: '/home/kubernetes/bin/gke-exec-auth-plugin'
>       args: [\"--cache-dir\", '/var/lib/kubelet/pki/']
> "

As you can see it doesn't hold the values checked in 4.2.1, 4.2.2, 4.2.3
@THordeq

**Comment by tapoton** [comment]
Hi @yoavrotems 
Looks like it's a mistake in checks. You're talking about `--kubeconfig` argument, but the path to conf file is in `--config` argument. So the check uses $kubeletconf as `audit-config`, but it actually should use `$kubeletkubeconfig` variable.

**Comment by mozillazg** [comment]
Hi @tapoton

> So the check uses $kubeletconf as audit-config, but it actually should use $kubeletkubeconfig variable.

The check uses `$kubeletconf` as audit-config is expected.

The root cause is the old job didn't mount `/home/kubernetes` and that has been fixed via https://github.com/aquasecurity/kube-bench/pull/976

**Comment by tapoton** [comment]
Hi @mozillazg ,
I just checked the logs attached by @THordeq 
```
I0519 09:31:33.952444  254140 check.go:110] -----   Running check 4.2.1   -----
I0519 09:31:33.959989  254140 check.go:299] Command: "/bin/ps -fC kubelet"
I0519 09:31:33.960003  254140 check.go:300] Output:
 "UID          PID    PPID  C STIME TTY          TIME CMD\nroot        1560       1  3 07:09 ?        00:04:42 /home/kubernetes/bin/kubelet --v=2 --cloud-provider=gce --experimental-check-node-capabilities-before-mount=true --experimental-mounter-path=/home/kubernetes/containerized_mounter/mounter --cert-dir=/var/lib/kubelet/pki/ --cni-bin-dir=/home/kubernetes/bin --kubeconfig=/var/lib/kubelet/kubeconfig --image-pull-progress-deadline=5m --experimental-kernel-memcg-notification=true --max-pods=16 --non-masquerade-cidr=0.0.0.0/0 --network-plugin=cni --volume-plugin-dir=/home/kubernetes/flexvolume --node-status-max-images=25 --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --runtime-cgroups=/system.slice/containerd.service --registry-qps=10 --registry-burst=20 --config /home/kubernetes/kubelet-config.yaml --pod-sysctls=net.core.somaxconn=1024,net.ipv4.conf.all.accept_redirects=0,net.ipv4.conf.all.forwarding=1,net.ipv4.conf.all.route_localnet=1,net.ipv4.conf.default.forwarding=1,net.ipv4.ip_forward=1,net.ipv4.tcp_fin_timeout=60,net.ipv4.tcp_keepalive_intvl=60,net.ipv4.tcp_keepalive_probes=5,net.ipv4.tcp_keepalive_time=300,net.ipv4.tcp_rmem=4096 87380 6291456,net.ipv4.tcp_syn_retries=6,net.ipv4.tcp_tw_reuse=0,net.ipv4.tcp_wmem=4096 16384 4194304,net.ipv4.udp_rmem_min=4096,net.ipv4.udp_wmem_min=4096,net.ipv6.conf.default.accept_ra=0,net.netfilter.nf_conntrack_generic_timeout=600,net.netfilter.nf_conntrack_tcp_be_liberal=1,net.netfilter.nf_conntrack_tcp_timeout_close_wait=3600,net.netfilter.nf_conntrack_tcp_timeout_established=86400\n"
I0519 09:31:33.960946  254140 check.go:299] Command: "/bin/cat /var/lib/kubelet/kubeconfig"
I0519 09:31:33.960961  254140 check.go:300] Output:
 "apiVersion: v1\nkind: Config\nclusters:\n- cluster:\n    server: https://10.0.0.2\n    certificate-authority: '/etc/srv/kubernetes/pki/ca-certificates.crt'\n  name: default-cluster\ncontexts:\n- context:\n    cluster: default-cluster\n    namespace: default\n    user: exec-plugin-auth\n  name: default-context\ncurrent-context: default-context\nusers:\n- name: exec-plugin-auth\n  user:\n    exec:\n      apiVersion: \"client.authentication.k8s.io/v1alpha1\"\n      command: '/home/kubernetes/bin/gke-exec-auth-plugin'\n      args: [\"--cache-dir\", '/var/lib/kubelet/pki/']\n"
I0519 09:31:33.960973  254140 check.go:221] Running 1 test_items
I0519 09:31:33.960980  254140 test.go:151] In flagTestItem.findValue 
I0519 09:31:33.961010  254140 test.go:245] Flag '--anonymous-auth' does not exist
I0519 09:31:33.961113  254140 test.go:169] In pathTestItem.findValue 
I0519 09:31:33.961122  254140 test.go:247] Path '{.authentication.anonymous.enabled}' does not exist
```

Here you can see `Command: "/bin/cat /var/lib/kubelet/kubeconfig"` which is passed as `--kubeconfig`, but the benchmark says you need to check what's in the `--config` argument (`--config /home/kubernetes/kubelet-config.yaml`).
You can also see that the result of `cat` is:
```yml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://10.0.0.2
    certificate-authority: '/etc/srv/kubernetes/pki/ca-certificates.crt'
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: exec-plugin-auth
  name: default-context
current-context: default-context
users:
- name: exec-plugin-auth
  user:
    exec:
      apiVersion: "client.authentication.k8s.io/v1alpha1"
      command: '/home/kubernetes/bin/gke-exec-auth-plugin'
      args: ["--cache-dir", '/var/lib/kubelet/pki/']```

which is a kubelet connection config file, not the kubelet config.

**Comment by mozillazg** [comment]
@tapoton 

> Here you can see Command: "/bin/cat /var/lib/kubelet/kubeconfig" which is passed as --kubeconfig

The `"/bin/cat /var/lib/kubelet/kubeconfig"` is generated via parse `"/bin/cat $kubeletconf"`, it has nothing to do with `--kubeconfig`. And the way to get value of `$kubeletconf` is follow this rules:

> confs: A list of candidate configuration files for a component. kube-bench checks this list and selects the **first** config file that is found on the node. If none of the config files exists, kube-bench defaults conf to the value of defaultconf.
> 
> The selected config for a component can be referenced in controls using a variable in the form `$<component>conf`. In the example below, we reference the selected API server config file with the variable `$apiserverconf` in an audit command.

https://github.com/aquasecurity/kube-bench/blob/main/docs/controls.md#configuration-and-variables

[A list of candidate configuration files] for kubelet(`$kubeletconf`) is defined in config.yaml which include /var/lib/kubelet/kubeconfig:

https://github.com/aquasecurity/kube-bench/blob/2d6bf55ab2ae3e0b919312a6c5cf3ddada7eb214/cfg/config.yaml#L151-L174
