### ISSUE TITLE
Issues with custom compliance host scans

### ISSUE THREAD

**Issue by gurugautmm** [aquasecurity/kube-bench#853]
Customer ran custom compliance checks that were already included in Aqua (i.e. "Kube bench-eks-1.0-node" and "Kube bench-eks-1.0-policies"), and found multiple issues with the accuracy of the scan results.  I have attached a CSV file of a recent compliance scan we did on a few hosts.

In the CSV file, we added a few more columns on the far right to give more context to the issues that we faced.  This is a description of the new columns and what they mean:
Aquasec Check: Aquasec commands that were executed
CIS Check: In the latest version of CIS EKS benchmarks, each control item is tagged as either Manual or Automated (meaning that whether that control item should be manually or automatically verified) as per the CIS benchmark doc.
CIS Command: Commands that were executed as per CIS benchmark, by direct access to the eks node to run these commands.
Our Manual Test Result: After manually running the commands as per CIS Command, whether the test Passed or Failed.
Command output/result:  Our observation of the results when the CIS Command were executed.
AquaSec Scan analysis:  Comparing Aquasec's test results (as recorded in the columns labelled "Test Status" and "Actual Result") with the columns labelled "Our Manual Test Result" and "Command output/result", if Aquasec's test result is "FAIL" but our's is "PASS",  then this column will show "False Positive".  Otherwise, we will highlight the nature of the problem encountered for each control item

They are using the EKS env.

[how we ran the commands.pdf](https://github.com/aquasecurity/kube-bench/files/6194750/how.we.ran.the.commands.pdf)
[qa_eks_cis-7_dated_9Feb2021.xlsx](https://github.com/aquasecurity/kube-bench/files/6194751/qa_eks_cis-7_dated_9Feb2021.xlsx)

**Comment by yoavrotems** [comment]
Hey first thing sorry for the late response we were busy with releasing the new kube-bench version.
As I see there are some old format test in the yaml, but it should still work. 
Could you please attach the debug logs? (-v 3) 
And please use the new release of kube-bench this could be cause from a problem we already solved

**Comment by yoavrotems** [comment]
Hello @gurugautmm is this still an issue?

**Comment by yoavrotems** [comment]
I'm closing this issue since no response, @gurugautmm please feel free to reopen it it is still relevant
