### ISSUE TITLE
The --noremediations flag is ignored when using with --json flag

### ISSUE THREAD

**Issue by macEar** [aquasecurity/kube-bench#876]
There is --noremediations flag which allows us to disable printing of remediations section. Also there is --json flag which is for printing the results as JSON.

They work if we use them separately. But if we specify them both then --noremediations is ignored and there are remedations in the output JSON. It looks like:

```
"remediation":"Create a PSP as described in the Kubernetes documentation, ensuring that the\n.spec.hostIPC field is omitted or set to false.\n"
```

It's a bug.

**Comment by yoavrotems** [comment]
You are correct, but it is not a bug, it is the way the engine works, the print flags don't effect the data, its just effect the **printed** data to make it more convenient and human readable, the json is the data so we do not removing parts from there, but if you are using the json you can just ignore some properties or create something like filter script to remove your unnecessary properties
