### ISSUE TITLE
Image 0.6.1 missing in DockerHub

### ISSUE THREAD

**Issue by sfc-gh-jelsesiy** [aquasecurity/kube-bench#878]
The latest release tag https://github.com/aquasecurity/kube-bench/releases/tag/0.6.1 is not following the same naming convention and is also missing in DockerHub.

**Comment by yoavrotems** [comment]
Hey thanks for this, you are correct and the dockerhub image wasn't pushed because the version missed the v in the beginning. 
We fixed it by releasing v0.6.2 version  https://github.com/aquasecurity/kube-bench/discussions/880
