### ISSUE TITLE
etcd tests expects flags to be set with equal sign

### ISSUE THREAD

**Issue by bsnchan** [aquasecurity/kube-bench#88]
We currently run etcd using flags without the equal sign: 

For example, 1.4.11 will fail with this etcd flag style

```
etcd --data-dir /var/vcap/store/etcd
```

It looks like the tests assume that the equal sign is always set: https://github.com/aquasecurity/kube-bench/blob/4907843b7b61f1a95214203470dd41373cab3bd3/cfg/1.8/master.yaml#L945

Could the tests be updated to support both flag styles?

**Comment by lizrice** [comment]
Fixed by #89
