### ISSUE TITLE
Malformed JUnit Output

### ISSUE THREAD

**Issue by chlynott** [aquasecurity/kube-bench#883]
JUnit XML format incorrect when running kube-bench to print results to as JUnit and save Kubectl logs in XML format. If kube-bench is adding more than one `<testsuite>` , they need to be wrapped in `<testsuites>` for parsers to interpret them properly.  The remediation output has text similar to `<filename>` that is not being encoded properly when generating the JUnit XML output. 

 Link for JUnit XML format : https://www.ibm.com/docs/en/developer-for-zos/9.1.1?topic=formats-junit-xml-format

Missing :  XML declaration `<?xml version="1.0" encoding="UTF-8" ?>`
Missing : Root `<testsuites>`
Several JUnit XML  parsing errors (examples) : 
`JUnit XML parsing failed: 83:254: FATAL: Opening and ending tag mismatch: filename line 82 and system-out`
`JUnit XML parsing failed: 129:487: FATAL: StartTag: invalid element name` 

For this case we wanted to specifically upload the JUnit report artifacts in a GitLab pipeline. 

kube-bench was run as a job in an kubernetes cluster :
`kubectl apply -f kube-bench-targets-aks.
[kube-bench-targets-aks_yml.txt](https://github.com/aquasecurity/kube-bench/files/6561807/kube-bench-targets-aks_yml.txt)
yml`
`kubectl logs job/kube-bench-targets-aks > kube-bench-aks-targets.xml`

***yml for job in kube-bench-targets-aks_yml.txt
*** Logs in kubebenchAKS_junit_xml.txt 

kube-bench version 0.3.1

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"6c90dbd9d6bb1ae8a4c0b0778752be06873e7c55", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

--------------------------------------------------------------------------------
Commands we used to fix the issues : 
-- Add missing root `<testsuites>` (might have to upgrade grep):

   `- TOTALTESTS=$(grep "testsuite" kube-bench-aks-targets.xml | grep -oP "tests=\"(\d+)\"" | grep -oP "\d+" | awk '{ SUM += $1} END { print SUM }')`
   ` - TOTALFAILURES=$(grep "testsuite" kube-bench-aks-targets.xml | grep -oP "failures=\"(\d+)\"" | grep -oP "\d+" | awk '{ SUM += $1} END { print SUM }')`
    `- TOTALERRORS=$(grep "testsuite" kube-bench-aks-targets.xml | grep -oP "errors=\"(\d+)\"" | grep -oP "\d+" | awk '{ SUM += $1} END { print SUM }')`
   ` - TOTALTIME=$(grep "testsuite" kube-bench-aks-targets.xml | grep -oP "time=\"(\d+)\"" | grep -oP "\d+" | awk '{ SUM += $1} END { print SUM }')`
   ` - XMLLINE="<?xml version=\"1.0\" encoding=\"UTF-8\"?>"`
    `- TESTSUITESLINE="<testsuites id=\"$CI_JOB_ID\" name=\"kube-bench\" tests=\"$TOTALTESTS\" failures=\"$TOTALFAILURES\" errors=\"$TOTALERRORS\" time=\"$TOTALTIME\">"`

-- Add XML declaration at the start of the document : 

  `- echo -e "$XMLLINE\n$TESTSUITESLINE\n$(cat kube-bench-aks-targets.xml)\n</testsuites>" > kube-bench-aks-targets.xml`
   
-- HTML encode 'special characters' to be safe in the XML :

   
     `- sed -i 's/<filename>/\&#60;filename\&#62;/g' kube-bench-aks-targets.xml
    - sed -i 's/memory.available</memory.available\&#60;/g' kube-bench-aks-targets.xml
    - sed -i 's/nodefs.available</nodefs.available\&#60;/g' kube-bench-aks-targets.xml
    - sed -i 's/nodefs.inodesFree</nodefs.inodesFree\&#60;/g' kube-bench-aks-targets.xml
    - sed -i 's|<path/to/client-ca-file>|\&#60;path/to/client-ca-file\&#62;|g' kube-bench-aks-targets.xml
    - sed -i 's|<path/to/tls-certificate-file>|\&#60;path/to/tls-certificate-file\&#62;|g' kube-bench-aks-targets.xml
    - sed -i 's|<path/to/tls-key-file>|\&#60;path/to/tls-key-file\&#62;|g' kube-bench-aks-targets.xml `
----------------------------------------------------------------
  Please review and check how to make the system work as expected by wrapping in testsuites and properly encoding the XML text data. 

[kube-bench-targets-aks_yml.txt](https://github.com/aquasecurity/kube-bench/files/6561949/kube-bench-targets-aks_yml.txt)
[kubebenchAKS_junit_XML.txt](https://github.com/aquasecurity/kube-bench/files/6561735/kubebenchAKS_junit_XML.txt)

**Comment by yoavrotems** [comment]
@chlynott Thank you for reporting us about this issue, Can I ask a couple of questions? 
How long are you using kube-bench and Junit? 
Is there a special reason you are using kube-bench version 0.3.1? (latest is 0.6.3) 
Currently I will make a quick fix for Junit output but for what I see this hasn't been valid for over a year and nobody noticed so maybe its not in use? 

I also open a discussion about it [here](https://github.com/aquasecurity/kube-bench/discussions/919) if you can reply there on the relevance of Junit it will be helpful
