### ISSUE TITLE
CIS Kubernetes V1.20 Benchmark v1.0.0

### ISSUE THREAD

**Issue by yoavrotems** [aquasecurity/kube-bench#897]
New [CIS Kubernetes V1.20 Benchmark v1.0.0](https://workbench.cisecurity.org/benchmarks/6246) was published 2 weeks ago on May 19th 2021
And we should add support for it

**Comment by PushkarJ** [comment]
Hey @yoavrotems Big fan of kube-bench!! I would be very interested in contributing to support this new version. Would following this issue be a good idea to keep up to date on this item?
