### ISSUE TITLE
False positive for cis-1.6 section 1.1.9 (CNI file permissions) when using calico

### ISSUE THREAD

**Issue by cernst-mx** [aquasecurity/kube-bench#902]
**Overview**

This test expects the CNI files under /var/lib/cni/networks to have 644 (or more restrictive) which, in my case, they do with one exception.  Calico also creates a 'lock' file with 750 which causes the test to fail.

**How did you run kube-bench?**

kube-bench is run from Rancher via a sonobuoy plugin.

**What happened?**

The audit for 1.1.9 produced a warning:

1.1.9,Ensure that the Container Network Interface file permissions are set to 644 or more restrictive (Manual),"Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 <path/to/cni/files>
",warn,master,stat -c permissions=%a <path/to/cni/files>,,"Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 <path/to/cni/files>
",,,,manual,false

when checking the CNI files in:
ls -l /var/lib/cni/networks/k8s-pod-network/
total 92
-rw-r--r-- 1 root root 70 May 24 16:16 10.42.8.10
-rw-r--r-- 1 root root 70 May 24 16:16 10.42.8.11
-rw-r--r-- 1 root root 70 May 24 16:16 10.42.8.12
-rw-r--r-- 1 root root 70 May 24 16:16 10.42.8.14
-rw-r--r-- 1 root root 70 May 24 16:16 10.42.8.15
-rw-r--r-- 1 root root 70 May 24 16:16 10.42.8.16
-rw-r--r-- 1 root root 70 May 24 16:16 10.42.8.17
-rw-r--r-- 1 root root 70 May 24 16:16 10.42.8.18
-rw-r--r-- 1 root root 70 May 24 16:17 10.42.8.19
-rw-r--r-- 1 root root 70 May 24 16:03 10.42.8.2
-rw-r--r-- 1 root root 70 May 24 16:17 10.42.8.20
-rw-r--r-- 1 root root 70 May 24 16:18 10.42.8.21
-rw-r--r-- 1 root root 70 May 24 16:18 10.42.8.23
-rw-r--r-- 1 root root 70 May 24 16:18 10.42.8.24
-rw-r--r-- 1 root root 70 May 24 16:18 10.42.8.26
-rw-r--r-- 1 root root 70 May 26 19:27 10.42.8.29
-rw-r--r-- 1 root root 70 May 27 18:53 10.42.8.34
-rw-r--r-- 1 root root 70 Jun  1 22:29 10.42.8.38
-rw-r--r-- 1 root root 70 May 24 16:03 10.42.8.4
-rw-r--r-- 1 root root 70 Jun  4 15:47 10.42.8.47
-rw-r--r-- 1 root root 70 May 24 16:03 10.42.8.5
-rw-r--r-- 1 root root 70 Jun 10 12:48 10.42.8.52
-rw-r--r-- 1 root root 10 Jun 10 12:48 last_reserved_ip.0
-rwxr-x--- 1 root root  0 May 24 16:03 lock

**What did you expect to happen:**

The audit for 1.1.9 should pass as the lock file is not significant to the test

**Environment** 

Rancher RKE build cluster in AWS using calico CNI.  kube-bench run via sonobuoy plugin

[What is your version of Kubernetes? (run `kubectl version` or `oc version` on OpenShift.)]

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:21:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Anything else you would like to add:**

Simply adding an exclusion for the 'lock' file in the audit will resolve the issue:

   find /var/lib/cni/networks -type f **! -name lock** 2> /dev/null | xargs --no-run-if-empty stat -c permissions=%a

**Comment by yoavrotems** [comment]
Hey @cernst-mx Thanks for letting us know about it, I believe this is a too specific case, we usually keep as close to CIS benchmark as possible, with minor changes that will effect the test for example `--no-run-if-empty`.
Do you know if this issue is only applied to calico? or is it relevant to other cases? 
Because I tell you what I'm a bit reluctant about this change, on the one hand it shouldn't effect the tests, but on the other hand if it just unique case then we shouldn't specifically addressing it. 
I tried searching for documentation about it but didn't find it. 
Oh and also does it has to have running permissions? if it is a kind of mutex why 640 permissions are not enough?

**Comment by yoavrotems** [comment]
I'm closing until farther interaction.
