### ISSUE TITLE
"Message:Finding does not adhere to Amazon Finding Format"

### ISSUE THREAD

**Issue by stephanlindauer** [aquasecurity/kube-bench#903]
With version `0.6.2` i get recommendation text that doesn't fit the requirements of that field in the ASFF spec:
```
Number of findings that failed to import:2
Message:Finding does not adhere to Amazon Finding Format. data.Remediation.Recommendation.Text should NOT be longer than 512 characters.
Error Code:InvalidInput
```

**Comment by yoavrotems** [comment]
Could you add more information? 
Here you can see what information we need https://github.com/aquasecurity/kube-bench/blob/main/CONTRIBUTING.md#bugs

**Comment by yoavrotems** [comment]
Also would help to know what is the latest version you used that it worked since eks files wasn't changed for 7 months

**Comment by yoavrotems** [comment]
@stephanlindauer Do you might ran a different cfg?

**Comment by stephanlindauer** [comment]
thanks!

**Comment by adelwin** [comment]
I'm not sure if there's a regression or if something in AWS-SH has added some further checking.
I am getting something similar to this one.
```
2022/01/26 06:31:11 ID:arn:aws:securityhub:ap-southeast-1::product/aqua-security/kube-bench421940619307EKSnodeID+4.1.42022-01-26T06:31:11Z
2022/01/26 06:31:11 Message:Finding does not adhere to Amazon Finding Format. data.Remediation.Recommendation.Text should NOT be shorter than 1 characters.
2022/01/26 06:31:11 Error Code:InvalidInput
2022/01/26 06:31:11 Number of findings that failed to import:13
2022/01/26 06:31:11 ID:arn:aws:securityhub:ap-southeast-1::product/aqua-security/kube-bench421940619307EKSnodeID+5.1.12022-01-26T06:31:11Z
2022/01/26 06:31:11 Message:Finding does not adhere to Amazon Finding Format. data.Remediation.Recommendation.Text should NOT be shorter than 1 characters.
```
Should I open a new ticket or continue the convo here?

**Comment by yoavrotems** [comment]
@adelwin yes please open a new bug report with all of the needed information

**Comment by adelwin** [comment]
I just checked that the new image v0.6.6 has already addressed the recommendation string.
Thanks @yoavrotems

**Comment by yoavrotems** [comment]
Sure thing 👍
