### ISSUE TITLE
Ability to ignore etcd specific configuration

### ISSUE THREAD

**Issue by jaxxstorm** [aquasecurity/kube-bench#92]
Firstly, amazingly useful project! Thanks so much!

I'm using kubeadm to generate my configuration, and also using an external etcd.

I can ignore the etcd specific components using the group configuration:

```
./kube-bench master --group="1.1,1.2,1.3,1.4,1.6,1.7"
```

I have also removed etcd and flanneld from `cfg/config.yaml`

However, the configuration section is still showing failures because the etcd manifest doesn't exist:

```
[FAIL] 1.4.7 Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.8 Ensure that the etcd pod specification file ownership is set to root:root (Scored)
```

Is it actually possible to ignore this check by knowing it's etcd based and skipping it?

**Comment by ttousai** [comment]
@jaxxstorm closing this issue, please reopen if you still need this.
