### ISSUE TITLE
Problems with dpkg package prevent from installing/upgrading kube-bench

### ISSUE THREAD

**Issue by marcinbojko** [aquasecurity/kube-bench#925]
**Overview**

[A clear and concise description of what the bug is] 
During the installation/upgrade of kube-bench*.deb package several errors appear.

sudo dpkg -i kube-bench_0.6.3_linux_amd64.deb

**What happened?**
Error #1 
```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 25638 package 'kube-bench':
 missing 'Maintainer' field
```

Error #2
```
Preparing to unpack kube-bench_0.6.3_linux_amd64.deb ...
Unpacking kube-bench (0.6.3) over (0.5.0) ...
dpkg: error processing archive kube-bench_0.6.3_linux_amd64.deb (--install):
 error creating directory './etc/kube-bench/cfg/eks-1.0': No such file or directory
```
Looks like extra '.' prevents from installation of a package

Clean install
```
 sudo dpkg -i kube-bench_0.6.3_linux_amd64.deb
(Reading database ... 1535279 files and directories currently installed.)
Preparing to unpack kube-bench_0.6.3_linux_amd64.deb ...
Unpacking kube-bench (0.6.3) ...
dpkg: error processing archive kube-bench_0.6.3_linux_amd64.deb (--install):
 error creating directory './etc/kube-bench/cfg/eks-1.0': No such file or directory
Errors were encountered while processing:
 kube-bench_0.6.3_linux_amd64.deb
```

**What did you expect to happen:**
Flawless installation/upgrade
Filled-in 'Maintainer' field in dpkg package

**Environment** 
Linux Mint 20.x

**Anything else you would like to add:**
Error related with installation, not actual kube-bench usage.

**Comment by 0x646e78** [comment]
I'm impacted by this also, looking forward to a release which has the fix.
