### ISSUE TITLE
kube-bench unable to get kubectl version

### ISSUE THREAD

**Issue by lirkog86** [aquasecurity/kube-bench#93]
working on a 1.8.6 k8s cluster running on google.

kubectl version on my node is-

gke-gke13-default-pool-7e367c4e-sj0w ~ # kubectl version
Client Version: version.Info

{Major:"1", Minor:"8+", GitVersion:"v1.8.6-gke.0", GitCommit:"ee9a97661f14ee0b1ca31d6edd30480c89347c79", GitTreeState:"clean", BuildDate:"2018-01-05T03:38:14Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

error from kube-bench

[WARN] Unable to get kubectl version, using default version: 1.6
Reading 1.6 specific configuration file

**Comment by jaxxstorm** [comment]
@lirkog86 you'll need to specify a `KUBECONFIG` to get this working. Possibly `export KUBECONFIG=/etc/kubernetes/admin.conf` or wherever your kubelet's `KUBECONFIG` file lives on gke

**Comment by lirkog86** [comment]
i can't find the config file in my host. /etc/kubernetes does not have any conf files.

**Comment by jaxxstorm** [comment]
What OS are you using? Is it systemd based?

**Comment by lirkog86** [comment]
gke-gke13-default-pool-7e367c4e-sj0w ~ # cat /etc/os-release
BUILD_ID=10032.71.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=c4c6234ae4f384ce00819c41b48ca8f6f1fa3ba8
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=63
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=63
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos

**Comment by lirkog86** [comment]
is it possible the config file only exist on the master and not on the nodes?

**Comment by jaxxstorm** [comment]
what does `systemctl cat kubelet` return?

**Comment by lirkog86** [comment]
gke-gke13-default-pool-7e367c4e-sj0w ~ # systemctl cat kubelet
# /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes kubelet
Requires=network-online.target
After=network-online.target

[Service]
Restart=always
RestartSec=10
EnvironmentFile=/etc/default/kubelet
ExecStart=/home/kubernetes/bin/kubelet $KUBELET_OPTS

[Install]
WantedBy=multi-user.target

**Comment by jaxxstorm** [comment]
and what's in `/etc/default/kubelet` ?

**Comment by lirkog86** [comment]
KUBELET_OPTS="--v=2 --kube-reserved=cpu=70m,memory=1736Mi --allow-privileged=true --cgroup-root=/ --cloud-provider=gce --cluster-dns=10.19.240.10 --cluster-domain=cluster.local --pod-manifest-path=/etc/kubernetes/manifests --experimental-mounter-path=/home/kubernetes/containerized_mounter/mounter --experimental-check-node-capabilities-before-mount=true --cert-dir=/var/lib/kubelet/pki/  --enable-debugging-handlers=true --bootstrap-kubeconfig=/var/lib/kubelet/bootstrap-kubeconfig --kubeconfig=/var/lib/kubelet/kubeconfig --anonymous-auth=false --authorization-mode=Webhook --client-ca-file=/etc/srv/kubernetes/pki/ca-certificates.crt --cni-bin-dir=/home/kubernetes/bin --network-plugin=kubenet --volume-plugin-dir=/home/kubernetes/flexvolume --node-labels=beta.kubernetes.io/fluentd-ds-ready=true,cloud.google.com/gke-nodepool=default-pool --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5% --feature-gates=ExperimentalCriticalPodAnnotation=true"

**Comment by jaxxstorm** [comment]
okay, so do:

```
export KUBECONFIG=/var/lib/kubelet/kubeconfig
```

Then run `kube-bench` again. It should work
