### ISSUE TITLE
Kube-bench pod error - failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "“kube-bench”": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by nidiculageorge** [aquasecurity/kube-bench#932]
Hi Team,

We are running the following kube-bench yaml in an Azure AKS cluster.

Yaml Below

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
spec:
  template:
    metadata:
      labels:
        app: kube-bench
    spec:
      hostPID: true
      containers:
        - name: kube-bench
          image: aquasec/kube-bench:latest
          command: [“kube-bench”]
          volumeMounts:
            - name: var-lib-etcd
              mountPath: /var/lib/etcd
              readOnly: true
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: var-lib-kube-scheduler
              mountPath: /var/lib/kube-scheduler
              readOnly: true
            - name: var-lib-kube-controller-manager
              mountPath: /var/lib/kube-controller-manager
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: lib-systemd
              mountPath: /lib/systemd/
              readOnly: true
            - name: srv-kubernetes
              mountPath: /srv/kubernetes/
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
              # /usr/local/mount-from-host/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
              # You can omit this mount if you specify --version as part of the command.
            - name: usr-bin
              mountPath: /usr/local/mount-from-host/bin
              readOnly: true
            - name: etc-cni-netd
              mountPath: /etc/cni/net.d/
              readOnly: true
            - name: opt-cni-bin
              mountPath: /opt/cni/bin/
              readOnly: true
      nodeSelector:
       beta.kubernetes.io/os: linux  
      restartPolicy: Never
      volumes:
        - name: var-lib-etcd
          hostPath:
            path: "/var/lib/etcd"
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: var-lib-kube-scheduler
          hostPath:
            path: "/var/lib/kube-scheduler"
        - name: var-lib-kube-controller-manager
          hostPath:
            path: "/var/lib/kube-controller-manager"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: lib-systemd
          hostPath:
            path: "/lib/systemd"
        - name: srv-kubernetes
          hostPath:
            path: "/srv/kubernetes"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
        - name: usr-bin
          hostPath:
            path: "/usr/bin"
        - name: etc-cni-netd
          hostPath:
            path: "/etc/cni/net.d/"
        - name: opt-cni-bin
          hostPath:
            path: "/opt/cni/bin/"

While this is applied the job is getting created ,but the pod is in Start Error ,when described we can see the following error

  Normal   Scheduled  9m28s  default-scheduler  Successfully assigned default/kube-bench-xxq6p to aks-vmidsemuat-77969286-vmss000001
  Normal   Pulling    9m28s  kubelet            Pulling image "aquasec/kube-bench:latest"
  Normal   Pulled     9m25s  kubelet            Successfully pulled image "aquasec/kube-bench:latest" in 2.178658758s
  Normal   Created    9m25s  kubelet            Created container kube-bench
  Warning  Failed     9m25s  kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "“kube-bench”": executable file not found in $PATH: unknown

KubeBench Link that we checked

https://k21academy.com/docker-kubernetes/kubernetes-security/kube-bench-cis/#eks

[kube-bencherror.txt](https://github.com/aquasecurity/kube-bench/files/6807211/kube-bencherror.txt)

Could you please check and let me know ?

**Comment by yoavrotems** [comment]
Could you try it please with version 0.6.3? instead of latest

**Comment by nidiculageorge** [comment]
@yoavrotems The issue is resolved.The issue occured because there was already a kube bench running in my cluster.When i removed that its working fine

**Comment by yoavrotems** [comment]
OK happy to see it solved 👍
