### ISSUE TITLE
Unable to Install kube-bench on EKS worker nodes

### ISSUE THREAD

**Issue by damerakd** [aquasecurity/kube-bench#962]
**Overview**
Getting below error when installing kube-bench on EKS worker node using the below instructions:

KUBEBENCH_URL=$(curl -s https://api.github.com/repos/aquasecurity/kube-bench/releases/latest | jq -r '.assets[] | select(.name | contains("amd64.rpm")) | .browser_download_url')

sudo yum install -y $KUBEBENCH_URL

===========

Loaded plugins: priorities, update-motd, versionlock

kube-bench_0.6.3_linux_amd64.rpm                                                                                                         | 7.6 MB  00:00:00
Examining /var/tmp/yum-root-7ZoRdP/kube-bench_0.6.3_linux_amd64.rpm: kube-bench-0.6.3-1.x86_64
Marking /var/tmp/yum-root-7ZoRdP/kube-bench_0.6.3_linux_amd64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package kube-bench.x86_64 0:0.6.3-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================
 Package                            Arch                           Version                          Repository                                             Size
================================================================================================================================================================
Installing:
 kube-bench                         x86_64                         0.6.3-1                          /kube-bench_0.6.3_linux_amd64                          18 M

Transaction Summary
================================================================================================================================================================
Install  1 Package

Total size: 18 M
Installed size: 18 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : kube-bench-0.6.3-1.x86_64                                                                                                                    1/1
Error unpacking rpm package kube-bench-0.6.3-1.x86_64
error: unpacking of archive failed on file /etc/kube-bench/cfg: cpio: rename
  Verifying  : kube-bench-0.6.3-1.x86_64                                                                                                                    1/1

Failed:
  kube-bench.x86_64 0:0.6.3-1

Complete!

**What did you expect to happen:**

To be installed successfully

**Environment** 

Tested on EKS 1.16 and above

**Running processes**

[Please include the output from running `ps -eaf | grep kube` on the affected node. This will allow us to check what Kubernetes processes are running, and how this compares to what kube-bench detected.]

ps-eaf | grep kube

root      2975     1  1 21:18 ?        00:00:02 /usr/bin/kubelet --cloud-provider aws --config /etc/kubernetes/kubelet/kubelet-config.json --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime docker --network-plugin cni --node-ip=172.31.5.1 --pod-infra-container-image=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1 --v=2 --node-labels=eks.amazonaws.com/nodegroup-image=ami-0539517fda76b726e,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=qefrg
root      3642  3607  0 21:18 ?        00:00:00 kube-proxy --v=2 --config=/var/lib/kube-proxy-config/config
root      5818  2653  0 21:21 pts/0    00:00:00 grep --color=auto kube

**Comment by yoavrotems** [comment]
Please let me know if this is still an issue in v0.6.5
