### ISSUE TITLE
Kube-bench is not working on arm/64 worker node

### ISSUE THREAD

**Issue by abhishekjaiswal06** [aquasecurity/kube-bench#963]
I followed the documentation to set up kub-bench as a job on my worker node. Everything is working as expected but container is failing. When i checked logs it is showing below error

standard_init_linux.go:228: exec user process caused: exec format error

Below are my manifest file, I am using aquasec/kube-bench:latest image.

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  namespace: kube-system
spec:
  template:
    spec:
      hostPID: true
      containers:
        - name: kube-bench
          image: aquasec/kube-bench:latest
          command: ["kube-bench", "--benchmark", "eks-1.0.1"]
          volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"

Note: As per my understanding it is not working as my worked node based on arm/64 processor. Can you suggest me a way around to run kube-bench on arm/64 based worker node.

**Comment by Effex-D** [comment]
I'm also running into this issue, where kube-bench is failing on a hybrid Kubernetes cluster containing X86_64 and ARM processors.

Are there any plans or suggestions on how to implement this for ARM?
