### ISSUE TITLE
 Unable to install kube-bench on openshift nodes

### ISSUE THREAD

**Issue by ragashreeshekar** [aquasecurity/kube-bench#972]
**Overview**
Unable to install kube-bench on openshift nodes 

**How did you run kube-bench?**

I have followed the following approach to deploy the kube-bench pod in openshift cluster.
It seems the pod is getting scheduled, I am able to pull the container image however there is an issue in creating the pod sandbox.

$ kubectl apply -f job.yaml
job.batch/kube-bench created

**What happened?**

Kube-bench pod creation is failing due to following error
```
$ kubectl get pods
NAME                      READY   STATUS              RESTARTS   AGE
kube-bench-cmwjd   0/1     ContainerCreating   0          3s

$ kubectl describe pod kube-bench-cmwjd
Events:
  Type     Reason                  Age        From               Message
  ----     ------                  ----       ----               -------
  Normal   Scheduled               6m27s      default-scheduler  Successfully assigned default/kube-bench-cmwjd to worker-2
  Warning  FailedCreatePodSandBox  5m30s      kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_kube-bench-cmwjd_default_ff06adc0-1369-418c-86cc-53bdcd573db9_0(5af8f772ef8145e0ba8a8a2e85bcbf20f7d35a2adc2dea4869120fb436c9af99): error adding pod default_kube-bench-cmwjd to CNI network "multus-cni-network": Multus: [default/kube-bench-cmwjd]: error getting pod: Get "https://[api-int.test.net]:6443/api/v1/namespaces/default/pods/kube-bench-cmwjd?timeout=1m0s": dial tcp: i/o timeout
```

Not sure why the kube-bench pod is considering https://[api-int.test.net] as API endpoint and not https://api-int.test.net as defined in the kubeconfig. Could you please assist in running the kube-bench assessment?

Also, this document is unclear to me - https://github.com/aquasecurity/kube-bench/blob/main/docs/running.md#running-on-openshift
- How to run the assessment as a crio container against docker container? Is it supported by kube-bench?
- While running in K8s, what modifications needs to be done at the job level, could you please elaborate?

**What did you expect to happen:**

kube-bench job successfully created along with kube-bench pod and providing the benchmark results

**Environment** 
OpenShift - 4.x
Kubernetes - Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+051ac4f", GitCommit:"051ac4f6786868fa0316800752e1905f31830383", GitTreeState:"clean", BuildDate:"2021-07-16T17:46:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
CoreOS version - Red Hat Enterprise Linux CoreOS 48.84.202107202156-0 (Ootpa)

**Comment by tonyqui** [comment]
Hello @ragashreeshekar, I regularly run jobs on openshift cluster without no issue.
Since there are multiple jobs in this repo, would you mind to paste here the content of the job file you're applying to openshift to see its content?

**Comment by ragashreeshekar** [comment]
@tonyqui Thanks for your response. 
I have used the https://raw.githubusercontent.com/aquasecurity/kube-bench/main/job.yaml job. 

With this, a new error is arising, details as follows:
Pods
```
[root@sectinstance ~]# kubectl get pods
NAME               READY   STATUS             RESTARTS   AGE
kube-bench-c55v7   0/1     ImagePullBackOff   0          29m
nginx              1/1     Running            0          29d
nks-ubuntu         1/1     Running            0          23d
```

Pod description
```
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       51s                default-scheduler  Successfully assigned default/kube-bench-c55v7 to worker-2
  Normal   AddedInterface  50s                multus             Add eth0 [10.254.12.38/23] from openshift-sdn
  Warning  Failed          40s                kubelet            Failed to pull image "aquasec/kube-bench:0.6.3": rpc error: code = Unknown desc = Error reading manifest 0.6.3 in registry.connect.redhat.com/aquasec/kube-bench: manifest unknown: manifest unknown
  Warning  Failed          40s                kubelet            Error: ErrImagePull
  Normal   BackOff         40s                kubelet            Back-off pulling image "aquasec/kube-bench:0.6.3"
  Warning  Failed          40s                kubelet            Error: ImagePullBackOff
  Normal   Pulling         27s (x2 over 49s)  kubelet            Pulling image "aquasec/kube-bench:0.6.3"

```

**Comment by tonyqui** [comment]
To me this does not relate to kube-bench delivery.

Image is correctly published on [dockerhub](https://hub.docker.com/layers/aquasec/kube-bench/0.6.3/images/sha256-e02aa2eb58c9a6bee9e2b060684051be14b266f0e9952cadd8f71f32f578b5d7?context=explore).
I'd suggest to check your configuration (openshift?) to check that dockerhub is correctly listed in image registry section of the cluster.
Eventually you could even log into one of the nodes and try to pull the image manually, using docker/crio-o/podman container engine.
