### ISSUE TITLE
Add support for CIS 1.3.0 spec supporting Kubernetes 1.9

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#99]

**Comment by netdisciple** [comment]
probably related to this error message im seeing after using the docker container to product the executable.

```
error opening master controls file: open ./cfg/1.9//master.yaml: no such file or directory

**Comment by Roland0** [comment]
I managed to get around this by simply creating a symlink for 1.9 => 1.8 in the cfg directory

ie 


`sudo ln -s 1.8/ 1.9`

```
k8s-node@k8s-01:~/cfg$ ls -l
total 16
drwxr-xr-x 2 root root 4096 Mar 15 16:50 1.6
drwxr-xr-x 2 root root 4096 Mar 15 16:50 1.7
drwxr-xr-x 2 root root 4096 Mar 15 16:50 1.8
lrwxrwxrwx 1 root root    4 Mar 16 15:59 1.9 -> 1.8/
-rw-r--r-- 1 root root 2550 Mar 15 16:50 config.yaml
```

Clearly this is sub-optimal and I certainly couldn't vouch for the accuracy of the results, but it will certainly get it running, probably just minus 1.9 specific tests.

**Comment by lizrice** [comment]
There isn't a CIS spec for 1.9 or 1.10 (at least not at time of writing) but I've made a change to fall back to the 1.8 tests for these versions

**Comment by andrewrynhard** [comment]
> There isn't a CIS spec for 1.9 or 1.10 (at least not at time of writing) but I've made a change to fall back to the 1.8 tests for these versions

Where might we be able to track progress on any potential spec for 1.9+?
