### ISSUE TITLE
False file permission failures on Bottlerocket nodes

### ISSUE THREAD

**Issue by abhay-krishna** [aquasecurity/kube-bench#996]
Hi, I tried running Kube-bench tests on a cluster provisioned with Bottlerocket nodes. The test results showed a lot of failures corresponding to permissions on pod specification files and kubeconfig files. Upon checking the controlplane node however, I found all the static pods manifests were there and also had required permissions. I suspect the issue is that Bottlerocket places the pod manifests and `.conf` files in a slightly different location on the host which is not being checked under in [config.yaml](https://github.com/aquasecurity/blob/main/cfg/config.yaml) embedded in the `aquasec/kube-bench` image, so it reports it as a failure since it cannot find the file in the first place.

I validated this by building my own image of Kube-bench with a modified config.yaml that includes the paths that Bottlerocket puts the manifests at, and all the previously failing tests passed.

I would like for Bottlerocket support to be added by including the new paths in the default config.yaml. I'd be happy to open a PR if you welcome that.

**Results with default kube-bench config and image**

```
[FAIL] 1.1.1 Ensure that the API server pod specification file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.2 Ensure that the API server pod specification file ownership is set to root:root (Automated)
[FAIL] 1.1.3 Ensure that the controller manager pod specification file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.4 Ensure that the controller manager pod specification file ownership is set to root:root (Automated)
[FAIL] 1.1.5 Ensure that the scheduler pod specification file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.6 Ensure that the scheduler pod specification file ownership is set to root:root (Automated)
[FAIL] 1.1.13 Ensure that the admin.conf file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.14 Ensure that the admin.conf file ownership is set to root:root (Automated)
[FAIL] 1.1.15 Ensure that the scheduler.conf file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.16 Ensure that the scheduler.conf file ownership is set to root:root (Automated)
[FAIL] 1.1.17 Ensure that the controller-manager.conf file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.18 Ensure that the controller-manager.conf file ownership is set to root:root (Automated)
[FAIL] 1.2.5 Ensure that the --kubelet-certificate-authority argument is set as appropriate (Automated)
[FAIL] 1.2.15 Ensure that the admission control plugin PodSecurityPolicy is set (Automated)

== Summary total ==
34 checks PASS
14 checks FAIL
12 checks WARN
4 checks INFO
```

**Results with custom kube-bench config and image**

```
[FAIL] 1.2.5 Ensure that the --kubelet-certificate-authority argument is set as appropriate (Automated)
[FAIL] 1.2.15 Ensure that the admission control plugin PodSecurityPolicy is set (Automated)

== Summary total ==
46 checks PASS
2 checks FAIL
12 checks WARN
4 checks INFO
```

**Configuration files**

The first time I ran it using the `aquasec/kube-bench:latest`  in the Kubernetes Job spec, which would have the `cfg/config.yaml` from main. The second time, I used an image that I locally built and pushed to ECR, and it had the modified config file embedded in it.

**Comment by yoavrotems** [comment]
If you could please attach the -v 3 logs it will be great and I could know better what is wrong.
